/*
 * Copyright (c) 2026, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

use crate::parser::{AsmInstruction, Handler, Operand, Program};
use crate::registers::{resolve_register, Arch};
use crate::shared::{get_immediate_value, resolve_field_ref, resolve_label, substitute_macro, w};
use std::collections::HashMap;
use std::fmt::Write;

pub fn generate(program: &Program) -> String {
    let mut out = String::new();

    w!(out, "# Generated by asmintgen -- DO NOT EDIT");
    w!(out, ".intel_syntax noprefix");
    w!(out);

    // On macOS, symbols need an underscore prefix
    w!(out, "#ifdef __APPLE__");
    w!(out, "#define CSYM(name) _##name");
    w!(out, "#else");
    w!(out, "#define CSYM(name) name");
    w!(out, "#endif");
    w!(out);

    w!(out, ".text");
    w!(out);

    // Generate dispatch table
    // The table contains absolute addresses that need relocation, so on Linux
    // it must go in .data.rel.ro (not .rodata) to avoid DT_TEXTREL in PIE.
    w!(out, "#ifdef __APPLE__");
    w!(out, ".section __DATA,__const");
    w!(out, "#else");
    w!(out, ".section .data.rel.ro");
    w!(out, "#endif");
    w!(out, ".p2align 3");
    w!(out, "asm_dispatch_table:");

    // Collect handler names for the dispatch table
    let handler_names: HashMap<String, usize> = program
        .handlers
        .iter()
        .enumerate()
        .map(|(i, h)| (h.name.clone(), i))
        .collect();

    // The opcode type is u8, so we need exactly 256 entries. Known opcodes
    // get their handler, everything else (including out-of-range values) gets
    // the fallback handler.
    for opcode in &program.opcode_list {
        if handler_names.contains_key(opcode.as_str()) {
            w!(out, "    .quad asm_handler_{opcode}");
        } else {
            w!(out, "    .quad asm_handler_fallback");
        }
    }
    for _ in program.opcode_list.len()..256 {
        w!(out, "    .quad asm_handler_fallback");
    }
    w!(out);

    w!(out, ".text");
    w!(out);

    // Generate entry point
    generate_entry_point(&mut out, program);

    // Generate fallback handler
    generate_fallback_handler(&mut out, program);

    // Generate each handler
    for handler in &program.handlers {
        generate_handler(&mut out, handler, program);
    }

    // Mark stack as non-executable (required by Linux linker)
    w!(out, "#ifndef __APPLE__");
    w!(out, ".section .note.GNU-stack,\"\",@progbits");
    w!(out, "#endif");

    out
}

fn generate_entry_point(out: &mut String, program: &Program) {
    // void asm_interpreter_entry(u8 const* bytecode, u32 entry_point, Value* values, Interpreter* interp)
    // System V AMD64: rdi=bytecode, esi=entry_point, rdx=values, rcx=interp
    w!(out, ".globl CSYM(asm_interpreter_entry)");
    w!(out, ".p2align 4");
    w!(out, "CSYM(asm_interpreter_entry):");

    // Save callee-saved registers
    w!(out, "    push rbp");
    w!(out, "    mov rbp, rsp");
    w!(out, "    push rbx");
    w!(out, "    push r12");
    w!(out, "    push r13");
    w!(out, "    push r14");
    w!(out, "    push r15");
    // Align stack to 16 bytes (pushed rbp + 5 regs = 48 bytes, need one more for alignment)
    w!(out, "    sub rsp, 8");

    // Set up pinned registers
    // rdi=bytecode (pb), esi=entry_point (pc), rdx=values, rcx=interp
    w!(out, "    mov r14, rdi          # pb = bytecode base");
    w!(out, "    mov r13d, esi         # pc = entry_point");
    w!(out, "    mov r15, rdx          # values = values array");
    // Store Interpreter* on the stack for C++ calls, pin exec_ctx instead
    let interp_ctx = program
        .constants
        .get("INTERPRETER_RUNNING_EXECUTION_CONTEXT")
        .copied()
        .unwrap_or(0);
    w!(
        out,
        "    mov QWORD PTR [rbp - 48], rcx  # save Interpreter*"
    );
    w!(
        out,
        "    mov rbx, QWORD PTR [rcx + {interp_ctx}]  # exec_ctx"
    );
    w!(
        out,
        "    lea r12, [rip + asm_dispatch_table]  # dispatch table"
    );

    // Dispatch to first instruction
    w!(out, "    movzx eax, BYTE PTR [r14 + r13]");
    w!(out, "    jmp [r12 + rax * 8]");
    w!(out);
}

fn generate_fallback_handler(out: &mut String, program: &Program) {
    // The fallback handler calls into C++ for any unhandled instruction.
    // extern "C" i64 asm_fallback_handler(Interpreter* interp, u32 pc);
    // Returns >= 0: new pc to dispatch to. Returns < 0: exit.
    w!(out, ".p2align 4");
    w!(out, "asm_handler_fallback:");
    // Set up args: rdi=interp (from stack), esi=pc (r13d)
    w!(out, "    mov rdi, QWORD PTR [rbp - 48]");
    w!(out, "    mov esi, r13d");
    w!(out, "    call CSYM(asm_fallback_handler)");
    // Check for exit (return < 0)
    w!(out, "    test rax, rax");
    w!(out, "    js .Lexit");
    // Reload exec_ctx, pb, and values (exception handling may have
    // unwound inline frames, changing the running execution context).
    emit_state_reload(out, program);
    // New pc from return value
    w!(out, "    mov r13d, eax");
    emit_dispatch(out);
    w!(out);

    // Exit path: restore callee-saved registers and return
    w!(out, ".Lexit:");
    w!(out, "    add rsp, 8");
    w!(out, "    pop r15");
    w!(out, "    pop r14");
    w!(out, "    pop r13");
    w!(out, "    pop r12");
    w!(out, "    pop rbx");
    w!(out, "    pop rbp");
    w!(out, "    ret");
    w!(out);
}

/// Emit instructions to reload exec_ctx (rbx), pb (r14) and values (r15)
/// from the Interpreter* saved on the stack. Uses rcx as scratch.
fn emit_state_reload(out: &mut String, program: &Program) {
    let interp_ctx = program
        .constants
        .get("INTERPRETER_RUNNING_EXECUTION_CONTEXT")
        .copied()
        .unwrap_or(0);
    let exec_executable = program
        .constants
        .get("EXECUTION_CONTEXT_EXECUTABLE")
        .copied()
        .unwrap_or(0);
    let exec_bytecode = program
        .constants
        .get("EXECUTABLE_BYTECODE_DATA")
        .copied()
        .unwrap_or(0);
    let sizeof_execctx = program
        .constants
        .get("SIZEOF_EXECUTION_CONTEXT")
        .copied()
        .unwrap_or(0);
    w!(out, "    mov rcx, QWORD PTR [rbp - 48]");
    w!(out, "    mov rbx, QWORD PTR [rcx + {interp_ctx}]");
    w!(out, "    mov rcx, QWORD PTR [rbx + {exec_executable}]");
    w!(out, "    mov r14, QWORD PTR [rcx + {exec_bytecode}]");
    w!(out, "    lea r15, [rbx + {sizeof_execctx}]");
}

fn emit_dispatch(out: &mut String) {
    w!(out, "    movzx eax, BYTE PTR [r14 + r13]");
    w!(out, "    jmp [r12 + rax * 8]");
}

fn emit_dispatch_with_size(out: &mut String, size: u32) {
    w!(out, "    add r13d, {size}");
    emit_dispatch(out);
}

/// Get the handler's instruction size: from explicit size= attribute, or from Bytecode.def.
fn handler_size(handler: &Handler, program: &Program) -> u32 {
    if let Some(size) = handler.size {
        return size;
    }
    let layout = program.op_layouts.get(&handler.name).unwrap_or_else(|| {
        panic!(
            "No Bytecode.def layout for handler '{}' and no explicit size",
            handler.name
        )
    });
    layout.size.unwrap_or_else(|| {
        panic!(
            "Handler '{}' is variable-length; use dispatch_variable instead of bare dispatch",
            handler.name
        )
    }) as u32
}

fn generate_handler(out: &mut String, handler: &Handler, program: &Program) {
    w!(out, ".p2align 4");
    w!(out, "asm_handler_{}:", handler.name);

    let mut label_counter: usize = 0;
    // Expand macros and emit instructions
    for insn in &handler.instructions {
        emit_instruction(out, insn, handler, program, &mut label_counter);
    }

    w!(out);
}

fn resolve_op(op: &Operand, handler: &Handler, program: &Program) -> String {
    match op {
        Operand::Register(name) => {
            resolve_register(name, Arch::X86_64).unwrap_or_else(|| name.clone())
        }
        Operand::Immediate(val) => format!("{val}"),
        Operand::Constant(name) => {
            if let Some(val) = program.constants.get(name) {
                format!("{val}")
            } else {
                name.clone()
            }
        }
        Operand::Memory { base, index, scale } => {
            let base_r = resolve_register(base, Arch::X86_64).unwrap_or_else(|| base.clone());
            match (index, scale) {
                (Some(idx), Some(sc)) => {
                    let idx_r = resolve_register(idx, Arch::X86_64).unwrap_or_else(|| idx.clone());
                    // Try to parse scale as immediate
                    let sc_val = program
                        .constants
                        .get(sc.as_str())
                        .copied()
                        .unwrap_or_else(|| sc.parse().unwrap_or(1));
                    format!("[{base_r} + {idx_r} * {sc_val}]")
                }
                (Some(idx), None) => {
                    // idx could be a field ref, immediate offset, constant, or register
                    if let Some(val) = resolve_field_ref(idx, handler, program) {
                        format!("[{base_r} + {val}]")
                    } else if let Some(val) = program.constants.get(idx.as_str()) {
                        format!("[{base_r} + {val}]")
                    } else if let Ok(val) = idx.parse::<i64>() {
                        format!("[{base_r} + {val}]")
                    } else {
                        let idx_r =
                            resolve_register(idx, Arch::X86_64).unwrap_or_else(|| idx.clone());
                        format!("[{base_r} + {idx_r}]")
                    }
                }
                (None, _) => format!("[{base_r}]"),
            }
        }
        Operand::Label(name) => name.clone(),
        Operand::FieldRef(name) => {
            let layout = program
                .op_layouts
                .get(&handler.name)
                .unwrap_or_else(|| panic!("No Bytecode.def layout for handler '{}'", handler.name));
            let offset = layout.field_offsets.get(name).unwrap_or_else(|| {
                panic!(
                    "No field '{}' in Bytecode.def for opcode '{}'",
                    name, handler.name
                )
            });
            format!("{offset}")
        }
    }
}

fn emit_instruction(out: &mut String, insn: &AsmInstruction, handler: &Handler, program: &Program, label_counter: &mut usize) {
    let m = &insn.mnemonic;

    match m.as_str() {
        "label" => {
            if let Some(Operand::Label(name)) = insn.operands.first() {
                // Local labels get handler prefix
                if name.starts_with('.') {
                    w!(out, ".Lasm_{}{name}:", handler.name);
                } else {
                    w!(out, "{name}:");
                }
            }
        }

        // Macro invocations
        _ if program.macros.contains_key(m) => {
            let mac = program.macros[m].clone();
            // Build parameter substitution map
            let mut param_map: HashMap<String, String> = HashMap::new();
            for (i, param) in mac.params.iter().enumerate() {
                if let Some(op) = insn.operands.get(i) {
                    param_map.insert(param.clone(), resolve_op(op, handler, program));
                }
            }
            // Expand macro body
            for body_insn in &mac.body {
                let expanded = substitute_macro(body_insn, &param_map);
                emit_instruction(out, &expanded, handler, program, label_counter);
            }
        }

        // reload_exec_ctx: reload the pinned exec_ctx register from Interpreter*
        "reload_exec_ctx" => {
            let interp_ctx = program
                .constants
                .get("INTERPRETER_RUNNING_EXECUTION_CONTEXT")
                .copied()
                .unwrap_or(0);
            w!(out, "    mov rcx, QWORD PTR [rbp - 48]");
            w!(out, "    mov rbx, QWORD PTR [rcx + {interp_ctx}]");
        }

        // dispatch_variable pseudo-instruction: advance pc by value in register and dispatch
        "dispatch_variable" => {
            if let Some(op) = insn.operands.first() {
                let reg = resolve_op(op, handler, program);
                let reg32 = to_32bit_reg(&reg);
                w!(out, "    add r13d, {reg32}");
                emit_dispatch(out);
            }
        }

        // dispatch_next: advance pc by the handler's instruction size and dispatch
        "dispatch_next" => {
            let size = handler_size(handler, program);
            emit_dispatch_with_size(out, size);
        }

        // call_slow_path pseudo-instruction
        // Calls a slow path C function: i64 func(Interpreter*, u32 pc)
        // Returns >= 0: new pc to dispatch to. Returns < 0: exit.
        // This is TERMINAL: it dispatches after return, control doesn't come back.
        // After the call, pb and values are reloaded from the running execution
        // context, since exception handling may have unwound inline frames.
        "call_slow_path" => {
            if let Some(Operand::Register(func_name)) = insn.operands.first() {
                // Set up args: rdi=interp (from stack), esi=pc
                w!(out, "    mov rdi, QWORD PTR [rbp - 48]");
                w!(out, "    mov esi, r13d");
                w!(out, "    call CSYM({func_name})");
                // Check for exit (return < 0)
                w!(out, "    test rax, rax");
                w!(out, "    js .Lexit");
                // Reload pb and values from the running execution context.
                // This is necessary because exception handling may unwind
                // inline frames, changing the current executable and values.
                emit_state_reload(out, program);
                // Update pc from return value and dispatch
                w!(out, "    mov r13d, eax");
                emit_dispatch(out);
            }
        }

        // call_helper pseudo-instruction
        // Calls a helper C function: u64 func(u64 value)
        // The value from t1 (rcx) is passed as the first argument.
        // Result is in rax (t0). NOT terminal: handler continues after.
        "call_helper" => {
            if let Some(Operand::Register(func_name)) = insn.operands.first() {
                w!(out, "    mov rdi, rcx");
                w!(out, "    call CSYM({func_name})");
            }
        }

        // call_interp pseudo-instruction
        // Calls a C++ helper: i64 func(Interpreter*, u32 pc)
        // Same args as call_slow_path, but NON-TERMINAL: result in rax (t0),
        // handler continues after.
        "call_interp" => {
            if let Some(Operand::Register(func_name)) = insn.operands.first() {
                w!(out, "    mov rdi, QWORD PTR [rbp - 48]");
                w!(out, "    mov esi, r13d");
                w!(out, "    call CSYM({func_name})");
            }
        }

        // double_to_int32 dst, src_fpr, fail_label
        // Truncate double to int32 with strict round-trip check.
        // Fails if fractional, out of i32 range, or NaN.
        // Clobbers rcx (t1) and xmm3 (ft3).
        "double_to_int32" => {
            if insn.operands.len() >= 3 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                let fail = resolve_label(&insn.operands[2], handler);
                // Truncate to i64 first, check for cvttsd2si overflow sentinel
                w!(out, "    cvttsd2si {dst}, {src}");
                w!(out, "    mov rcx, 0x8000000000000000");
                w!(out, "    cmp {dst}, rcx");
                w!(out, "    je {fail}");
                // Check it fits in i32
                w!(out, "    movsxd rcx, {}", to_32bit_reg(&dst));
                w!(out, "    cmp {dst}, rcx");
                w!(out, "    jne {fail}");
                // Round-trip: convert back and compare
                w!(out, "    cvtsi2sd xmm3, {dst}");
                w!(out, "    ucomisd {src}, xmm3");
                w!(out, "    jne {fail}");
            }
        }

        // js_to_int32 dst, src_fpr, fail_label
        // Truncate double to int64. cvttsd2si returns 0x8000000000000000 on
        // overflow/NaN, which we detect and branch to the slow path.
        // Clobbers rcx (t1).
        "js_to_int32" => {
            if insn.operands.len() >= 3 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                let fail = resolve_label(&insn.operands[2], handler);
                w!(out, "    cvttsd2si {dst}, {src}");
                w!(out, "    mov rcx, 0x8000000000000000");
                w!(out, "    cmp {dst}, rcx");
                w!(out, "    je {fail}");
            }
        }

        // divmod quot, rem, dividend, divisor
        // Signed integer divide: quot = dividend / divisor, rem = dividend % divisor.
        "divmod" => {
            if insn.operands.len() == 4 {
                let dividend = resolve_op(&insn.operands[2], handler, program);
                let divisor = resolve_op(&insn.operands[3], handler, program);
                // x86 idiv divides rdx:rax by operand.
                // Result: quotient in rax, remainder in rdx.
                w!(out, "    mov rax, {dividend}");
                w!(out, "    cqo");
                w!(out, "    idiv {divisor}");
                // rax (t0) = quotient, rdx (t2) = remainder -- matches DSL convention
            }
        }

        // fp_floor dst, src - Round toward negative infinity
        "fp_floor" => {
            if insn.operands.len() == 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    roundsd {dst}, {src}, 1");
            }
        }

        // fp_ceil dst, src - Round toward positive infinity
        "fp_ceil" => {
            if insn.operands.len() == 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    roundsd {dst}, {src}, 2");
            }
        }

        // toggle_bit dst, bit - Toggle (flip) a single bit: dst ^= (1 << bit)
        "toggle_bit" => {
            if insn.operands.len() == 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let bit = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    btc {dst}, {bit}");
            }
        }

        // clear_bit dst, bit - Clear a single bit: dst &= ~(1 << bit)
        "clear_bit" => {
            if insn.operands.len() == 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let bit = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    btr {dst}, {bit}");
            }
        }

        // Architecture-neutral FP arithmetic
        "fp_add" | "fp_sub" | "fp_mul" | "fp_div" | "fp_sqrt" => {
            let x86_mnemonic = match m.as_str() {
                "fp_add" => "addsd",
                "fp_sub" => "subsd",
                "fp_mul" => "mulsd",
                "fp_div" => "divsd",
                "fp_sqrt" => "sqrtsd",
                _ => unreachable!(),
            };
            let ops: Vec<String> = insn
                .operands
                .iter()
                .map(|o| resolve_op(o, handler, program))
                .collect();
            w!(out, "    {x86_mnemonic} {}", ops.join(", "));
        }

        // fp_mov dst, src - Move between int and FP registers
        "fp_mov" => {
            let ops: Vec<String> = insn
                .operands
                .iter()
                .map(|o| resolve_op(o, handler, program))
                .collect();
            w!(out, "    movq {}", ops.join(", "));
        }

        // int_to_double fpr, gpr - Convert signed int64 to double
        "int_to_double" => {
            let ops: Vec<String> = insn
                .operands
                .iter()
                .map(|o| resolve_op(o, handler, program))
                .collect();
            w!(out, "    cvtsi2sd {}", ops.join(", "));
        }

        // canonicalize_nan dst_gpr, src_fpr
        // If src is NaN, write CANON_NAN_BITS to dst. Otherwise bitwise-copy src to dst.
        // Clobbers r11 as scratch.
        "canonicalize_nan" => {
            if insn.operands.len() == 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                let canon = program
                    .constants
                    .get("CANON_NAN_BITS")
                    .copied()
                    .expect("CANON_NAN_BITS constant required for canonicalize_nan");
                w!(out, "    movq {dst}, {src}");
                w!(out, "    ucomisd {src}, {src}");
                w!(out, "    movabs r11, {canon}");
                w!(out, "    cmovp {dst}, r11");
            }
        }

        // mul: maps to x86 imul (2-operand: dst *= src, or 3-operand: dst = src * imm)
        "mul" => {
            let ops: Vec<String> = insn
                .operands
                .iter()
                .map(|o| resolve_op(o, handler, program))
                .collect();
            w!(out, "    imul {}", ops.join(", "));
        }

        "exit" => {
            w!(out, "    jmp .Lexit");
        }

        // load64 dst_reg, [base, offset] - Load 64-bit value from memory
        "load64" => {
            if insn.operands.len() >= 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let mem = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    mov {dst}, QWORD PTR {mem}");
            }
        }

        // load32 dst_reg, [base, offset] - Load 32-bit value (zero-extended to 64-bit)
        "load32" => {
            if insn.operands.len() >= 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let dst32 = to_32bit_reg(&dst);
                let mem = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    mov {dst32}, DWORD PTR {mem}");
            }
        }

        // load8 dst_reg, [base, offset] - Load 8-bit value (zero-extended to 64-bit)
        "load8" => {
            if insn.operands.len() >= 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let dst32 = to_32bit_reg(&dst);
                let mem = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    movzx {dst32}, BYTE PTR {mem}");
            }
        }

        // load16 dst_reg, [base, offset] - Load 16-bit value (zero-extended to 64-bit)
        "load16" => {
            if insn.operands.len() >= 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let dst32 = to_32bit_reg(&dst);
                let mem = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    movzx {dst32}, WORD PTR {mem}");
            }
        }

        // load8s dst_reg, [base, offset] - Load 8-bit value (sign-extended to 64-bit)
        "load8s" => {
            if insn.operands.len() >= 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let dst32 = to_32bit_reg(&dst);
                let mem = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    movsx {dst32}, BYTE PTR {mem}");
            }
        }

        // load16s dst_reg, [base, offset] - Load 16-bit value (sign-extended to 64-bit)
        "load16s" => {
            if insn.operands.len() >= 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let dst32 = to_32bit_reg(&dst);
                let mem = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    movsx {dst32}, WORD PTR {mem}");
            }
        }

        // store8 [base, offset], src_reg - Store low 8 bits to memory
        "store8" => {
            if insn.operands.len() >= 2 {
                let mem = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                let src8 = to_8bit_reg(&src);
                w!(out, "    mov BYTE PTR {mem}, {src8}");
            }
        }

        // store16 [base, offset], src_reg - Store low 16 bits to memory
        "store16" => {
            if insn.operands.len() >= 2 {
                let mem = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                let src16 = to_16bit_reg(&src);
                w!(out, "    mov WORD PTR {mem}, {src16}");
            }
        }

        // store32 [base, offset], src_reg - Store low 32 bits to memory
        "store32" => {
            if insn.operands.len() >= 2 {
                let mem = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                let src32 = to_32bit_reg(&src);
                w!(out, "    mov DWORD PTR {mem}, {src32}");
            }
        }

        // store64 [base, offset], src_reg - Store 64-bit value to memory
        "store64" => {
            if insn.operands.len() >= 2 {
                let mem = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    mov QWORD PTR {mem}, {src}");
            }
        }

        // load_operand dst_reg, byte_offset
        "load_operand" => {
            if insn.operands.len() >= 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let offset = resolve_op(&insn.operands[1], handler, program);
                // Load the u32 operand raw value from bytecode
                w!(out, "    mov eax, DWORD PTR [r14 + r13 + {offset}]");
                // Use it as index into values array (scaled by 8)
                w!(out, "    mov {dst}, QWORD PTR [r15 + rax * 8]");
            }
        }

        // store_operand byte_offset, src_reg
        "store_operand" => {
            if insn.operands.len() >= 2 {
                let offset = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                // Load the u32 operand raw value from bytecode.
                // Use r11 as scratch to avoid clobbering src if it's rax.
                w!(out, "    mov r11d, DWORD PTR [r14 + r13 + {offset}]");
                // Store value into values array
                w!(out, "    mov QWORD PTR [r15 + r11 * 8], {src}");
            }
        }

        // load_label dst_reg, byte_offset (loads a Label = u32 address)
        "load_label" => {
            if insn.operands.len() >= 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let dst32 = to_32bit_reg(&dst);
                let offset = resolve_op(&insn.operands[1], handler, program);
                w!(out, "    mov {dst32}, DWORD PTR [r14 + r13 + {offset}]");
            }
        }

        // goto_handler label_reg - set pc and dispatch
        "goto_handler" => {
            if let Some(op) = insn.operands.first() {
                let reg = resolve_op(op, handler, program);
                let reg32 = to_32bit_reg(&reg);
                w!(out, "    mov r13d, {reg32}");
                emit_dispatch(out);
            }
        }

        // mov with large immediate needs movabs on x86_64
        "mov" => {
            if insn.operands.len() == 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                // Check if src is a large immediate that needs movabs
                if let Some(val) = get_immediate_value(&insn.operands[1], program) {
                    let uval = val as u64;
                    if uval > 0x7FFFFFFF && uval < 0xFFFFFFFF80000000 {
                        // Need movabs for 64-bit immediate
                        w!(out, "    movabs {dst}, {val}");
                    } else {
                        w!(out, "    mov {dst}, {src}");
                    }
                } else {
                    w!(out, "    mov {dst}, {src}");
                }
            }
        }

        // movsxd needs 32-bit source register
        "movsxd" => {
            if insn.operands.len() == 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                let src = resolve_op(&insn.operands[1], handler, program);
                let src32 = to_32bit_reg(&src);
                w!(out, "    movsxd {dst}, {src32}");
            }
        }

        // and with 0xFFFFFFFF needs special handling on x86_64
        // (imm32 gets sign-extended to 64 bits, making it a no-op)
        "and" => {
            if insn.operands.len() == 2 {
                let dst = resolve_op(&insn.operands[0], handler, program);
                if let Some(val) = get_immediate_value(&insn.operands[1], program) {
                    if val as u64 == 0xFFFFFFFF {
                        // Use mov to 32-bit register to zero upper bits
                        let dst32 = to_32bit_reg(&dst);
                        w!(out, "    mov {dst32}, {dst32}");
                    } else {
                        let src = resolve_op(&insn.operands[1], handler, program);
                        w!(out, "    and {dst}, {src}");
                    }
                } else {
                    let src = resolve_op(&insn.operands[1], handler, program);
                    w!(out, "    and {dst}, {src}");
                }
            }
        }

        // Shift instructions: x86 variable shifts require count in cl register.
        // If the count is in a register other than rcx, move it there first.
        "shl" | "shr" | "sar" => {
            let dst = resolve_op(&insn.operands[0], handler, program);
            if insn.operands.len() == 2 {
                if get_immediate_value(&insn.operands[1], program).is_some() {
                    let count = resolve_op(&insn.operands[1], handler, program);
                    w!(out, "    {m} {dst}, {count}");
                } else {
                    let count = resolve_op(&insn.operands[1], handler, program);
                    if count != "rcx" {
                        w!(out, "    mov rcx, {count}");
                    }
                    w!(out, "    {m} {dst}, cl");
                }
            }
        }

        // Standard x86 instructions - pass through with register resolution
        "lea" | "add" | "sub" | "neg" | "not" | "or" | "xor" => {
            let ops: Vec<String> = insn
                .operands
                .iter()
                .map(|o| resolve_op(o, handler, program))
                .collect();
            if ops.is_empty() {
                w!(out, "    {m}");
            } else {
                w!(out, "    {m} {}", ops.join(", "));
            }
        }

        // Unconditional jump - resolve local labels
        "jmp" => {
            if let Some(Operand::Label(label)) = insn.operands.first() {
                if label.starts_with('.') {
                    w!(out, "    {m} .Lasm_{}{label}", handler.name);
                } else {
                    w!(out, "    {m} {label}");
                }
            } else if let Some(op) = insn.operands.first() {
                w!(out, "    {m} {}", resolve_op(op, handler, program));
            }
        }

        // Architecture-neutral branch operations.
        // These encode the comparison and branch as a single DSL operation,
        // freeing backends from x86 flag-register semantics.
        "branch_eq" | "branch_ne" | "branch_ge_unsigned"
        | "branch_lt_signed" | "branch_le_signed"
        | "branch_gt_signed" | "branch_ge_signed" => {
            // branch_XX a, b, label  =>  cmp a, b; jXX label
            if insn.operands.len() == 3 {
                let a = resolve_op(&insn.operands[0], handler, program);
                let b = resolve_op(&insn.operands[1], handler, program);
                let label = resolve_label(&insn.operands[2], handler);
                let cc = match m.as_str() {
                    "branch_eq" => "je",
                    "branch_ne" => "jne",
                    "branch_ge_unsigned" => "jae",
                    "branch_lt_signed" => "jl",
                    "branch_le_signed" => "jle",
                    "branch_gt_signed" => "jg",
                    "branch_ge_signed" => "jge",
                    _ => unreachable!(),
                };
                w!(out, "    cmp {a}, {b}");
                w!(out, "    {cc} {label}");
            }
        }

        "branch_zero" | "branch_nonzero" | "branch_negative" | "branch_not_negative" => {
            // branch_zero a, label  =>  test a, a; jz label
            if insn.operands.len() == 2 {
                let a = resolve_op(&insn.operands[0], handler, program);
                let label = resolve_label(&insn.operands[1], handler);
                let cc = match m.as_str() {
                    "branch_zero" => "jz",
                    "branch_nonzero" => "jnz",
                    "branch_negative" => "js",
                    "branch_not_negative" => "jns",
                    _ => unreachable!(),
                };
                w!(out, "    test {a}, {a}");
                w!(out, "    {cc} {label}");
            }
        }

        "branch_bits_set" | "branch_bits_clear" => {
            // branch_bits_set a, mask, label  =>  test a, mask; jnz label
            if insn.operands.len() == 3 {
                let a = resolve_op(&insn.operands[0], handler, program);
                let mask = resolve_op(&insn.operands[1], handler, program);
                let label = resolve_label(&insn.operands[2], handler);
                let cc = match m.as_str() {
                    "branch_bits_set" => "jnz",
                    "branch_bits_clear" => "jz",
                    _ => unreachable!(),
                };
                w!(out, "    test {a}, {mask}");
                w!(out, "    {cc} {label}");
            }
        }

        "branch_bit_set" => {
            // branch_bit_set a, N, label  =>  bt a, N; jc label
            if insn.operands.len() == 3 {
                let a = resolve_op(&insn.operands[0], handler, program);
                let bit = resolve_op(&insn.operands[1], handler, program);
                let label = resolve_label(&insn.operands[2], handler);
                w!(out, "    bt {a}, {bit}");
                w!(out, "    jc {label}");
            }
        }

        // Multi-value equality branch: branch if register equals any of the given values.
        // branch_any_eq reg, val1, val2, ..., label
        // On x86: emits cmp + je for each value.
        "branch_any_eq" => {
            if insn.operands.len() >= 3 {
                let reg = resolve_op(&insn.operands[0], handler, program);
                let label = resolve_label(insn.operands.last().unwrap(), handler);
                for op in &insn.operands[1..insn.operands.len() - 1] {
                    let val = resolve_op(op, handler, program);
                    w!(out, "    cmp {reg}, {val}");
                    w!(out, "    je {label}");
                }
            }
        }

        // Floating-point compare-and-branch operations.
        "branch_fp_unordered" | "branch_fp_equal" | "branch_fp_less"
        | "branch_fp_less_or_equal" | "branch_fp_greater"
        | "branch_fp_greater_or_equal" => {
            if insn.operands.len() == 3 {
                let a = resolve_op(&insn.operands[0], handler, program);
                let b = resolve_op(&insn.operands[1], handler, program);
                let label = resolve_label(&insn.operands[2], handler);
                w!(out, "    ucomisd {a}, {b}");
                if m == "branch_fp_equal" {
                    // ucomisd sets both ZF=1 and PF=1 for unordered (NaN) operands.
                    // A plain `je` would incorrectly branch on NaN since it only
                    // checks ZF. Emit `jp` to skip over the `je` when unordered.
                    let skip = *label_counter;
                    *label_counter += 1;
                    let handler_name = &handler.name;
                    w!(out, "    jp .Lnan_skip_{handler_name}_{skip}");
                    w!(out, "    je {label}");
                    w!(out, ".Lnan_skip_{handler_name}_{skip}:");
                } else {
                    let cc = match m.as_str() {
                        "branch_fp_unordered" => "jp",
                        "branch_fp_less" => "jb",
                        "branch_fp_less_or_equal" => "jbe",
                        "branch_fp_greater" => "ja",
                        "branch_fp_greater_or_equal" => "jae",
                        _ => unreachable!(),
                    };
                    w!(out, "    {cc} {label}");
                }
            }
        }

        _ => {
            panic!("Unknown instruction '{m}' in handler '{}'", handler.name);
        }
    }
}

/// Convert a 64-bit register name to its 8-bit counterpart.
fn to_8bit_reg(reg: &str) -> String {
    match reg {
        "rax" => "al".to_string(),
        "rbx" => "bl".to_string(),
        "rcx" => "cl".to_string(),
        "rdx" => "dl".to_string(),
        "rsi" => "sil".to_string(),
        "rdi" => "dil".to_string(),
        "rsp" => "spl".to_string(),
        "rbp" => "bpl".to_string(),
        "r8" => "r8b".to_string(),
        "r9" => "r9b".to_string(),
        "r10" => "r10b".to_string(),
        "r11" => "r11b".to_string(),
        "r12" => "r12b".to_string(),
        "r13" => "r13b".to_string(),
        "r14" => "r14b".to_string(),
        "r15" => "r15b".to_string(),
        _ => reg.to_string(),
    }
}

/// Convert a 64-bit register name to its 16-bit counterpart.
fn to_16bit_reg(reg: &str) -> String {
    match reg {
        "rax" => "ax".to_string(),
        "rbx" => "bx".to_string(),
        "rcx" => "cx".to_string(),
        "rdx" => "dx".to_string(),
        "rsi" => "si".to_string(),
        "rdi" => "di".to_string(),
        "rsp" => "sp".to_string(),
        "rbp" => "bp".to_string(),
        "r8" => "r8w".to_string(),
        "r9" => "r9w".to_string(),
        "r10" => "r10w".to_string(),
        "r11" => "r11w".to_string(),
        "r12" => "r12w".to_string(),
        "r13" => "r13w".to_string(),
        "r14" => "r14w".to_string(),
        "r15" => "r15w".to_string(),
        _ => reg.to_string(),
    }
}

/// Convert a 64-bit register name to its 32-bit counterpart.
fn to_32bit_reg(reg: &str) -> String {
    match reg {
        "rax" => "eax".to_string(),
        "rbx" => "ebx".to_string(),
        "rcx" => "ecx".to_string(),
        "rdx" => "edx".to_string(),
        "rsi" => "esi".to_string(),
        "rdi" => "edi".to_string(),
        "rsp" => "esp".to_string(),
        "rbp" => "ebp".to_string(),
        "r8" => "r8d".to_string(),
        "r9" => "r9d".to_string(),
        "r10" => "r10d".to_string(),
        "r11" => "r11d".to_string(),
        "r12" => "r12d".to_string(),
        "r13" => "r13d".to_string(),
        "r14" => "r14d".to_string(),
        "r15" => "r15d".to_string(),
        _ => reg.to_string(),
    }
}
