#import <DOM/Event.idl>
#import <Gamepad/Gamepad.idl>

// https://w3c.github.io/gamepad/#dom-gamepadevent
[Exposed=Window]
interface GamepadEvent : Event {
    constructor(DOMString type, GamepadEventInit eventInitDict);
    [SameObject] readonly attribute Gamepad gamepad;
};

// https://w3c.github.io/gamepad/#dom-gamepadeventinit
dictionary GamepadEventInit : EventInit {
    required Gamepad gamepad;
};
