// https://w3c.github.io/webvtt/#enumdef-scrollsetting
enum ScrollSetting { "", "up" };

// https://w3c.github.io/webvtt/#vttregion
[Exposed=Window]
interface VTTRegion {
    constructor();
    attribute DOMString id;
    [NeedsThisObjectRealmForSetter] attribute double width;
    attribute unsigned long lines;
    [NeedsThisObjectRealmForSetter] attribute double regionAnchorX;
    [NeedsThisObjectRealmForSetter] attribute double regionAnchorY;
    [NeedsThisObjectRealmForSetter] attribute double viewportAnchorX;
    [NeedsThisObjectRealmForSetter] attribute double viewportAnchorY;
    attribute ScrollSetting scroll;
};
