// https://streams.spec.whatwg.org/#cqs-class-definition
[Exposed=*]
interface CountQueuingStrategy {
    constructor(QueuingStrategyInit init);

    readonly attribute unrestricted double highWaterMark;
    [NeedsCallerRealmForGetter] readonly attribute Function size;
};
