// https://streams.spec.whatwg.org/#rbs-controller-class-definition
    [Exposed=*]
interface ReadableByteStreamController {
    [NeedsThisObjectRealm] readonly attribute ReadableStreamBYOBRequest? byobRequest;
    readonly attribute unrestricted double? desiredSize;

    [NeedsThisObjectRealm] undefined close();
    undefined error(optional any e);
    [NeedsThisObjectRealm] undefined enqueue(ArrayBufferView chunk);
};
