// https://streams.spec.whatwg.org/#readablestreambyobrequest
[Exposed=*]
interface ReadableStreamBYOBRequest {
    readonly attribute ArrayBufferView? view;

    [NeedsThisObjectRealm] undefined respond([EnforceRange] unsigned long long bytesWritten);
    [NeedsCallerRealm] undefined respondWithNewView(ArrayBufferView view);
};
