// https://streams.spec.whatwg.org/#writablestreamdefaultcontroller
[Exposed=*]
interface WritableStreamDefaultController {
    [DirectGetter] readonly attribute AbortSignal signal;
    undefined error(optional any e);
};
