/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Extracts the interpreter data layout from LibJS's C++ declarations.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::Path;

use super::object_symbols;

enum Directive {
    Section(String),
    Raw(String),
    Constant {
        name: String,
        expression: String,
        hexadecimal: bool,
        query: usize,
    },
    Field {
        name: String,
        declaration: String,
        expression: String,
        modifiers: String,
        force_nonnull: bool,
        query: usize,
    },
}

struct Spec {
    includes: Vec<String>,
    namespaces: Vec<String>,
    prelude: Vec<String>,
    directives: Vec<Directive>,
    query_count: usize,
}

pub(crate) fn generate_probe(spec: &str) -> Result<String, String> {
    parse_spec(spec).map(|spec| synthesize_probe(&spec))
}

pub(crate) fn read_object(spec: &str, objdump_path: &Path, object_path: &Path) -> Result<String, String> {
    let spec = parse_spec(spec)?;
    emit(
        &spec,
        &object_symbols::read_query_values(objdump_path, object_path, spec.query_count)?,
    )
}

fn synthesize_probe(spec: &Spec) -> String {
    let mut output = String::from("// Generated by flapc -- DO NOT EDIT\n\n");
    for include in &spec.includes {
        let _ = writeln!(output, "#include {include}");
    }
    output.push('\n');
    for namespace in &spec.namespaces {
        let _ = writeln!(output, "using namespace {namespace};");
    }
    for line in &spec.prelude {
        let _ = writeln!(output, "{line}");
    }
    output.push_str(
        "\nnamespace flap_probe {\n\
         template<typename> constexpr bool is_gc_ptr = false;\n\
         template<typename T> constexpr bool is_gc_ptr<GC::Ptr<T>> = true;\n\
         template<typename> constexpr bool is_gc_ref = false;\n\
         template<typename T> constexpr bool is_gc_ref<GC::Ref<T>> = true;\n",
    );
    for directive in &spec.directives {
        let (query, name, expression) = match directive {
            Directive::Constant {
                query,
                name,
                expression,
                ..
            }
            | Directive::Field {
                query,
                name,
                expression,
                ..
            } => (query, name, expression),
            Directive::Section(_) | Directive::Raw(_) => continue,
        };
        let _ = writeln!(
            output,
            "constexpr unsigned long long flap_Q{query} = \
             static_cast<unsigned long long>({expression});"
        );
        let symbol_name = symbol_name(*query, name);
        let function_name = cxx_identifier(name);
        let _ = writeln!(
            output,
            "__attribute__((used)) static void flap_emit_Q{query}_{function_name}() {{\n\
                 asm volatile(\".globl {symbol_name}__lo\\n.set {symbol_name}__lo, %c0\\n\" : : \"i\"(static_cast<unsigned>(flap_Q{query} & 0xffffffffULL)));\n\
                 asm volatile(\".globl {symbol_name}__hi\\n.set {symbol_name}__hi, %c0\\n\" : : \"i\"(static_cast<unsigned>((flap_Q{query} >> 32) & 0xffffffffULL)));\n\
             }}"
        );
    }
    output.push_str("}\n");
    output
}

fn symbol_name(query: usize, name: &str) -> String {
    let mut symbol = format!("flap_layout_Q{query}__");
    for character in name.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            symbol.push(character);
        } else {
            symbol.push('_');
        }
    }
    symbol
}

fn cxx_identifier(name: &str) -> String {
    let mut identifier = String::with_capacity(name.len());
    for (index, character) in name.chars().enumerate() {
        if character.is_ascii_alphanumeric() || character == '_' {
            if index == 0 && character.is_ascii_digit() {
                identifier.push('_');
            }
            identifier.push(character);
        } else {
            identifier.push('_');
        }
    }
    identifier
}

fn emit(spec: &Spec, values: &[Option<u64>]) -> Result<String, String> {
    let mut output = String::from("# Generated by flapc from the LibJS headers -- DO NOT EDIT\n");
    let mut emitted = HashMap::new();
    for directive in &spec.directives {
        match directive {
            Directive::Section(title) => {
                let _ = write!(output, "\n# {title}\n");
            }
            Directive::Raw(line) => {
                writeln!(output, "{}", interpolate(line, &emitted)?).unwrap();
            }
            Directive::Constant {
                name,
                hexadecimal,
                query,
                ..
            } => {
                let value = query_value(values, *query, name)?;
                emitted.insert(name.as_str(), value);
                if *hexadecimal {
                    let _ = writeln!(output, "const {name} = 0x{value:X}");
                } else {
                    let _ = writeln!(output, "const {name} = {}", value as i64);
                }
            }
            Directive::Field {
                name,
                declaration,
                modifiers,
                force_nonnull,
                query,
                ..
            } => {
                let packed = query_value(values, *query, name)?;
                let offset = packed / 4;
                emitted.insert(name.as_str(), offset);
                let storage = if *force_nonnull || packed & 1 != 0 {
                    "nonnull"
                } else {
                    "nullable"
                };
                let representation = if packed & 2 != 0 { "cell" } else { "scalar" };
                let _ = writeln!(output, "const {name} = {offset}");
                let _ = writeln!(
                    output,
                    "field {declaration} {name} {storage} {representation}{modifiers}"
                );
            }
        }
    }
    Ok(output)
}

fn query_value(values: &[Option<u64>], query: usize, name: &str) -> Result<u64, String> {
    values
        .get(query)
        .copied()
        .flatten()
        .ok_or_else(|| format!("the layout probe did not emit {name}"))
}

fn interpolate(line: &str, emitted: &HashMap<&str, u64>) -> Result<String, String> {
    let mut output = String::with_capacity(line.len());
    let mut rest = line;
    while let Some(start) = rest.find('{') {
        let end = rest[start..]
            .find('}')
            .ok_or_else(|| format!("unterminated '{{' in raw line: {line}"))?
            + start;
        let name = &rest[start + 1..end];
        let value = emitted
            .get(name)
            .ok_or_else(|| format!("raw line references undefined constant '{name}'"))?;
        let _ = write!(output, "{}{}", &rest[..start], *value as i64);
        rest = &rest[end + 1..];
    }
    output.push_str(rest);
    Ok(output)
}

fn parse_spec(source: &str) -> Result<Spec, String> {
    let mut spec = Spec {
        includes: Vec::new(),
        namespaces: Vec::new(),
        prelude: Vec::new(),
        directives: Vec::new(),
        query_count: 0,
    };
    let mut types = HashMap::new();
    for (index, raw_line) in source.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let error = |message: &str| format!("layout spec line {}: {message}", index + 1);
        let (keyword, rest) = line.split_once(char::is_whitespace).unwrap_or((line, ""));
        let rest = rest.trim();
        match keyword {
            "include" => spec.includes.push(rest.to_string()),
            "namespace" => spec.namespaces.push(rest.to_string()),
            "prelude" => spec.prelude.push(rest.to_string()),
            "type" => {
                let (name, cxx_type) = rest.split_once('=').ok_or_else(|| error("type requires '='"))?;
                if types
                    .insert(name.trim().to_string(), cxx_type.trim().to_string())
                    .is_some()
                {
                    return Err(error("duplicate type alias"));
                }
            }
            "section" => spec.directives.push(Directive::Section(rest.to_string())),
            "raw" => spec.directives.push(Directive::Raw(rest.to_string())),
            "offset" | "size" | "align" | "const" | "hex" => {
                let (name, value) = rest.split_once('=').ok_or_else(|| error("constant requires '='"))?;
                let expression = match keyword {
                    "offset" => {
                        let (owner, member) =
                            split_member(value.trim()).ok_or_else(|| error("offset requires <type>.<member>"))?;
                        format!("__builtin_offsetof({}, {member})", lookup(&types, owner)?)
                    }
                    "size" => format!("sizeof({})", lookup(&types, value.trim())?),
                    "align" => format!("alignof({})", lookup(&types, value.trim())?),
                    _ => value.trim().to_string(),
                };
                spec.directives.push(Directive::Constant {
                    name: name.trim().to_string(),
                    expression,
                    hexadecimal: keyword == "hex",
                    query: spec.query_count,
                });
                spec.query_count += 1;
            }
            "field" => {
                spec.directives
                    .push(parse_field(rest, &types, spec.query_count).map_err(|message| error(&message))?);
                spec.query_count += 1;
            }
            _ => return Err(error(&format!("unknown directive '{keyword}'"))),
        }
    }
    Ok(spec)
}

fn parse_field(rest: &str, types: &HashMap<String, String>, query: usize) -> Result<Directive, String> {
    let (declaration, source) = rest.split_once('=').ok_or_else(|| "field requires '='".to_string())?;
    let mut declaration_words = declaration.split_ascii_whitespace();
    let name = declaration_words.next().ok_or("field requires a name")?;
    let owner = declaration_words.next().ok_or("field requires an owner")?;
    let flap_type = declaration_words.next().ok_or("field requires a type")?;
    if declaration_words.next().is_some() || !owner.contains('.') {
        return Err("field requires a constant name, qualified name, and type".to_string());
    }

    let mut source_words = source.split_ascii_whitespace();
    let (type_name, member) = split_member(source_words.next().ok_or("field requires <type>.<member>")?)
        .ok_or("field requires <type>.<member>")?;
    let cxx_type = lookup(types, type_name)?;
    let mut force_nonnull = false;
    let mut modifiers = String::new();
    while let Some(modifier) = source_words.next() {
        match modifier {
            "nonnull" => force_nonnull = true,
            "pair" => {
                modifiers.push(' ');
                modifiers.push_str(source_words.next().ok_or("pair requires a name")?);
            }
            "pinned" => {
                modifiers.push_str(" pinned ");
                modifiers.push_str(source_words.next().ok_or("pinned requires a base")?);
                modifiers.push(' ');
                modifiers.push_str(source_words.next().ok_or("pinned requires an offset")?);
            }
            "stride" => {
                modifiers.push_str(" stride ");
                modifiers.push_str(source_words.next().ok_or("stride requires a value")?);
            }
            _ => return Err(format!("unknown field modifier '{modifier}'")),
        }
    }
    Ok(Directive::Field {
        name: name.to_string(),
        declaration: format!("{owner} {flap_type}"),
        expression: format!(
            "__builtin_offsetof({cxx_type}, {member}) * 4 + \
             is_gc_ref<decltype({cxx_type}::{member})> + \
             (is_gc_ref<decltype({cxx_type}::{member})> || \
              is_gc_ptr<decltype({cxx_type}::{member})>) * 2"
        ),
        modifiers,
        force_nonnull,
        query,
    })
}

fn split_member(value: &str) -> Option<(&str, &str)> {
    let (owner, member) = value.rsplit_once('.')?;
    (!owner.is_empty() && !member.is_empty()).then_some((owner, member))
}

fn lookup<'a>(types: &'a HashMap<String, String>, name: &str) -> Result<&'a str, String> {
    types
        .get(name)
        .map(String::as_str)
        .ok_or_else(|| format!("unknown type alias '{name}'"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_and_synthesizes_queries() {
        let spec = parse_spec(
            "include <LibJS/Runtime/Object.h>\n\
             namespace JS\n\
             type Object = JS::Object\n\
             field OBJECT_SHAPE Object.shape Shape = Object.m_shape pair state\n\
             size OBJECT_SIZE = Object\n\
             hex OBJECT_TAG = OBJECT_TAG\n",
        )
        .unwrap();
        let probe = synthesize_probe(&spec);
        assert_eq!(spec.query_count, 3);
        assert!(probe.contains("__builtin_offsetof(JS::Object, m_shape) * 4"));
        assert!(probe.contains("sizeof(JS::Object)"));
        assert!(probe.contains("OBJECT_TAG"));
    }

    #[test]
    fn emits_inferred_and_explicit_nonnull_fields() {
        let mut spec = parse_spec(
            "type Object = JS::Object\n\
             field A Object.a Shape = Object.m_a\n\
             field B Object.b Shape = Object.m_b nonnull\n",
        )
        .unwrap();
        spec.directives.insert(1, Directive::Section("Fields".to_string()));
        let output = emit(&spec, &[Some(8), Some(12)]).unwrap();
        assert!(output.contains("field Object.a Shape A nullable scalar"));
        assert!(output.contains("field Object.b Shape B nonnull scalar"));
    }

    #[test]
    fn rejects_unknown_types_and_directives() {
        assert!(matches!(
            parse_spec("size SIZE = Missing"),
            Err(error) if error.contains("unknown type")
        ));
        assert!(matches!(
            parse_spec("wobble thing"),
            Err(error) if error.contains("unknown directive")
        ));
    }

    #[test]
    fn evaluates_using_the_requested_target_abi() {
        let spec = "prelude namespace GC { template<typename> class Ptr; template<typename> class Ref; }\n\
                    prelude struct Probe { void* pointer; long value; char tail; };\n\
                    type Probe = Probe\n\
                    const LONG_SIZE = sizeof(long)\n\
                    offset TAIL_OFFSET = Probe.tail\n\
                    size PROBE_SIZE = Probe\n";
        let evaluate = |target: &str| {
            let probe_path = std::env::temp_dir().join(format!(
                "flap-layout-{}-{}.cpp",
                std::process::id(),
                target.replace('-', "_")
            ));
            let object_path = probe_path.with_extension("o");
            let Some((compiler_path, mut compiler_arguments)) = find_cxx_compiler() else {
                eprintln!("skipping target ABI layout test: clang++/clang-cl not found");
                return None;
            };
            let Some(objdump_path) = find_tool(&["llvm-objdump", "llvm-objdump.exe", "objdump", "objdump.exe"]) else {
                eprintln!("skipping target ABI layout test: objdump not found");
                return None;
            };
            compiler_arguments.extend([
                "-xc++".to_string(),
                "-std=c++23".to_string(),
                format!("--target={target}"),
            ]);
            std::fs::write(&probe_path, generate_probe(spec).unwrap()).unwrap();
            let output = std::process::Command::new(&compiler_path)
                .args(&compiler_arguments)
                .args(["-c", probe_path.to_str().unwrap(), "-o", object_path.to_str().unwrap()])
                .output()
                .unwrap();
            assert!(
                output.status.success(),
                "{} rejected the layout probe:\n{}{}",
                compiler_path.display(),
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            );
            let result = read_object(spec, objdump_path.as_ref(), &object_path);
            let _ = std::fs::remove_file(probe_path);
            let _ = std::fs::remove_file(object_path);
            match result {
                Ok(result) => Some(result),
                // Ignore if `objdump` doesn't know about the test target.
                Err(error) if error.contains("recognized") => {
                    eprintln!(
                        "skipping {target}: {} cannot read its objects:\n{error}",
                        objdump_path.display()
                    );
                    None
                }
                Err(error) => panic!("{error}"),
            }
        };

        let Some(linux) = evaluate("aarch64-unknown-linux-gnu") else {
            return;
        };
        let Some(windows) = evaluate("x86_64-pc-windows-msvc") else {
            return;
        };
        assert!(linux.contains("const LONG_SIZE = 8"));
        assert!(windows.contains("const LONG_SIZE = 4"));
        assert!(linux.contains("const TAIL_OFFSET = 16"));
        assert!(windows.contains("const TAIL_OFFSET = 12"));
        assert!(linux.contains("const PROBE_SIZE = 24"));
        assert!(windows.contains("const PROBE_SIZE = 16"));
    }

    fn find_cxx_compiler() -> Option<(std::path::PathBuf, Vec<String>)> {
        find_tool(&["clang++", "clang++.exe"])
            .map(|path| (path, Vec::new()))
            .or_else(|| {
                find_tool(&["clang-cl", "clang-cl.exe"]).map(|path| (path, vec!["--driver-mode=g++".to_string()]))
            })
    }

    fn find_tool(names: &[&str]) -> Option<std::path::PathBuf> {
        let path = std::env::var_os("PATH")?;
        let directories = std::env::split_paths(&path).collect::<Vec<_>>();
        for name in names {
            for directory in &directories {
                let candidate = directory.join(name);
                if candidate.is_file() {
                    return Some(candidate);
                }
            }
        }
        None
    }
}
