// https://storage.spec.whatwg.org/#storagemanager
[SecureContext, Exposed=(Window,Worker)]
interface StorageManager {
    [FIXME] Promise<boolean> persisted();
    [FIXME, Exposed=Window] Promise<boolean> persist();

    // FIXME: This should also be exposed to Workers
    [Exposed=Window] Promise<StorageEstimate> estimate();
};

// https://storage.spec.whatwg.org/#dictdef-storageestimate
dictionary StorageEstimate {
    unsigned long long usage;
    unsigned long long quota;
};
