// https://html.spec.whatwg.org/multipage/canvas.html#canvasfillrule
enum CanvasFillRule { "nonzero", "evenodd" };

// https://html.spec.whatwg.org/multipage/canvas.html#canvasdrawpath
interface mixin CanvasDrawPath {
    undefined beginPath();
    // FIXME: `Utf16DOMString` should be `CanvasFillRule`
    undefined fill(optional [Utf16FlyString] Utf16DOMString fillRule = "nonzero");
    // FIXME: `Utf16DOMString` should be `CanvasFillRule`
    undefined fill(Path2D path, optional [Utf16FlyString] Utf16DOMString fillRule = "nonzero");
    undefined stroke();
    undefined stroke(Path2D path);

    // FIXME: `Utf16DOMString` should be `CanvasFillRule`
    undefined clip(optional [Utf16FlyString] Utf16DOMString fillRule = "nonzero");
    // FIXME: `Utf16DOMString` should be `CanvasFillRule`
    undefined clip(Path2D path, optional [Utf16FlyString] Utf16DOMString fillRule = "nonzero");

    // FIXME: `Utf16DOMString` should be `CanvasFillRule`
    boolean isPointInPath(unrestricted double x, unrestricted double y, optional [Utf16FlyString] Utf16DOMString fillRule = "nonzero");
    // FIXME: `Utf16DOMString` should be `CanvasFillRule`
    boolean isPointInPath(Path2D path, unrestricted double x, unrestricted double y, optional [Utf16FlyString] Utf16DOMString fillRule = "nonzero");
    [FIXME] boolean isPointInStroke(unrestricted double x, unrestricted double y);
    [FIXME] boolean isPointInStroke(Path2D path, unrestricted double x, unrestricted double y);
};
