#import <DOM/Event.idl>
#import <WebXR/XRSession.idl>

// https://immersive-web.github.io/webxr/#xrsessionevent-interface
[SecureContext, Exposed=Window]
interface XRSessionEvent : Event {
    constructor(DOMString type, XRSessionEventInit eventInitDict);
    [SameObject] readonly attribute XRSession session;
};

dictionary XRSessionEventInit : EventInit {
    required XRSession session;
};
