[Experimental, SecureContext, Exposed=Window] interface XRSystem : EventTarget {
    // Methods
    Promise<boolean> isSessionSupported(XRSessionMode mode);
    [NewObject] Promise<XRSession> requestSession(XRSessionMode mode, optional XRSessionInit options = {});

    // Events
    [FIXME] attribute EventHandler ondevicechange;
};

[Experimental] enum XRSessionMode {
    "inline",
    "immersive-vr",
    "immersive-ar"
};

[Experimental] dictionary XRSessionInit {
    sequence<DOMString> requiredFeatures;
    sequence<DOMString> optionalFeatures;
};
