#import <DOM/EventHandler.idl>
#import <MediaSourceExtensions/SourceBuffer.idl>

// https://w3c.github.io/media-source/#dom-sourcebufferlist
[Exposed=(Window,DedicatedWorker)]
interface SourceBufferList : EventTarget {
    readonly attribute unsigned long length;

    attribute EventHandler onaddsourcebuffer;
    attribute EventHandler onremovesourcebuffer;

    getter SourceBuffer (unsigned long index);
};
