// https://html.spec.whatwg.org/multipage/custom-elements.html#customelementregistry
[Exposed=Window]
interface CustomElementRegistry {
    constructor();

    [CEReactions] undefined define([Utf16FlyString] Utf16DOMString name, CustomElementConstructor constructor, optional ElementDefinitionOptions options = {});
    (CustomElementConstructor or undefined) get([Utf16FlyString] Utf16DOMString name);
    Utf16DOMString? getName(CustomElementConstructor constructor);
    Promise<CustomElementConstructor> whenDefined([Utf16FlyString] Utf16DOMString name);
    [CEReactions] undefined upgrade(Node root);
    [CEReactions, ImplementedAs=initialize_for_bindings] undefined initialize(Node root);
};

callback CustomElementConstructor = HTMLElement ();

dictionary ElementDefinitionOptions {
    [Utf16FlyString] Utf16DOMString extends;
};
