[tool.ruff]
line-length = 120

[tool.ruff.lint]
# On top of the defaults (`E4`, E7`, `E9`, and `F`), enable flake8-bugbear (`B`) and isort (`i`).
# https://docs.astral.sh/ruff/rules/
select = ["E4", "E7", "E9", "F", "B", "I"]

[tool.ruff.lint.isort]
force-single-line = true
lines-between-types = 1
