/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Bytecode instruction types generated from Bytecode.def.
//!
//! The `OpCode` enum, `Instruction` enum, and all encoding/visiting methods
//! are generated by build.rs from Bytecode.def. This is the single source
//! of truth for instruction definitions.

include!(concat!(env!("OUT_DIR"), "/instruction_generated.rs"));
