#import <IndexedDB/IDBRequest.idl>

[Exposed=(Window,Worker)]
interface IDBCursor {
    readonly attribute (IDBObjectStore or IDBIndex) source;
    readonly attribute IDBCursorDirection direction;
    readonly attribute any key;
    [FIXME] readonly attribute any primaryKey;
    [SameObject] readonly attribute IDBRequest request;
    [FIXME] undefined advance([EnforceRange] unsigned long count);
    undefined continue(optional any key);
    [FIXME] undefined continuePrimaryKey(any key, any primaryKey);
    [FIXME, NewObject] IDBRequest update(any value);
    [FIXME, NewObject] IDBRequest delete();
};

enum IDBCursorDirection {
    "next",
    "nextunique",
    "prev",
    "prevunique"
};
