#import <IndexedDB/IDBCursor.idl>

[Exposed=(Window,Worker)]
interface IDBIndex {
    [FIXME] attribute DOMString name;
    [FIXME, SameObject] readonly attribute IDBObjectStore objectStore;
    [FIXME] readonly attribute any keyPath;
    [FIXME] readonly attribute boolean multiEntry;
    [FIXME] readonly attribute boolean unique;
    [FIXME, NewObject] IDBRequest get(any query);
    [FIXME, NewObject] IDBRequest getKey(any query);
    [FIXME, NewObject] IDBRequest getAll(optional any query, optional [EnforceRange] unsigned long count);
    [FIXME, NewObject] IDBRequest getAllKeys(optional any query, optional [EnforceRange] unsigned long count);
    [FIXME, NewObject] IDBRequest count(optional any query);
    [FIXME, NewObject] IDBRequest openCursor(optional any query, optional IDBCursorDirection direction = "next");
    [FIXME, NewObject] IDBRequest openKeyCursor(optional any query, optional IDBCursorDirection direction = "next");
};
