#import <DOM/EventTarget.idl>
#import <IndexedDB/IDBDatabase.idl>
#import <IndexedDB/IDBObjectStore.idl>

[Exposed=(Window,Worker)]
interface IDBTransaction : EventTarget {
    [FIXME] readonly attribute DOMStringList objectStoreNames;
    readonly attribute IDBTransactionMode mode;
    readonly attribute IDBTransactionDurability durability;
    [FIXME, SameObject] readonly attribute IDBDatabase db;
    readonly attribute DOMException? error;
    [FIXME] IDBObjectStore objectStore(DOMString name);
    [FIXME] undefined commit();
    [FIXME] undefined abort();
    
    attribute EventHandler onabort;
    attribute EventHandler oncomplete;
    attribute EventHandler onerror;
};

enum IDBTransactionMode {
    "readonly",
    "readwrite",
    "versionchange"
};
