// Rather than creating a list of all languages supported by ICU (of which there are on the order of a thousand), we
// create a list of languages that are supported by both Chrome and Firefox. We can extend this list as needed.
//
// https://github.com/chromium/chromium/blob/main/ui/base/l10n/l10n_util.cc (see kAcceptLanguageList)
// https://github.com/mozilla/gecko-dev/blob/master/intl/locale/language.properties
window.languages = (() => {
    const display = new Intl.DisplayNames([], { type: "language", languageDisplay: "standard" });

    const language = languageID => {
        return {
            language: languageID,
            displayName: display.of(languageID),
        };
    };

    const languages = [
        language("af"),
        language("ak"),
        language("am"),
        language("ar"),
        language("as"),
        language("ast"),
        language("az"),
        language("be"),
        language("bg"),
        language("bm"),
        language("bn"),
        language("br"),
        language("bs"),
        language("ca"),
        language("cs"),
        language("cy"),
        language("da"),
        language("de"),
        language("de-AT"),
        language("de-CH"),
        language("de-DE"),
        language("de-LI"),
        language("ee"),
        language("el"),
        language("en"),
        language("en-AU"),
        language("en-CA"),
        language("en-GB"),
        language("en-IE"),
        language("en-NZ"),
        language("en-US"),
        language("en-ZA"),
        language("eo"),
        language("es"),
        language("es-AR"),
        language("es-CL"),
        language("es-CO"),
        language("es-CR"),
        language("es-ES"),
        language("es-HN"),
        language("es-MX"),
        language("es-PE"),
        language("es-UY"),
        language("es-VE"),
        language("et"),
        language("eu"),
        language("fa"),
        language("fi"),
        language("fo"),
        language("fr"),
        language("fr-CA"),
        language("fr-CH"),
        language("fr-FR"),
        language("fy"),
        language("ga"),
        language("gd"),
        language("gl"),
        language("gu"),
        language("ha"),
        language("haw"),
        language("he"),
        language("hi"),
        language("hr"),
        language("hu"),
        language("hy"),
        language("ia"),
        language("id"),
        language("ig"),
        language("is"),
        language("it"),
        language("it-CH"),
        language("ja"),
        language("jv"),
        language("ka"),
        language("kk"),
        language("km"),
        language("kn"),
        language("ko"),
        language("kok"),
        language("ku"),
        language("ky"),
        language("lb"),
        language("lg"),
        language("ln"),
        language("lo"),
        language("lt"),
        language("lv"),
        language("mai"),
        language("mg"),
        language("mi"),
        language("mk"),
        language("ml"),
        language("mn"),
        language("mr"),
        language("ms"),
        language("mt"),
        language("my"),
        language("nb"),
        language("ne"),
        language("nl"),
        language("nn"),
        language("no"),
        language("nso"),
        language("oc"),
        language("om"),
        language("or"),
        language("pa"),
        language("pl"),
        language("ps"),
        language("pt"),
        language("pt-BR"),
        language("pt-PT"),
        language("qu"),
        language("rm"),
        language("ro"),
        language("ru"),
        language("rw"),
        language("sa"),
        language("sd"),
        language("si"),
        language("sk"),
        language("sl"),
        language("so"),
        language("sq"),
        language("sr"),
        language("st"),
        language("su"),
        language("sv"),
        language("sw"),
        language("ta"),
        language("te"),
        language("tg"),
        language("th"),
        language("ti"),
        language("tk"),
        language("tn"),
        language("to"),
        language("tr"),
        language("tt"),
        language("ug"),
        language("uk"),
        language("ur"),
        language("uz"),
        language("vi"),
        language("wo"),
        language("xh"),
        language("yi"),
        language("yo"),
        language("zh"),
        language("zh-CN"),
        language("zh-HK"),
        language("zh-TW"),
        language("zu"),
    ];

    languages.sort((lhs, rhs) => {
        return lhs.displayName.localeCompare(rhs.displayName);
    });

    return languages;
})();
