// https://w3c.github.io/trusted-types/dist/spec/#trustedtypepolicyfactory
[Exposed=(Window,Worker)]
interface TrustedTypePolicyFactory {
    [NeedsCallerRealm]
    TrustedTypePolicy createPolicy(
        DOMString policyName, optional TrustedTypePolicyOptions policyOptions = {});
    boolean isHTML(any value);
    boolean isScript(any value);
    boolean isScriptURL(any value);
    readonly attribute TrustedHTML emptyHTML;
    readonly attribute TrustedScript emptyScript;
    DOMString? getAttributeType(
        [FlyString] DOMString tagName,
        [FlyString] DOMString attribute,
        optional [FlyString] DOMString? elementNs = "",
        optional [FlyString] DOMString? attrNs = "");
    DOMString? getPropertyType(
        [FlyString] DOMString tagName,
        [FlyString] DOMString property,
        optional [FlyString] DOMString? elementNs = "");
    [DirectGetter] readonly attribute TrustedTypePolicy? defaultPolicy;
};
