#import <TrustedTypes/TrustedHTML.idl>
#import <TrustedTypes/TrustedScript.idl>
#import <TrustedTypes/TrustedScriptURL.idl>

// https://w3c.github.io/trusted-types/dist/spec/#trusted-type-policy
[Exposed=(Window,Worker)]
interface TrustedTypePolicy {
    readonly attribute DOMString name;
    TrustedHTML createHTML(DOMString input, any... arguments);
    TrustedScript createScript(DOMString input, any... arguments);
    TrustedScriptURL createScriptURL(DOMString input, any... arguments);
};

// https://w3c.github.io/trusted-types/dist/spec/#trusted-type-policy-options
dictionary TrustedTypePolicyOptions {
    CreateHTMLCallback createHTML;
    CreateScriptCallback createScript;
    CreateScriptURLCallback createScriptURL;
};
callback CreateHTMLCallback = DOMString? (DOMString input, any... arguments);
callback CreateScriptCallback = DOMString? (DOMString input, any... arguments);
callback CreateScriptURLCallback = USVString? (DOMString input, any... arguments);
