#!/usr/bin/env python3
#
# Copyright (c) 2026-present, the Ladybird developers.
#
# SPDX-License-Identifier: BSD-2-Clause

import argparse
import json
import re
import shlex
import subprocess

from pathlib import Path

HELPERS = ("WebContent", "WebWorker", "RequestServer", "ImageDecoder", "Compositor", "WasmCompiler")


def git_revision(source):
    try:
        revision = subprocess.check_output(
            ["git", "-C", str(source), "rev-parse", "--verify", "HEAD"], stderr=subprocess.DEVNULL, text=True
        ).strip()
        if not re.fullmatch(r"[0-9a-f]{40}|[0-9a-f]{64}", revision):
            return "unknown", "unknown"
        result = subprocess.run(
            ["git", "-C", str(source), "diff-index", "--quiet", "HEAD", "--"],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return revision, {0: "clean", 1: "modified"}.get(result.returncode, "unknown")
    except (OSError, subprocess.CalledProcessError):
        return "unknown", "unknown"


def compiler_flags(command):
    # Never copy include/output paths, response files, arbitrary string defines,
    # or plugin arguments. Keep code-generation flags and numeric build defines.
    flags = []
    arguments = iter(shlex.split(command))
    for argument in arguments:
        if argument in (
            "-I",
            "-isystem",
            "-iquote",
            "-include",
            "-isysroot",
            "-o",
            "-MF",
            "-MT",
            "-Xclang",
            "-Xlinker",
        ):
            next(arguments, None)
            continue
        if argument in ("-arch", "-target"):
            value = next(arguments, "")
            if re.fullmatch(r"[a-zA-Z0-9_.-]+", value):
                flags.extend((argument, value))
            continue
        if (
            re.fullmatch(r"-D[A-Z][A-Z0-9_]*(=[0-9]+)?", argument)
            or re.fullmatch(r"-(O[0-3sgz]|g[0-3]?|ggnu-pubnames|std=[a-z+0-9]+|[fWm][a-zA-Z0-9-]+)", argument)
            or re.fullmatch(r"-[fm][a-zA-Z0-9-]+=(native|hidden|default|off|on|fast|zero|pattern|[0-9.]+)", argument)
            or re.fullmatch(r"-fsanitize=[a-z,-]+", argument)
        ):
            flags.append(argument)
    return " ".join(flags) or "unavailable"


def build_options(cache):
    options = []
    for line in cache.splitlines():
        match = re.fullmatch(r"((?:ENABLE_|USE_|BUILD_|LADYBIRD_)[A-Z0-9_]+):BOOL=(ON|OFF|TRUE|FALSE|0|1)", line)
        if match:
            options.append(f"{match[1]}={match[2]}")
    return "; ".join(sorted(options)) or "unavailable"


def generate(source, build, compiler):
    revision, state = git_revision(source)
    options = build_options((build / "CMakeCache.txt").read_text())
    commands_path = build / "compile_commands.json"
    commands = json.loads(commands_path.read_text()) if commands_path.exists() else []
    common = (
        f"Git commit: {revision}\nTracked source state: {state}\nC++ compiler: {compiler}\nBuild options: {options}\n"
    )
    result = "// Generated by Meta/generate-build-information.py.\n#pragma once\n\n#include <AK/StringView.h>\n#include <LibWebView/ProcessType.h>\n\nnamespace WebView::BuildInformation {\n\ninline StringView for_process(ProcessType type)\n{\n    switch (type) {\n"
    for helper in HELPERS:
        entry = next(
            (entry for entry in commands if Path(entry["file"]) == source / "Services" / helper / "main.cpp"), None
        )
        flags = compiler_flags(entry["command"]) if entry else "unavailable"
        sdk = re.search(r"/MacOSX([0-9.]+)\.sdk", entry["command"]) if entry else None
        text = common
        if sdk:
            text += f"macOS SDK: {sdk[1]}\n"
        text += f"C++ flags ({helper} main; paths and string defines omitted): {flags}\n"
        result += f"    case ProcessType::{helper}:\n        return {json.dumps(text)}sv;\n"
    result += '    default:\n        return ""sv;\n    }\n}\n\n}\n'
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("build", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("compiler")
    args = parser.parse_args()
    if not re.fullmatch(r"[a-zA-Z0-9_. +()-]+", args.compiler):
        raise ValueError("Invalid compiler identity")
    contents = generate(args.source.resolve(), args.build.resolve(), args.compiler)
    if not args.output.exists() or args.output.read_text() != contents:
        args.output.write_text(contents)


if __name__ == "__main__":
    main()
