#import <XPath/XPathResult.idl>

// https://dom.spec.whatwg.org/#interface-xpathexpression
[Exposed=Window]
interface XPathExpression {
  // XPathResult.ANY_TYPE = 0
    XPathResult evaluate(Node contextNode, optional unsigned short type = 0, optional XPathResult? result = null);
};

