// https://svgwg.org/svg2-draft/types.html#InterfaceSVGAnimatedString
[Exposed=Window]
interface SVGAnimatedString {
    attribute Utf16DOMString baseVal;
    [ImplementedAs=base_val] readonly attribute Utf16DOMString animVal;
};
