// https://w3c.github.io/svgwg/svg2-draft/types.html#InterfaceSVGAnimatedNumberList
[Exposed=Window]
interface SVGAnimatedNumberList {
    [DirectGetter, SameObject] readonly attribute SVGNumberList baseVal;
    [DirectGetter=base_val, SameObject] readonly attribute SVGNumberList animVal;
};
