// https://svgwg.org/svg2-draft/types.html#InterfaceSVGAnimatedLengthList
[Exposed=Window]
interface SVGAnimatedLengthList {
    [DirectGetter, SameObject] readonly attribute SVGLengthList baseVal;
    [DirectGetter=base_val, SameObject] readonly attribute SVGLengthList animVal;
};
