#import <SVG/SVGLengthList.idl>

// https://svgwg.org/svg2-draft/types.html#InterfaceSVGAnimatedLengthList
[Exposed=Window]
interface SVGAnimatedLengthList {
    [SameObject] readonly attribute SVGLengthList baseVal;
    [SameObject] readonly attribute SVGLengthList animVal;
};
