// https://svgwg.org/svg2-draft/single-page.html#coords-InterfaceSVGAnimatedTransformList
[Exposed=Window]
interface SVGAnimatedTransformList {
    [DirectGetter, SameObject] readonly attribute SVGTransformList baseVal;
    [DirectGetter, SameObject] readonly attribute SVGTransformList animVal;
};
