// https://w3c.github.io/svgwg/svg2-draft/types.html#InterfaceSVGAnimatedNumberList
[Exposed=Window]
interface SVGAnimatedNumberList {
    [SameObject] readonly attribute SVGNumberList baseVal;
    [SameObject] readonly attribute SVGNumberList animVal;
};
