#import <SVG/SVGAnimatedEnumeration.idl>
#import <SVG/SVGAnimatedString.idl>
#import <SVG/SVGFilterPrimitiveStandardAttributes.idl>

// https://www.w3.org/TR/filter-effects-1/#InterfaceSVGFECompositeElement
[Exposed=Window]
interface SVGFECompositeElement : SVGElement {
    // Composite Operators
    const unsigned short SVG_FECOMPOSITE_OPERATOR_UNKNOWN = 0;
    const unsigned short SVG_FECOMPOSITE_OPERATOR_OVER = 1;
    const unsigned short SVG_FECOMPOSITE_OPERATOR_IN = 2;
    const unsigned short SVG_FECOMPOSITE_OPERATOR_OUT = 3;
    const unsigned short SVG_FECOMPOSITE_OPERATOR_ATOP = 4;
    const unsigned short SVG_FECOMPOSITE_OPERATOR_XOR = 5;
    const unsigned short SVG_FECOMPOSITE_OPERATOR_ARITHMETIC = 6;

    readonly attribute SVGAnimatedString in1;
    readonly attribute SVGAnimatedString in2;
    [ImplementedAs=operator_for_bindings] readonly attribute SVGAnimatedEnumeration operator;
    readonly attribute SVGAnimatedNumber k2;
    readonly attribute SVGAnimatedNumber k3;
    readonly attribute SVGAnimatedNumber k1;
    readonly attribute SVGAnimatedNumber k4;
};

SVGFECompositeElement includes SVGFilterPrimitiveStandardAttributes;
