#import <SVG/SVGComponentTransferFunctionElement.idl>

// https://www.w3.org/TR/filter-effects-1/#InterfaceSVGFEFuncRElement
[Exposed=Window]
interface SVGFEFuncRElement : SVGComponentTransferFunctionElement {
};
