#import <SVG/SVGComponentTransferFunctionElement.idl>

// https://www.w3.org/TR/filter-effects-1/#InterfaceSVGFEFuncAElement
[Exposed=Window]
interface SVGFEFuncAElement : SVGComponentTransferFunctionElement {
};
