// https://w3c.github.io/svgwg/svg2-draft/types.html#InterfaceSVGNumberList
[Exposed=Window]
interface SVGNumberList {

    readonly attribute unsigned long length;
    readonly attribute unsigned long numberOfItems;

    // AD-HOC: 'undefined' instead of 'void'
    [NeedsThisObjectRealm] undefined clear();
    [NeedsCallerRealm] SVGNumber initialize(SVGNumber newItem);
    [NeedsCallerRealm] getter SVGNumber getItem(unsigned long index);
    [NeedsCallerRealm] SVGNumber insertItemBefore(SVGNumber newItem, unsigned long index);
    [NeedsCallerRealm] SVGNumber replaceItem(SVGNumber newItem, unsigned long index);
    [NeedsCallerRealm] SVGNumber removeItem(unsigned long index);
    [NeedsCallerRealm] SVGNumber appendItem(SVGNumber newItem);
    setter void (unsigned long index, SVGNumber newItem);
};
