#import <SVG/SVGElement.idl>
#import <SVG/SVGFitToViewBox.idl>
#import <SVG/SVGURIReference.idl>

// https://svgwg.org/svg2-draft/pservers.html#InterfaceSVGPatternElement
[Exposed=Window]
interface SVGPatternElement : SVGElement {
    [SameObject] readonly attribute SVGAnimatedEnumeration patternUnits;
    [SameObject] readonly attribute SVGAnimatedEnumeration patternContentUnits;
    [SameObject] readonly attribute SVGAnimatedTransformList patternTransform;
    [SameObject] readonly attribute SVGAnimatedLength x;
    [SameObject] readonly attribute SVGAnimatedLength y;
    [SameObject] readonly attribute SVGAnimatedLength width;
    [SameObject] readonly attribute SVGAnimatedLength height;
};

SVGPatternElement includes SVGFitToViewBox;
SVGPatternElement includes SVGURIReference;
