// https://svgwg.org/svg2-draft/single-page.html#styling-InterfaceSVGStyleElement
[Exposed=Window]
interface SVGStyleElement : SVGElement {
    [Reflect] attribute Utf16DOMString media;
    [Reflect] attribute Utf16DOMString title;
    
    // obsolete members
    [Reflect] attribute Utf16DOMString type;
};

SVGStyleElement includes LinkStyle;
