// https://svgwg.org/svg2-draft/single-page.html#coords-InterfaceSVGTransformList
[Exposed=Window]
interface SVGTransformList {
    readonly attribute unsigned long length;
    readonly attribute unsigned long numberOfItems;

    [NeedsThisObjectRealm] undefined clear();
    [NeedsCallerRealm] SVGTransform initialize(SVGTransform newItem);
    [NeedsCallerRealm] getter SVGTransform getItem(unsigned long index);
    [NeedsCallerRealm] SVGTransform insertItemBefore(SVGTransform newItem, unsigned long index);
    [NeedsCallerRealm] SVGTransform replaceItem(SVGTransform newItem, unsigned long index);
    [NeedsCallerRealm] SVGTransform removeItem(unsigned long index);
    [NeedsCallerRealm] SVGTransform appendItem(SVGTransform newItem);
    setter undefined (unsigned long index, SVGTransform newItem);

  // Additional methods not common to other list interfaces.
    [FIXME] SVGTransform createSVGTransformFromMatrix(optional DOMMatrix2DInit matrix = {});
    [FIXME] SVGTransform? consolidate();
};
