#import <SVG/SVGGraphicsElement.idl>
#import <SVG/SVGFitToViewBox.idl>

// https://svgwg.org/svg2-draft/linking.html#InterfaceSVGViewElement
[Exposed=Window]
interface SVGViewElement : SVGElement {};

SVGViewElement includes SVGFitToViewBox;
