// https://url.spec.whatwg.org/#urlsearchparams
[Exposed=*]
interface URLSearchParams {

    constructor(optional (sequence<sequence<Utf16USVString>> or record<Utf16USVString, Utf16USVString> or Utf16USVString) init = "");

    readonly attribute unsigned long size;

    undefined append(Utf16USVString name, Utf16USVString value);
    undefined delete(Utf16USVString name, optional Utf16USVString value);
    Utf16USVString? get(Utf16USVString name);
    sequence<Utf16USVString> getAll(Utf16USVString name);
    boolean has(Utf16USVString name, optional Utf16USVString value);
    undefined set(Utf16USVString name, Utf16USVString value);

    undefined sort();

    iterable<Utf16USVString, Utf16USVString>;
    stringifier;

};
