include_guard()

if (NOT ANDROID)
find_package(PkgConfig REQUIRED)
pkg_check_modules(AVCODEC REQUIRED IMPORTED_TARGET libavcodec)
pkg_check_modules(AVFORMAT REQUIRED IMPORTED_TARGET libavformat)
pkg_check_modules(AVUTIL REQUIRED IMPORTED_TARGET libavutil)
pkg_check_modules(LIBSWRESAMPLE REQUIRED IMPORTED_TARGET libswresample)
else()
    find_package(FFMPEG REQUIRED)

    if (TARGET PkgConfig::openh264)
        get_target_property(openh264_link_libraries PkgConfig::openh264 INTERFACE_LINK_LIBRARIES)
        if (openh264_link_libraries)
            list(FILTER openh264_link_libraries EXCLUDE REGEX "/toolchains/llvm/prebuilt/.*/lib/libc\\+\\+\\.so$")
            set_target_properties(PkgConfig::openh264 PROPERTIES INTERFACE_LINK_LIBRARIES "${openh264_link_libraries}")
        endif()
    endif()
endif()
