execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${LADYBIRD_SOURCE_DIR}" rev-parse --git-path HEAD
    OUTPUT_VARIABLE LADYBIRD_BUILD_HEAD
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
get_filename_component(LADYBIRD_BUILD_HEAD "${LADYBIRD_BUILD_HEAD}" ABSOLUTE BASE_DIR "${LADYBIRD_SOURCE_DIR}")

execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${LADYBIRD_SOURCE_DIR}" rev-parse --git-path logs/HEAD
    OUTPUT_VARIABLE LADYBIRD_BUILD_HEAD_LOG
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
get_filename_component(LADYBIRD_BUILD_HEAD_LOG "${LADYBIRD_BUILD_HEAD_LOG}" ABSOLUTE BASE_DIR "${LADYBIRD_SOURCE_DIR}")
