include_guard()

if (NOT APPLE)
    find_package(VulkanHeaders CONFIG QUIET)
    find_package(Vulkan QUIET)
    if (VulkanHeaders_FOUND AND Vulkan_FOUND)
        set(HAS_VULKAN ON CACHE BOOL "" FORCE)
        add_cxx_compile_definitions(USE_VULKAN=1)
        find_package(VulkanUtilityLibraries)
        if (VulkanUtilityLibraries_FOUND)
            add_cxx_compile_definitions(USE_VULKAN_UTILS=1)
        endif()
    endif()
endif()
