include_guard()

if (NOT APPLE)
    find_package(VulkanHeaders CONFIG QUIET)
    find_package(Vulkan QUIET)
    if (VulkanHeaders_FOUND AND Vulkan_FOUND)
        option(WITH_VULKAN "" ON)
    else()
        option(WITH_VULKAN "" OFF)
    endif()
    if (WITH_VULKAN)
        set(HAS_VULKAN ON CACHE BOOL "" FORCE)
        add_cxx_compile_definitions(USE_VULKAN=1)
    endif()
endif()
