// https://fullscreen.spec.whatwg.org/#ref-for-documentorshadowroot
partial interface mixin DocumentOrShadowRoot {
    [LegacyLenientSetter, ImplementedAs=retargeted_fullscreen_element] readonly attribute Element? fullscreenElement;
};
