// https://fullscreen.spec.whatwg.org/#ref-for-element
partial interface Element {
    [CreatesPromise, NeedsThisObjectRealm] Promise<undefined> requestFullscreen();

    attribute EventHandler onfullscreenchange;
    attribute EventHandler onfullscreenerror;
};
