/*
 * Copyright (c) 2021, Tim Flynn <trflynn89@serenityos.org>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <AK/HashMap.h>
#include <LibUnicode/CurrencyCode.h>

namespace Unicode {

static auto const& ensure_currency_codes()
{
    // https://www.iso.org/iso-4217-currency-codes.html
    // https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/amendments/lists/list_one.xml
    static HashMap<StringView, CurrencyCode> currency_codes {
        { "AED"_sv, { 2 } },
        { "AFN"_sv, { 2 } },
        { "ALL"_sv, { 2 } },
        { "AMD"_sv, { 2 } },
        { "ANG"_sv, { 2 } },
        { "AOA"_sv, { 2 } },
        { "ARS"_sv, { 2 } },
        { "AUD"_sv, { 2 } },
        { "AWG"_sv, { 2 } },
        { "AZN"_sv, { 2 } },
        { "BAM"_sv, { 2 } },
        { "BBD"_sv, { 2 } },
        { "BDT"_sv, { 2 } },
        { "BGN"_sv, { 2 } },
        { "BHD"_sv, { 3 } },
        { "BIF"_sv, { 0 } },
        { "BMD"_sv, { 2 } },
        { "BND"_sv, { 2 } },
        { "BOB"_sv, { 2 } },
        { "BOV"_sv, { 2 } },
        { "BRL"_sv, { 2 } },
        { "BSD"_sv, { 2 } },
        { "BTN"_sv, { 2 } },
        { "BWP"_sv, { 2 } },
        { "BYN"_sv, { 2 } },
        { "BZD"_sv, { 2 } },
        { "CAD"_sv, { 2 } },
        { "CDF"_sv, { 2 } },
        { "CHE"_sv, { 2 } },
        { "CHF"_sv, { 2 } },
        { "CHW"_sv, { 2 } },
        { "CLF"_sv, { 4 } },
        { "CLP"_sv, { 0 } },
        { "CNY"_sv, { 2 } },
        { "COP"_sv, { 2 } },
        { "COU"_sv, { 2 } },
        { "CRC"_sv, { 2 } },
        { "CUC"_sv, { 2 } },
        { "CUP"_sv, { 2 } },
        { "CVE"_sv, { 2 } },
        { "CZK"_sv, { 2 } },
        { "DJF"_sv, { 0 } },
        { "DKK"_sv, { 2 } },
        { "DOP"_sv, { 2 } },
        { "DZD"_sv, { 2 } },
        { "EGP"_sv, { 2 } },
        { "ERN"_sv, { 2 } },
        { "ETB"_sv, { 2 } },
        { "EUR"_sv, { 2 } },
        { "FJD"_sv, { 2 } },
        { "FKP"_sv, { 2 } },
        { "GBP"_sv, { 2 } },
        { "GEL"_sv, { 2 } },
        { "GHS"_sv, { 2 } },
        { "GIP"_sv, { 2 } },
        { "GMD"_sv, { 2 } },
        { "GNF"_sv, { 0 } },
        { "GTQ"_sv, { 2 } },
        { "GYD"_sv, { 2 } },
        { "HKD"_sv, { 2 } },
        { "HNL"_sv, { 2 } },
        { "HRK"_sv, { 2 } },
        { "HTG"_sv, { 2 } },
        { "HUF"_sv, { 2 } },
        { "IDR"_sv, { 2 } },
        { "ILS"_sv, { 2 } },
        { "INR"_sv, { 2 } },
        { "IQD"_sv, { 3 } },
        { "IRR"_sv, { 2 } },
        { "ISK"_sv, { 0 } },
        { "JMD"_sv, { 2 } },
        { "JOD"_sv, { 3 } },
        { "JPY"_sv, { 0 } },
        { "KES"_sv, { 2 } },
        { "KGS"_sv, { 2 } },
        { "KHR"_sv, { 2 } },
        { "KMF"_sv, { 0 } },
        { "KPW"_sv, { 2 } },
        { "KRW"_sv, { 0 } },
        { "KWD"_sv, { 3 } },
        { "KYD"_sv, { 2 } },
        { "KZT"_sv, { 2 } },
        { "LAK"_sv, { 2 } },
        { "LBP"_sv, { 2 } },
        { "LKR"_sv, { 2 } },
        { "LRD"_sv, { 2 } },
        { "LSL"_sv, { 2 } },
        { "LYD"_sv, { 3 } },
        { "MAD"_sv, { 2 } },
        { "MDL"_sv, { 2 } },
        { "MGA"_sv, { 2 } },
        { "MKD"_sv, { 2 } },
        { "MMK"_sv, { 2 } },
        { "MNT"_sv, { 2 } },
        { "MOP"_sv, { 2 } },
        { "MRU"_sv, { 2 } },
        { "MUR"_sv, { 2 } },
        { "MVR"_sv, { 2 } },
        { "MWK"_sv, { 2 } },
        { "MXN"_sv, { 2 } },
        { "MXV"_sv, { 2 } },
        { "MYR"_sv, { 2 } },
        { "MZN"_sv, { 2 } },
        { "NAD"_sv, { 2 } },
        { "NGN"_sv, { 2 } },
        { "NIO"_sv, { 2 } },
        { "NOK"_sv, { 2 } },
        { "NPR"_sv, { 2 } },
        { "NZD"_sv, { 2 } },
        { "OMR"_sv, { 3 } },
        { "PAB"_sv, { 2 } },
        { "PEN"_sv, { 2 } },
        { "PGK"_sv, { 2 } },
        { "PHP"_sv, { 2 } },
        { "PKR"_sv, { 2 } },
        { "PLN"_sv, { 2 } },
        { "PYG"_sv, { 0 } },
        { "QAR"_sv, { 2 } },
        { "RON"_sv, { 2 } },
        { "RSD"_sv, { 2 } },
        { "RUB"_sv, { 2 } },
        { "RWF"_sv, { 0 } },
        { "SAR"_sv, { 2 } },
        { "SBD"_sv, { 2 } },
        { "SCR"_sv, { 2 } },
        { "SDG"_sv, { 2 } },
        { "SEK"_sv, { 2 } },
        { "SGD"_sv, { 2 } },
        { "SHP"_sv, { 2 } },
        { "SLL"_sv, { 2 } },
        { "SOS"_sv, { 2 } },
        { "SRD"_sv, { 2 } },
        { "SSP"_sv, { 2 } },
        { "STN"_sv, { 2 } },
        { "SVC"_sv, { 2 } },
        { "SYP"_sv, { 2 } },
        { "SZL"_sv, { 2 } },
        { "THB"_sv, { 2 } },
        { "TJS"_sv, { 2 } },
        { "TMT"_sv, { 2 } },
        { "TND"_sv, { 3 } },
        { "TOP"_sv, { 2 } },
        { "TRY"_sv, { 2 } },
        { "TTD"_sv, { 2 } },
        { "TWD"_sv, { 2 } },
        { "TZS"_sv, { 2 } },
        { "UAH"_sv, { 2 } },
        { "UGX"_sv, { 0 } },
        { "USD"_sv, { 2 } },
        { "USN"_sv, { 2 } },
        { "UYI"_sv, { 0 } },
        { "UYU"_sv, { 2 } },
        { "UYW"_sv, { 4 } },
        { "UZS"_sv, { 2 } },
        { "VES"_sv, { 2 } },
        { "VND"_sv, { 0 } },
        { "VUV"_sv, { 0 } },
        { "WST"_sv, { 2 } },
        { "XAF"_sv, { 0 } },
        { "XAG"_sv, { {} } },
        { "XAU"_sv, { {} } },
        { "XBA"_sv, { {} } },
        { "XBB"_sv, { {} } },
        { "XBC"_sv, { {} } },
        { "XBD"_sv, { {} } },
        { "XCD"_sv, { 2 } },
        { "XDR"_sv, { {} } },
        { "XOF"_sv, { 0 } },
        { "XPD"_sv, { {} } },
        { "XPF"_sv, { 0 } },
        { "XPT"_sv, { {} } },
        { "XSU"_sv, { {} } },
        { "XTS"_sv, { {} } },
        { "XUA"_sv, { {} } },
        { "XXX"_sv, { {} } },
        { "YER"_sv, { 2 } },
        { "ZAR"_sv, { 2 } },
        { "ZMW"_sv, { 2 } },
        { "ZWL"_sv, { 2 } },
    };

    return currency_codes;
}

Optional<CurrencyCode const&> get_currency_code(StringView currency)
{
    static auto const& currency_codes = ensure_currency_codes();
    return currency_codes.get(currency);
}

}
