// https://drafts.csswg.org/css-animations-1/#animationevent
[Exposed=Window]
interface AnimationEvent : Event {
    constructor([Utf16FlyString] Utf16CSSOMString type, optional AnimationEventInit animationEventInitDict = {});
    readonly attribute Utf16CSSOMString animationName;
    readonly attribute double elapsedTime;
    readonly attribute Utf16CSSOMString pseudoElement;
};

// https://drafts.csswg.org/css-animations-1/#dictdef-animationeventinit
dictionary AnimationEventInit : EventInit {
    Utf16CSSOMString animationName = "";
    double elapsedTime = 0.0;
    Utf16CSSOMString pseudoElement = "";
};

// https://drafts.csswg.org/css-animations/#interface-globaleventhandlers-idl
partial interface mixin GlobalEventHandlers {
    attribute EventHandler onanimationcancel;
    attribute EventHandler onanimationend;
    attribute EventHandler onanimationiteration;
    attribute EventHandler onanimationstart;
};
