// https://drafts.csswg.org/css-counter-styles/#the-csscounterstylerule-interface
[Exposed=Window]
interface CSSCounterStyleRule : CSSRule {
    attribute Utf16CSSOMString name;
    attribute Utf16CSSOMString system;
    attribute Utf16CSSOMString symbols;
    attribute Utf16CSSOMString additiveSymbols;
    attribute Utf16CSSOMString negative;
    attribute Utf16CSSOMString prefix;
    attribute Utf16CSSOMString suffix;
    attribute Utf16CSSOMString range;
    attribute Utf16CSSOMString pad;
    attribute Utf16CSSOMString speakAs;
    attribute Utf16CSSOMString fallback;
};
