// https://drafts.csswg.org/css-conditional-5/#dictdef-csscontainercondition
dictionary CSSContainerCondition {
    required Utf16CSSOMString name;
    required Utf16CSSOMString query;
};

// https://drafts.csswg.org/css-conditional-5/#csscontainerrule
[Exposed=Window]
interface CSSContainerRule : CSSConditionRule {
    readonly attribute Utf16CSSOMString containerName;
    readonly attribute Utf16CSSOMString containerQuery;
    readonly attribute FrozenArray<CSSContainerCondition> conditions;
};
