#import <CSS/CSSRule.idl>

// https://drafts.csswg.org/css-counter-styles/#the-csscounterstylerule-interface
[Exposed=Window]
interface CSSCounterStyleRule : CSSRule {
    attribute CSSOMString name;
    attribute CSSOMString system;
    [FIXME] attribute CSSOMString symbols;
    [FIXME] attribute CSSOMString additiveSymbols;
    attribute CSSOMString negative;
    attribute CSSOMString prefix;
    attribute CSSOMString suffix;
    attribute CSSOMString range;
    attribute CSSOMString pad;
    [FIXME] attribute CSSOMString speakAs;
    [FIXME] attribute CSSOMString fallback;
};
