// https://drafts.csswg.org/css-fonts/#om-fontface
[Exposed=Window]
interface CSSFontFaceRule : CSSRule {
    [DirectGetter, SameObject, PutForwards=cssText, ImplementedAs=descriptors] readonly attribute CSSFontFaceDescriptors style;
};
