[Exposed=Window]
interface CSSFontFeatureValuesMap {
    maplike<Utf16CSSOMString, sequence<unsigned long>>;
    undefined set(Utf16CSSOMString featureValueName, (unsigned long or sequence<unsigned long>) values);
};
