[Exposed=Window]
interface CSSFontFeatureValuesRule : CSSRule {
    attribute Utf16CSSOMString fontFamily;
    [DirectGetter] readonly attribute CSSFontFeatureValuesMap annotation;
    [DirectGetter] readonly attribute CSSFontFeatureValuesMap ornaments;
    [DirectGetter] readonly attribute CSSFontFeatureValuesMap stylistic;
    [DirectGetter] readonly attribute CSSFontFeatureValuesMap swash;
    [DirectGetter] readonly attribute CSSFontFeatureValuesMap characterVariant;
    [DirectGetter] readonly attribute CSSFontFeatureValuesMap styleset;
    [DirectGetter] readonly attribute CSSFontFeatureValuesMap historicalForms;
};
