// https://drafts.csswg.org/css-mixins-1/#cssfunctiondescriptors
[Exposed=Window]
interface CSSFunctionDescriptors : CSSStyleDeclaration {
    [LegacyNullToEmptyString] attribute CSSOMString result;
};
