#import <CSS/CSSRule.idl>
#import <CSS/CSSFunctionDescriptors.idl>

[Exposed=Window]
interface CSSFunctionDeclarations : CSSRule {
    [SameObject, PutForwards=cssText] readonly attribute CSSFunctionDescriptors style;
};
