// https://drafts.csswg.org/cssom/#the-cssimportrule-interface
[Exposed=Window]
interface CSSImportRule : CSSRule {
    [ImplementedAs=href_for_bindings] readonly attribute Utf16USVString href;
    [SameObject, PutForwards=mediaText] readonly attribute MediaList media;
    [SameObject, ImplementedAs=style_sheet_for_bindings] readonly attribute CSSStyleSheet? styleSheet;
    readonly attribute Utf16CSSOMString? layerName;
    readonly attribute Utf16CSSOMString? supportsText;
};
