#import <CSS/CSSRule.idl>
#import <CSS/CSSStyleSheet.idl>
#import <CSS/MediaList.idl>

// https://drafts.csswg.org/cssom/#the-cssimportrule-interface
[Exposed=Window]
interface CSSImportRule : CSSRule {
    readonly attribute USVString href;
    // AD-HOC: media is null if styleSheet is null. Spec issue: https://github.com/w3c/csswg-drafts/issues/12063
    [SameObject, PutForwards=mediaText] readonly attribute MediaList? media;
    [SameObject, ImplementedAs=style_sheet_for_bindings] readonly attribute CSSStyleSheet? styleSheet;
    readonly attribute CSSOMString? layerName;
    readonly attribute CSSOMString? supportsText;
};
