// https://drafts.csswg.org/css-animations-1/#interface-csskeyframerule-idl
[Exposed=Window]
interface CSSKeyframeRule : CSSRule {
    attribute Utf16CSSOMString keyText;
    [SameObject, PutForwards=cssText] readonly attribute CSSStyleProperties style;
};
