// https://drafts.css-houdini.org/css-typed-om-1/#csskeywordvalue
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSKeywordValue : CSSStyleValue {
    constructor(Utf16USVString value);
    attribute Utf16USVString value;
};

typedef (Utf16DOMString or CSSKeywordValue) CSSKeywordish;
