#import <CSS/CSSTransformComponent.idl>
#import <Geometry/DOMMatrix.idl>
#import <Geometry/DOMMatrixReadOnly.idl>

// https://drafts.css-houdini.org/css-typed-om-1/#cssmatrixcomponent
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSMatrixComponent : CSSTransformComponent {
    constructor(DOMMatrixReadOnly matrix, optional CSSMatrixComponentOptions options = {});
    attribute DOMMatrix matrix;
};

// https://drafts.css-houdini.org/css-typed-om-1/#dictdef-cssmatrixcomponentoptions
dictionary CSSMatrixComponentOptions {
    boolean is2D;
};
