#import <CSS/CSSMathValue.idl>
#import <CSS/CSSNumericArray.idl>

// https://drafts.css-houdini.org/css-typed-om-1/#cssmathsum
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSMathSum : CSSMathValue {
    constructor(CSSNumberish... args);
    readonly attribute CSSNumericArray values;
};
