#import <CSS/CSSNumericValue.idl>

// https://drafts.css-houdini.org/css-typed-om-1/#cssmathvalue
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSMathValue : CSSNumericValue {
    readonly attribute CSSMathOperator operator;
};

// https://drafts.css-houdini.org/css-typed-om-1/#enumdef-cssmathoperator
enum CSSMathOperator {
    "sum",
    "product",
    "negate",
    "invert",
    "min",
    "max",
    "clamp",
};
