// https://drafts.csswg.org/cssom/#the-cssnamespacerule-interface
[Exposed=Window]
interface CSSNamespaceRule : CSSRule {
    readonly attribute Utf16CSSOMString namespaceURI;
    readonly attribute Utf16CSSOMString prefix;
};
