// https://drafts.css-houdini.org/css-typed-om-1/#enumdef-cssnumericbasetype
enum CSSNumericBaseType {
    "length",
    "angle",
    "time",
    "frequency",
    "resolution",
    "flex",
    "percent",
};

// https://drafts.css-houdini.org/css-typed-om-1/#dictdef-cssnumerictype
dictionary CSSNumericType {
    long length;
    long angle;
    long time;
    long frequency;
    long resolution;
    long flex;
    long percent;
    CSSNumericBaseType percentHint;
};

// https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSNumericValue : CSSStyleValue {
    [NeedsCallerRealm] CSSNumericValue add(CSSNumberish... values);
    [NeedsCallerRealm] CSSNumericValue sub(CSSNumberish... values);
    CSSNumericValue mul(CSSNumberish... values);
    CSSNumericValue div(CSSNumberish... values);
    [NeedsCallerRealm] CSSNumericValue min(CSSNumberish... values);
    [NeedsCallerRealm] CSSNumericValue max(CSSNumberish... values);

    [ImplementedAs=equals_for_bindings] boolean equals(CSSNumberish... value);

    [NeedsCallerRealm] CSSUnitValue to(USVString unit);
    // FIXME: CSSMathSum toSum(USVString... units);
    [ImplementedAs=type_for_bindings] CSSNumericType type();

    [Exposed=Window, NeedsCallerRealm] static CSSNumericValue parse(USVString cssText);
};

// https://drafts.css-houdini.org/css-typed-om-1/#typedefdef-cssnumberish
typedef (double or CSSNumericValue) CSSNumberish;
