// https://drafts.csswg.org/cssom/#the-cssnamespacerule-interface
[Exposed=Window]
interface CSSNamespaceRule : CSSRule {
    readonly attribute CSSOMString namespaceURI;
    readonly attribute CSSOMString prefix;
};
