#import <CSS/CSSGroupingRule.idl>
#import <CSS/CSSPageDescriptors.idl>

// https://drafts.csswg.org/cssom/#csspagerule
[Exposed=Window]
interface CSSPageRule : CSSGroupingRule {
    attribute CSSOMString selectorText;
    [SameObject, PutForwards=cssText] readonly attribute CSSPageDescriptors style;
};
