// https://drafts.csswg.org/cssom/#csspagedescriptors
[Exposed=Window]
interface CSSPageDescriptors : CSSStyleDeclaration {
    [LegacyNullToEmptyString] attribute Utf16CSSOMString margin;
    [LegacyNullToEmptyString, AttributeCallbackName=margin_top_regular, ImplementedAs=margin_top] attribute Utf16CSSOMString marginTop;
    [LegacyNullToEmptyString, AttributeCallbackName=margin_right_regular, ImplementedAs=margin_right] attribute Utf16CSSOMString marginRight;
    [LegacyNullToEmptyString, AttributeCallbackName=margin_bottom_regular, ImplementedAs=margin_bottom] attribute Utf16CSSOMString marginBottom;
    [LegacyNullToEmptyString, AttributeCallbackName=margin_left_regular, ImplementedAs=margin_left] attribute Utf16CSSOMString marginLeft;
    [LegacyNullToEmptyString, AttributeCallbackName=margin_top_dashed, ImplementedAs=margin_top] attribute Utf16CSSOMString margin-top;
    [LegacyNullToEmptyString, AttributeCallbackName=margin_right_dashed, ImplementedAs=margin_right] attribute Utf16CSSOMString margin-right;
    [LegacyNullToEmptyString, AttributeCallbackName=margin_bottom_dashed, ImplementedAs=margin_bottom] attribute Utf16CSSOMString margin-bottom;
    [LegacyNullToEmptyString, AttributeCallbackName=margin_left_dashed, ImplementedAs=margin_left] attribute Utf16CSSOMString margin-left;
    [LegacyNullToEmptyString] attribute Utf16CSSOMString size;
    [LegacyNullToEmptyString, AttributeCallbackName=page_orientation_regular, ImplementedAs=page_orientation] attribute Utf16CSSOMString pageOrientation;
    [LegacyNullToEmptyString, AttributeCallbackName=page_orientation_dashed, ImplementedAs=page_orientation] attribute Utf16CSSOMString page-orientation;
    [LegacyNullToEmptyString] attribute Utf16CSSOMString marks;
    [LegacyNullToEmptyString] attribute Utf16CSSOMString bleed;
};
