// https://drafts.csswg.org/cssom/#csspagerule
[Exposed=Window]
interface CSSPageRule : CSSGroupingRule {
    attribute Utf16CSSOMString selectorText;
    [SameObject, PutForwards=cssText] readonly attribute CSSPageDescriptors style;
};
