// https://drafts.css-houdini.org/css-properties-values-api/#the-css-property-rule-interface
[Exposed=Window]
interface CSSPropertyRule : CSSRule {
    readonly attribute Utf16CSSOMString name;
    readonly attribute Utf16CSSOMString syntax;
    readonly attribute boolean inherits;
    readonly attribute Utf16CSSOMString? initialValue;

};
