// https://drafts.css-houdini.org/css-typed-om-1/#cssstylevalue
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSStyleValue {
    stringifier;
    [Exposed=Window, NeedsCallerRealm] static CSSStyleValue parse(USVString property, USVString cssText);
    [Exposed=Window, NeedsCallerRealm] static sequence<CSSStyleValue> parseAll(USVString property, USVString cssText);
};
