// https://drafts.csswg.org/cssom/#cssstyleproperties
// Generated property accessors live on the shared prototype.
[Exposed=Window]
interface CSSStyleProperties : CSSStyleDeclaration {
    [CEReactions, LegacyNullToEmptyString] attribute CSSOMString cssFloat;
};

CSSStyleProperties includes GeneratedCSSStyleProperties;
