#import <CSS/CSSStyleDeclaration.idl>
#import <CSS/GeneratedCSSStyleProperties.idl>

// https://drafts.csswg.org/cssom/#cssstyleproperties
[Exposed=Window]
interface CSSStyleProperties : CSSStyleDeclaration {
    [CEReactions, LegacyNullToEmptyString] attribute CSSOMString cssFloat;
};

CSSStyleProperties includes GeneratedCSSStyleProperties;
