// https://drafts.csswg.org/cssom/#cssstyledeclaration
[Exposed=Window]
interface CSSStyleDeclaration {
    [CEReactions] attribute Utf16CSSOMString cssText;

    readonly attribute unsigned long length;
    getter Utf16CSSOMString item(unsigned long index);

    Utf16CSSOMString getPropertyValue(Utf16CSSOMString property);
    Utf16CSSOMString getPropertyPriority(Utf16CSSOMString property);

    [CEReactions] undefined setProperty(Utf16CSSOMString property, [LegacyNullToEmptyString] Utf16CSSOMString value, optional [LegacyNullToEmptyString] Utf16CSSOMString priority = "");
    [CEReactions] Utf16CSSOMString removeProperty(Utf16CSSOMString property);

    readonly attribute CSSRule? parentRule;
};
