// https://drafts.csswg.org/cssom/#cssstyleproperties
[Exposed=Window]
interface CSSStyleProperties : CSSStyleDeclaration {
    [CEReactions, LegacyNullToEmptyString] attribute Utf16CSSOMString cssFloat;
};

CSSStyleProperties includes GeneratedCSSStyleProperties;
