#import <CSS/CSSNumericValue.idl>
#import <CSS/CSSTransformComponent.idl>

// https://drafts.css-houdini.org/css-typed-om-1/#cssskewx
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSSkewX : CSSTransformComponent {
    constructor(CSSNumericValue ax);
    attribute CSSNumericValue ax;
};
