// https://drafts.csswg.org/cssom/#cssstyledeclaration
[Exposed=Window]
interface CSSStyleDeclaration {
    [CEReactions, NeedsThisObjectRealmForSetter] attribute CSSOMString cssText;

    readonly attribute unsigned long length;
    getter CSSOMString item(unsigned long index);

    CSSOMString getPropertyValue(CSSOMString property);
    CSSOMString getPropertyPriority(CSSOMString property);

    [CEReactions, NeedsCallerRealm] undefined setProperty(CSSOMString property, [LegacyNullToEmptyString] CSSOMString value, optional [LegacyNullToEmptyString] CSSOMString priority = "");
    [CEReactions, NeedsCallerRealm] CSSOMString removeProperty(CSSOMString property);

    readonly attribute CSSRule? parentRule;
};
