// https://drafts.csswg.org/css-cascade-6/#the-cssscoperule-interface
[Exposed=Window]
interface CSSScopeRule : CSSGroupingRule {
    readonly attribute Utf16CSSOMString? start;
    readonly attribute Utf16CSSOMString? end;
};
