// https://drafts.css-houdini.org/css-typed-om-1/#csstranslate
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSTranslate : CSSTransformComponent {
    constructor(CSSNumericValue x, CSSNumericValue y, optional CSSNumericValue z);
    [DirectGetter] attribute CSSNumericValue x;
    [DirectGetter] attribute CSSNumericValue y;
    [DirectGetter] attribute CSSNumericValue z;
};
