#import <CSS/CSSNumericValue.idl>
#import <CSS/CSSTransformComponent.idl>

// https://drafts.css-houdini.org/css-typed-om-1/#csstranslate
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSTranslate : CSSTransformComponent {
    constructor(CSSNumericValue x, CSSNumericValue y, optional CSSNumericValue z);
    attribute CSSNumericValue x;
    attribute CSSNumericValue y;
    attribute CSSNumericValue z;
};
