// https://drafts.css-houdini.org/css-typed-om-1/#cssunitvalue
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSUnitValue : CSSNumericValue {
    constructor(double value, Utf16USVString unit);
    attribute double value;
    readonly attribute Utf16USVString unit;
};
