// https://drafts.css-houdini.org/css-typed-om-1/#cssvariablereferencevalue
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSVariableReferenceValue {
    constructor(Utf16USVString variable, optional CSSUnparsedValue? fallback = null);
    attribute Utf16USVString variable;
    readonly attribute CSSUnparsedValue? fallback;
};
