dictionary FontFaceDescriptors {
    Utf16CSSOMString style = "normal";
    Utf16CSSOMString weight = "normal";
    Utf16CSSOMString stretch = "normal";
    Utf16CSSOMString unicodeRange = "U+0-10FFFF";
    Utf16CSSOMString featureSettings = "normal";
    Utf16CSSOMString variationSettings = "normal";
    Utf16CSSOMString display = "auto";
    Utf16CSSOMString ascentOverride = "normal";
    Utf16CSSOMString descentOverride = "normal";
    Utf16CSSOMString lineGapOverride = "normal";
};

enum FontFaceLoadStatus { "unloaded", "loading", "loaded", "error" };

// https://drafts.csswg.org/css-font-loading/#fontface-interface
[Exposed=(Window,Worker)]
interface FontFace {
    // FIXME: BufferSource usage needs https://github.com/w3c/csswg-drafts/pull/10309
    constructor(Utf16CSSOMString family, (Utf16CSSOMString or BufferSource) source, optional FontFaceDescriptors descriptors = {});
    attribute Utf16CSSOMString family;
    attribute Utf16CSSOMString style;
    attribute Utf16CSSOMString weight;
    attribute Utf16CSSOMString stretch;
    attribute Utf16CSSOMString unicodeRange;
    attribute Utf16CSSOMString featureSettings;
    attribute Utf16CSSOMString variationSettings;
    attribute Utf16CSSOMString display;
    attribute Utf16CSSOMString ascentOverride;
    attribute Utf16CSSOMString descentOverride;
    attribute Utf16CSSOMString lineGapOverride;

    readonly attribute FontFaceLoadStatus status;

    Promise<FontFace> load();
    readonly attribute Promise<FontFace> loaded;
};
