// https://drafts.csswg.org/css-font-loading/#fontfacesetloadevent
dictionary FontFaceSetLoadEventInit : EventInit {
    sequence<FontFace> fontfaces = [];
};


// https://drafts.csswg.org/css-font-loading/#fontfacesetloadevent
[Exposed=(Window,Worker)]
interface FontFaceSetLoadEvent : Event {
    constructor([Utf16FlyString] Utf16CSSOMString type, optional FontFaceSetLoadEventInit eventInitDict = {});
    [SameObject] readonly attribute FrozenArray<FontFace> fontfaces;
};
