// https://drafts.csswg.org/cssom-1/#the-medialist-interface
[Exposed=Window]
interface MediaList {
    [LegacyNullToEmptyString] stringifier attribute Utf16CSSOMString mediaText;
    readonly attribute unsigned long length;
    getter Utf16CSSOMString? item(unsigned long index);
    undefined appendMedium(Utf16CSSOMString medium);
    undefined deleteMedium(Utf16CSSOMString medium);
};
