// https://w3c.github.io/csswg-drafts/cssom-view-1/#mediaquerylistevent
[Exposed=Window]
interface MediaQueryListEvent : Event {
    constructor([Utf16FlyString] Utf16CSSOMString type, optional MediaQueryListEventInit eventInitDict = {});

    readonly attribute Utf16CSSOMString media;
    readonly attribute boolean matches;
};

dictionary MediaQueryListEventInit : EventInit {
    Utf16CSSOMString media = "";
    boolean matches = false;
};
