// https://drafts.csswg.org/cssom/#stylesheet
[Exposed=Window]
interface StyleSheet {

    readonly attribute Utf16CSSOMString type;
    [ImplementedAs=href_for_bindings] readonly attribute Utf16USVString? href;

    // FIXME: readonly attribute (Element or ProcessingInstruction)? ownerNode;
    readonly attribute Element? ownerNode;

    readonly attribute CSSStyleSheet? parentStyleSheet;
    [ImplementedAs=title_for_bindings] readonly attribute Utf16DOMString? title;
    [SameObject, PutForwards=mediaText] readonly attribute MediaList media;
    attribute boolean disabled;

};
