// https://drafts.csswg.org/css-transitions-2/#interface-transitionevent-idl
[Exposed=Window]
interface TransitionEvent : Event {
    constructor([Utf16FlyString] Utf16CSSOMString type, optional TransitionEventInit transitionEventInitDict = {});
    readonly attribute Utf16CSSOMString propertyName;
    readonly attribute double elapsedTime;
    readonly attribute Utf16CSSOMString pseudoElement;
    readonly attribute CSSTransition? animation;
};

// https://drafts.csswg.org/css-transitions-2/#interface-transitionevent-idl
dictionary TransitionEventInit : EventInit {
    Utf16CSSOMString propertyName = "";
    double elapsedTime = 0.0;
    Utf16CSSOMString pseudoElement = "";
    CSSTransition? animation = null;
};

// https://drafts.csswg.org/css-transitions/#interface-globaleventhandlers-idl
partial interface mixin GlobalEventHandlers {
    attribute EventHandler ontransitionrun;
    attribute EventHandler ontransitionstart;
    attribute EventHandler ontransitionend;
    attribute EventHandler ontransitioncancel;
};
