// https://drafts.csswg.org/css-transitions/#transitionevent
[Exposed=Window]
interface TransitionEvent : Event {
    constructor([Utf16FlyString] Utf16CSSOMString type, optional TransitionEventInit transitionEventInitDict = {});
    readonly attribute Utf16CSSOMString propertyName;
    readonly attribute double elapsedTime;
    readonly attribute Utf16CSSOMString pseudoElement;
};

dictionary TransitionEventInit : EventInit {
    Utf16CSSOMString propertyName = "";
    double elapsedTime = 0.0;
    Utf16CSSOMString pseudoElement = "";
};
