// https://w3c.github.io/IntersectionObserver/#intersectionobserverentry
[Exposed=Window]
interface IntersectionObserverEntry {
    // FIXME: constructor(IntersectionObserverEntryInit intersectionObserverEntryInit);
    readonly attribute DOMHighResTimeStamp time;
    [DirectGetter] readonly attribute DOMRectReadOnly? rootBounds;
    [DirectGetter] readonly attribute DOMRectReadOnly boundingClientRect;
    [DirectGetter] readonly attribute DOMRectReadOnly intersectionRect;
    readonly attribute boolean isIntersecting;
    readonly attribute double intersectionRatio;
    [DirectGetter] readonly attribute Element target;
};

dictionary IntersectionObserverEntryInit {
    required DOMHighResTimeStamp time;
    required DOMRectInit? rootBounds;
    required DOMRectInit boundingClientRect;
    required DOMRectInit intersectionRect;
    required boolean isIntersecting;
    required double intersectionRatio;
    required Element target;
};
