// https://w3c.github.io/uievents/#compositionevent
[Exposed=Window]
interface CompositionEvent : UIEvent {
    constructor([Utf16FlyString] Utf16DOMString type, optional CompositionEventInit eventInitDict = {});
    readonly attribute Utf16DOMString data;

    // https://w3c.github.io/uievents/#dom-compositionevent-initcompositionevent
    // FIXME: The spec uses WindowProxy rather than Window (see https://github.com/w3c/uievents/pull/379).
    undefined initCompositionEvent([Utf16FlyString] Utf16DOMString typeArg, optional boolean bubblesArg = false, optional boolean cancelableArg = false, optional WindowProxy? viewArg = null, optional Utf16DOMString dataArg = "");
};

// https://w3c.github.io/uievents/#dictdef-compositioneventinit
dictionary CompositionEventInit : UIEventInit {
    Utf16DOMString data = "";
};
