// https://w3c.github.io/uievents/#inputevent
[Exposed=Window]
interface InputEvent : UIEvent {
    constructor([FlyString] DOMString type, optional InputEventInit eventInitDict = {});
    readonly attribute USVString? data;
    readonly attribute boolean isComposing;
    readonly attribute DOMString inputType;

    // https://w3c.github.io/input-events/#interface-InputEvent
    [DirectGetter] readonly attribute DataTransfer? dataTransfer;
    sequence<StaticRange> getTargetRanges();
};

// https://w3c.github.io/uievents/#dictdef-inputeventinit
dictionary InputEventInit : UIEventInit {
    DOMString? data = null;
    boolean isComposing = false;
    [FlyString] DOMString inputType = "";

    // https://w3c.github.io/input-events/#interface-InputEvent
    DataTransfer? dataTransfer = null;
    sequence<StaticRange> targetRanges = [];
};
