// https://w3c.github.io/uievents/#textevent
[Exposed=Window]
interface TextEvent : UIEvent {
    readonly attribute Utf16DOMString data;
    undefined initTextEvent([Utf16FlyString] Utf16DOMString type, optional boolean bubbles = false, optional boolean cancelable = false, optional WindowProxy? view = null, optional Utf16DOMString data = "undefined");
};
