/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Generated CSS keyword and enum vocabulary, shared by the crate's modules. The constants are
//! generated by build.rs from the same JSON files as the C++ enums, so the numeric values cannot
//! drift between the two sides.

include!(concat!(env!("OUT_DIR"), "/keywords_generated.rs"));
include!(concat!(env!("OUT_DIR"), "/css_enums_generated.rs"));

pub(crate) fn keyword_from_ascii_case_insensitive(identifier: &[u16]) -> Option<u16> {
    use crate::css::ffi_support::ascii_lowercase;

    keyword::SORTED_NAMES
        .binary_search_by(|&(name, _)| {
            for (&identifier_unit, name_byte) in identifier.iter().zip(name.bytes()) {
                match u16::from(name_byte).cmp(&ascii_lowercase(identifier_unit)) {
                    std::cmp::Ordering::Equal => {}
                    ordering => return ordering,
                }
            }
            name.len().cmp(&identifier.len())
        })
        .ok()
        .map(|index| keyword::SORTED_NAMES[index].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn looks_up_keywords_case_insensitively() {
        assert_eq!(
            keyword_from_ascii_case_insensitive(&"ReVeRt-LaYeR".encode_utf16().collect::<Vec<_>>()),
            Some(keyword::REVERT_LAYER)
        );
        assert_eq!(
            keyword_from_ascii_case_insensitive(&"unknown".encode_utf16().collect::<Vec<_>>()),
            None
        );
        assert_eq!(keyword_from_ascii_case_insensitive(&[0xe9]), None);
    }
}
