/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Generated CSS keyword and enum vocabulary, shared by the crate's modules. The constants are
//! generated by build.rs from the same JSON files as the C++ enums, so the numeric values cannot
//! drift between the two sides.

include!(concat!(env!("OUT_DIR"), "/keywords_generated.rs"));
include!(concat!(env!("OUT_DIR"), "/css_enums_generated.rs"));
