/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Generated CSS property metadata for the Rust style computation core.
//!
//! The tables are generated by build.rs from Properties.json, replicating the
//! property identifier assignment of the C++ generator exactly: Custom is 0,
//! then shorthands, inherited longhands and non-inherited longhands in JSON
//! order, skipping legacy aliases. A C++ unit test compares every table
//! against the C++-generated equivalents so the two generators cannot drift.
//!
//! Property identifiers cross the FFI as opaque u16 values, like keywords.

include!(concat!(env!("OUT_DIR"), "/property_metadata_generated.rs"));

pub(crate) const NUMBER_OF_LONGHAND_PROPERTIES: usize =
    (LAST_LONGHAND_PROPERTY_ID - FIRST_LONGHAND_PROPERTY_ID + 1) as usize;

/// How much of the computation a property needs, mirroring the C++
/// requires-computation levels: 0 = never, 1 = with the cascaded value,
/// 2 = with any non-inherited value, 3 = always.
pub const REQUIRES_COMPUTATION_NEVER: u8 = 0;
pub const REQUIRES_COMPUTATION_CASCADED: u8 = 1;
pub const REQUIRES_COMPUTATION_NON_INHERITED: u8 = 2;
pub const REQUIRES_COMPUTATION_ALWAYS: u8 = 3;

fn longhand_index(property_id: u16) -> usize {
    debug_assert!((FIRST_LONGHAND_PROPERTY_ID..=LAST_LONGHAND_PROPERTY_ID).contains(&property_id));
    (property_id - FIRST_LONGHAND_PROPERTY_ID) as usize
}

pub fn property_is_inherited(property_id: u16) -> bool {
    (FIRST_INHERITED_PROPERTY_ID..=LAST_INHERITED_PROPERTY_ID).contains(&property_id)
}

pub fn property_requires_computation_level(property_id: u16) -> u8 {
    REQUIRES_COMPUTATION_LEVELS[longhand_index(property_id)]
}

pub fn property_animation_type(property_id: u16) -> u8 {
    PROPERTY_ANIMATION_TYPES[longhand_index(property_id)]
}

pub(crate) fn pseudo_element_supports_property(pseudo_element: u8, property_id: u16) -> bool {
    if PSEUDO_ELEMENT_ALWAYS_ALLOWED_PROPERTIES
        .binary_search(&property_id)
        .is_ok()
    {
        return true;
    }
    match PSEUDO_ELEMENT_PROPERTY_WHITELISTS[pseudo_element as usize] {
        Some(whitelist) => whitelist.binary_search(&property_id).is_ok(),
        None => true,
    }
}

/// An accepted numeric range for one CSS value type.
#[repr(C)]
pub struct FfiPropertyNumericRange {
    pub value_type: u8,
    pub min: f64,
    pub max: f64,
}

pub fn property_numeric_ranges(property_id: u16) -> &'static [FfiPropertyNumericRange] {
    PROPERTY_NUMERIC_RANGES[longhand_index(property_id)]
}

/// Returns the longhand property identifiers in computation order.
pub fn property_computation_order() -> &'static [u16] {
    &PROPERTY_COMPUTATION_ORDER
}

/// FFI accessors for the parity test on the C++ side.
///
/// # Safety
/// `out_length` must be a valid pointer.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rust_property_metadata_computation_order(out_length: *mut usize) -> *const u16 {
    unsafe { *out_length = PROPERTY_COMPUTATION_ORDER.len() };
    PROPERTY_COMPUTATION_ORDER.as_ptr()
}

#[unsafe(no_mangle)]
pub extern "C" fn rust_property_metadata_is_inherited(property_id: u16) -> bool {
    property_is_inherited(property_id)
}

#[unsafe(no_mangle)]
pub extern "C" fn rust_property_metadata_requires_computation_level(property_id: u16) -> u8 {
    property_requires_computation_level(property_id)
}

#[unsafe(no_mangle)]
pub extern "C" fn rust_property_metadata_animation_type(property_id: u16) -> u8 {
    property_animation_type(property_id)
}

/// # Safety
/// `out_length` must be a valid pointer.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rust_property_metadata_numeric_ranges(
    property_id: u16,
    out_length: *mut usize,
) -> *const FfiPropertyNumericRange {
    let ranges = property_numeric_ranges(property_id);
    unsafe { *out_length = ranges.len() };
    ranges.as_ptr()
}

/// # Safety
/// All out-pointers must be valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rust_property_metadata_bounds(
    out_first_longhand: *mut u16,
    out_last_longhand: *mut u16,
    out_first_inherited: *mut u16,
    out_last_inherited: *mut u16,
) {
    unsafe {
        *out_first_longhand = FIRST_LONGHAND_PROPERTY_ID;
        *out_last_longhand = LAST_LONGHAND_PROPERTY_ID;
        *out_first_inherited = FIRST_INHERITED_PROPERTY_ID;
        *out_last_inherited = LAST_INHERITED_PROPERTY_ID;
    }
}

pub fn property_is_shorthand(property_id: u16) -> bool {
    (FIRST_SHORTHAND_PROPERTY_ID..=LAST_SHORTHAND_PROPERTY_ID).contains(&property_id)
}

/// Returns the longhands a shorthand expands to, in Properties.json order.
pub fn longhands_for_shorthand(property_id: u16) -> &'static [u16] {
    if !property_is_shorthand(property_id) {
        return &[];
    }
    SHORTHAND_EXPANSIONS[(property_id - FIRST_SHORTHAND_PROPERTY_ID) as usize]
}

fn property_index(property_id: u16) -> usize {
    debug_assert!((FIRST_SHORTHAND_PROPERTY_ID..=LAST_LONGHAND_PROPERTY_ID).contains(&property_id));
    (property_id - FIRST_SHORTHAND_PROPERTY_ID) as usize
}

fn property_is_logical_alias_including_shorthands(property_id: u16) -> bool {
    PROPERTY_IS_LOGICAL_ALIAS[property_index(property_id)]
}

/// Returns whether `a` wins a keyframe declaration conflict with `b`.
pub(crate) fn animation_property_is_preferred(a: u16, b: u16) -> bool {
    // https://drafts.csswg.org/web-animations-1/#ref-for-computed-keyframes
    // If conflicts arise when expanding shorthand properties or replacing logical properties with physical properties, apply the following rules in order until the conflict is resolved:

    // 1. Longhand properties override shorthand properties (e.g. border-top-color overrides border-top).
    if property_is_shorthand(a) != property_is_shorthand(b) {
        return !property_is_shorthand(a);
    }

    // 2. Shorthand properties with fewer longhand components override those with more longhand components (e.g. border-top overrides border-color).
    if property_is_shorthand(a) {
        let a_length = SHORTHAND_EXPANDED_LONGHAND_COUNTS[(a - FIRST_SHORTHAND_PROPERTY_ID) as usize];
        let b_length = SHORTHAND_EXPANDED_LONGHAND_COUNTS[(b - FIRST_SHORTHAND_PROPERTY_ID) as usize];
        if a_length != b_length {
            return a_length < b_length;
        }
    }

    let a_is_logical_alias = property_is_logical_alias_including_shorthands(a);
    let b_is_logical_alias = property_is_logical_alias_including_shorthands(b);

    // 3. Physical properties override logical properties.
    if a_is_logical_alias != b_is_logical_alias {
        return !a_is_logical_alias;
    }

    // 4. For shorthand properties with an equal number of longhand components, properties whose IDL name (see
    //    the CSS property to IDL attribute algorithm [CSSOM]) appears earlier when sorted in ascending order
    //    by the Unicode codepoints that make up each IDL name, override those who appear later.
    PROPERTY_IDL_NAMES[property_index(a)] < PROPERTY_IDL_NAMES[property_index(b)]
}

/// FFI accessor for the metadata parity test on the C++ side.
#[unsafe(no_mangle)]
pub extern "C" fn rust_animation_property_is_preferred(a: u16, b: u16) -> bool {
    animation_property_is_preferred(a, b)
}

/// FFI accessors for the parity test on the C++ side.
#[unsafe(no_mangle)]
pub extern "C" fn rust_property_metadata_is_shorthand(property_id: u16) -> bool {
    property_is_shorthand(property_id)
}

/// # Safety
/// `out_length` must be a valid pointer.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rust_property_metadata_longhands_for_shorthand(
    property_id: u16,
    out_length: *mut usize,
) -> *const u16 {
    let longhands = longhands_for_shorthand(property_id);
    unsafe { *out_length = longhands.len() };
    longhands.as_ptr()
}
