// https://w3c.github.io/aria/#ARIAMixin
interface mixin ARIAMixin {
    [CEReactions] attribute Utf16DOMString? role;
    [Reflect=aria-activedescendant, CEReactions] attribute Element? ariaActiveDescendantElement;
    [CEReactions] attribute Utf16DOMString? ariaAtomic;
    [CEReactions] attribute Utf16DOMString? ariaAutoComplete;
    [CEReactions] attribute Utf16DOMString? ariaBrailleLabel;
    [CEReactions] attribute Utf16DOMString? ariaBrailleRoleDescription;
    [CEReactions] attribute Utf16DOMString? ariaBusy;
    [CEReactions] attribute Utf16DOMString? ariaChecked;
    [CEReactions] attribute Utf16DOMString? ariaColCount;
    [CEReactions] attribute Utf16DOMString? ariaColIndex;
    [CEReactions] attribute Utf16DOMString? ariaColIndexText;
    [CEReactions] attribute Utf16DOMString? ariaColSpan;
    [Reflect=aria-controls, CEReactions] attribute FrozenArray<Element>? ariaControlsElements;
    [CEReactions] attribute Utf16DOMString? ariaCurrent;
    [Reflect=aria-describedby, CEReactions] attribute FrozenArray<Element>? ariaDescribedByElements;
    [CEReactions] attribute Utf16DOMString? ariaDescription;
    [Reflect=aria-details, CEReactions] attribute FrozenArray<Element>? ariaDetailsElements;
    [CEReactions] attribute Utf16DOMString? ariaDisabled;
    [Reflect=aria-errormessage, CEReactions] attribute FrozenArray<Element>? ariaErrorMessageElements;
    [CEReactions] attribute Utf16DOMString? ariaExpanded;
    [Reflect=aria-flowto, CEReactions] attribute FrozenArray<Element>? ariaFlowToElements;
    [CEReactions] attribute Utf16DOMString? ariaHasPopup;
    [CEReactions] attribute Utf16DOMString? ariaHidden;
    [CEReactions] attribute Utf16DOMString? ariaInvalid;
    [CEReactions] attribute Utf16DOMString? ariaKeyShortcuts;
    [CEReactions] attribute Utf16DOMString? ariaLabel;
    [Reflect=aria-labelledby, CEReactions] attribute FrozenArray<Element>? ariaLabelledByElements;
    [CEReactions] attribute Utf16DOMString? ariaLevel;
    [CEReactions] attribute Utf16DOMString? ariaLive;
    [CEReactions] attribute Utf16DOMString? ariaModal;
    [CEReactions] attribute Utf16DOMString? ariaMultiLine;
    [CEReactions] attribute Utf16DOMString? ariaMultiSelectable;
    [CEReactions] attribute Utf16DOMString? ariaOrientation;
    [Reflect=aria-owns, CEReactions] attribute FrozenArray<Element>? ariaOwnsElements;
    [CEReactions] attribute Utf16DOMString? ariaPlaceholder;
    [CEReactions] attribute Utf16DOMString? ariaPosInSet;
    [CEReactions] attribute Utf16DOMString? ariaPressed;
    [CEReactions] attribute Utf16DOMString? ariaReadOnly;
    [CEReactions] attribute Utf16DOMString? ariaRelevant;
    [CEReactions] attribute Utf16DOMString? ariaRequired;
    [CEReactions] attribute Utf16DOMString? ariaRoleDescription;
    [CEReactions] attribute Utf16DOMString? ariaRowCount;
    [CEReactions] attribute Utf16DOMString? ariaRowIndex;
    [CEReactions] attribute Utf16DOMString? ariaRowIndexText;
    [CEReactions] attribute Utf16DOMString? ariaRowSpan;
    [CEReactions] attribute Utf16DOMString? ariaSelected;
    [CEReactions] attribute Utf16DOMString? ariaSetSize;
    [CEReactions] attribute Utf16DOMString? ariaSort;
    [CEReactions] attribute Utf16DOMString? ariaValueMax;
    [CEReactions] attribute Utf16DOMString? ariaValueMin;
    [CEReactions] attribute Utf16DOMString? ariaValueNow;
    [CEReactions] attribute Utf16DOMString? ariaValueText;
};
