// https://immersive-web.github.io/webxr-test-api/#fakexrdeviceinit-dict
dictionary FakeXRDeviceInit {
    // required boolean supportsImmersive;
    sequence<XRSessionMode> supportedModes;
    // required sequence<FakeXRViewInit> views;
    // sequence<FakeXRViewInit> secondaryViews;

    sequence<any> supportedFeatures;
    // sequence<FakeXRBoundsPoint> boundsCoordinates;
    // FakeXRRigidTransformInit floorOrigin;
    // FakeXRRigidTransformInit viewerOrigin;

    // Hit test extensions:
    // FakeXRWorldInit world;

    // Depth sensing extensions:
    // FakeXRDepthSensingDataInit depthSensingData;
    // FakeXRDepthConfigurationSupport depthSupport;
};

// https://immersive-web.github.io/webxr-test-api/#fakexrdevice-interface
// FIXME: FakeXRDevice should be a subclass of EventTarget.
[SecureContext, Exposed=Nobody]
interface FakeXRDevice {
    // FIXME: undefined setViews(sequence<FakeXRViewInit> views, optional sequence<FakeXRViewInit> secondaryViews);

    Promise<undefined> disconnect();

    // FIXME: undefined setViewerOrigin(FakeXRRigidTransformInit origin, optional boolean emulatedPosition = false);
    // FIXME: undefined clearViewerOrigin();
    // FIXME: undefined setFloorOrigin(FakeXRRigidTransformInit origin);
    // FIXME: undefined clearFloorOrigin();
    // FIXME: undefined setBoundsGeometry(sequence<FakeXRBoundsPoint> boundsCoordinates);
    // FIXME: undefined simulateResetPose();

    // FIXME: undefined simulateVisibilityChange(XRVisibilityState state);

    // FIXME: FakeXRInputController simulateInputSourceConnection(FakeXRInputSourceInit init);

    // Hit test extensions:
    // FIXME: undefined setWorld(FakeXRWorldInit world);
    // FIXME: undefined clearWorld();

    // Depth sensing extensions:
    // FIXME: undefined setDepthSensingData(FakeXRDepthSensingDataInit depthSensingData);
    // FIXME: undefined clearDepthSensingData();
};
