[Exposed=Nobody]
interface Settings {
    undefined loadCurrentSettings();
    undefined restoreDefaultSettings();

    undefined setNewTabPageURL(USVString newTabPageURL);

    undefined loadAvailableSearchEngines();
    undefined setSearchEngine(DOMString? search_engine);
};
