typedef (File or Utf16USVString) FormDataEntryValue;

// https://xhr.spec.whatwg.org/#interface-formdata
[Exposed=(Window,Worker)]
interface FormData {
    constructor(optional HTMLFormElement form, optional HTMLElement? submitter = null);

    undefined append(Utf16USVString name, Utf16USVString value);
    undefined append(Utf16USVString name, Blob blobValue, optional Utf16USVString filename);
    undefined delete(Utf16USVString name);
    FormDataEntryValue? get(Utf16USVString name);
    sequence<FormDataEntryValue> getAll(Utf16USVString name);
    boolean has(Utf16USVString name);
    undefined set(Utf16USVString name, Utf16USVString value);
    undefined set(Utf16USVString name, Blob blobValue, optional Utf16USVString filename);
    iterable<Utf16USVString, FormDataEntryValue>;
};
