typedef (Utf16USVString or URLPatternInit) URLPatternInput;

// https://urlpattern.spec.whatwg.org/#urlpattern
[Exposed=(Window,Worker)]
interface URLPattern {
    constructor(URLPatternInput input, Utf16USVString baseURL, optional URLPatternOptions options = {});
    constructor(optional URLPatternInput input = {}, optional URLPatternOptions options = {});

    boolean test(optional URLPatternInput input = {}, optional Utf16USVString baseURL);

    URLPatternResult? exec(optional URLPatternInput input = {}, optional Utf16USVString baseURL);

    readonly attribute Utf16USVString protocol;
    readonly attribute Utf16USVString username;
    readonly attribute Utf16USVString password;
    readonly attribute Utf16USVString hostname;
    readonly attribute Utf16USVString port;
    readonly attribute Utf16USVString pathname;
    readonly attribute Utf16USVString search;
    readonly attribute Utf16USVString hash;

    readonly attribute boolean hasRegExpGroups;
};

// https://urlpattern.spec.whatwg.org/#dictdef-urlpatterninit
dictionary URLPatternInit {
    Utf16USVString protocol;
    Utf16USVString username;
    Utf16USVString password;
    Utf16USVString hostname;
    Utf16USVString port;
    Utf16USVString pathname;
    Utf16USVString search;
    Utf16USVString hash;
    Utf16USVString baseURL;
};

// https://urlpattern.spec.whatwg.org/#dictdef-urlpatternoptions
dictionary URLPatternOptions {
    boolean ignoreCase = false;
};

// https://urlpattern.spec.whatwg.org/#dictdef-urlpatternresult
dictionary URLPatternResult {
    sequence<URLPatternInput> inputs;

    URLPatternComponentResult protocol;
    URLPatternComponentResult username;
    URLPatternComponentResult password;
    URLPatternComponentResult hostname;
    URLPatternComponentResult port;
    URLPatternComponentResult pathname;
    URLPatternComponentResult search;
    URLPatternComponentResult hash;
};

// https://urlpattern.spec.whatwg.org/#dictdef-urlpatterncomponentresult
dictionary URLPatternComponentResult {
    Utf16USVString input;
    record<Utf16USVString, (Utf16USVString or undefined)> groups;
};
