#import <DOM/NamedNodeMap.idl>

[Exposed=Nobody] interface Inspector {

    undefined inspectorLoaded();
    undefined inspectDOMNode(long long nodeID, optional long pseudoElement);

    undefined setDOMNodeText(long long nodeID, DOMString text);
    undefined setDOMNodeTag(long long nodeID, DOMString tag);
    undefined addDOMNodeAttributes(long long nodeID, NamedNodeMap attributes);
    undefined replaceDOMNodeAttribute(long long nodeID, unsigned long long attributeIndex, NamedNodeMap replacementAttributes);

    undefined requestDOMTreeContextMenu(long long nodeID, long clientX, long clientY, DOMString type, DOMString? tag, unsigned long long? attributeIndex);

    undefined requestCookieContextMenu(unsigned long long cookieIndex, long clientX, long clientY);

    undefined requestStyleSheetSource(DOMString type, long long? domNodeID, DOMString? url);

    undefined executeConsoleScript(DOMString script);

    undefined exportInspectorHTML(DOMString html);

};
