// https://w3c.github.io/webcrypto/#crypto-interface
[Exposed=(Window,Worker)]
interface Crypto {
    [SecureContext] readonly attribute SubtleCrypto subtle;

    [NeedsCallerRealm] ArrayBufferView getRandomValues(ArrayBufferView array);

    [SecureContext] DOMString randomUUID();
};
