// https://html.spec.whatwg.org/multipage/canvas.html#canvasgradient
[Exposed=(Window,Worker)]
interface CanvasGradient {
    // opaque object
    undefined addColorStop(double offset, DOMString color);
};
