// https://websockets.spec.whatwg.org/#the-closeevent-interface
[Exposed=*]
interface CloseEvent : Event {
    constructor([Utf16FlyString] Utf16DOMString type, optional CloseEventInit eventInitDict = {});

    readonly attribute boolean wasClean;
    readonly attribute unsigned short code;
    readonly attribute Utf16USVString reason;
};

dictionary CloseEventInit : EventInit {
    boolean wasClean = false;
    unsigned short code = 0;
    Utf16USVString reason = "";
};
