// https://html.spec.whatwg.org/multipage/dnd.html#datatransfer
[Exposed=Window]
interface DataTransfer {
    constructor();

    attribute [Utf16FlyString] Utf16DOMString dropEffect;
    attribute [Utf16FlyString] Utf16DOMString effectAllowed;

    [SameObject] readonly attribute DataTransferItemList items;

    [FIXME] undefined setDragImage(Element image, long x, long y);

    // old interface
    [CachedAttribute] readonly attribute FrozenArray<Utf16DOMString> types;
    Utf16DOMString getData(Utf16DOMString format);
    undefined setData(Utf16DOMString format, Utf16DOMString data);
    undefined clearData(optional Utf16DOMString format);
    [SameObject] readonly attribute FileList files;
};
