// https://html.spec.whatwg.org/multipage/webappapis.html#errorevent
[Exposed=(Window,Worker)]
interface ErrorEvent : Event {
    constructor([Utf16FlyString] Utf16DOMString type, optional ErrorEventInit eventInitDict = {});

    readonly attribute Utf16DOMString message;
    readonly attribute Utf16USVString filename;
    readonly attribute unsigned long lineno;
    readonly attribute unsigned long colno;
    readonly attribute any error;
};

// https://html.spec.whatwg.org/multipage/webappapis.html#erroreventinit
dictionary ErrorEventInit : EventInit {
    Utf16DOMString message = "";
    Utf16USVString filename = "";
    unsigned long lineno = 0;
    unsigned long colno = 0;
    any error;
};
