// https://html.spec.whatwg.org/multipage/nav-history-apis.html#hashchangeevent
[Exposed=Window]
interface HashChangeEvent : Event {
    constructor([Utf16FlyString] Utf16DOMString type, optional HashChangeEventInit eventInitDict = {});

    readonly attribute Utf16USVString oldURL;
    readonly attribute Utf16USVString newURL;
};

dictionary HashChangeEventInit : EventInit {
    Utf16USVString oldURL = "";
    Utf16USVString newURL = "";
};
