// https://fetch.spec.whatwg.org/#concept-potential-destination
enum PotentialDestination {
    "",
    "audio",
    "audioworklet",
    "document",
    "embed",
    "font",
    "frame",
    "iframe",
    "image",
    "json",
    "manifest",
    "object",
    "paintworklet",
    "report",
    "script",
    "serviceworker",
    "sharedworker",
    "style",
    "track",
    "video",
    "webidentity",
    "worker",
    "xslt",
    "fetch"
};

// https://html.spec.whatwg.org/multipage/semantics.html#htmllinkelement
[Exposed=Window]
interface HTMLLinkElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect, URL] attribute Utf16USVString href;
    [CEReactions, Reflect=crossorigin, Enumerated=CORSSettingsAttribute] attribute Utf16DOMString? crossOrigin;
    [CEReactions, Reflect] attribute Utf16DOMString rel;
    [CEReactions, Reflect, Enumerated=PotentialDestination] attribute Utf16DOMString as;
    [SameObject, PutForwards=value] readonly attribute DOMTokenList relList;
    [CEReactions] attribute Utf16DOMString media;
    [CEReactions, Reflect] attribute Utf16DOMString integrity;
    [CEReactions, Reflect] attribute Utf16DOMString hreflang;
    [CEReactions, Reflect] attribute Utf16DOMString type;
    [SameObject, PutForwards=value] readonly attribute DOMTokenList sizes;
    [CEReactions, Reflect=imagesrcset] attribute Utf16USVString imageSrcset;
    [CEReactions, Reflect=imagesizes] attribute Utf16DOMString imageSizes;
    [CEReactions, Reflect=referrerpolicy, Enumerated=ReferrerPolicy] attribute Utf16DOMString referrerPolicy;
    [FIXME, SameObject, PutForwards=value] readonly attribute DOMTokenList blocking;
    [CEReactions, Reflect] attribute boolean disabled;
    [CEReactions, Enumerated=FetchPriorityAttribute, Reflect=fetchpriority] attribute Utf16DOMString fetchPriority;

    // Obsolete
    [CEReactions, Reflect] attribute Utf16DOMString charset;
    [CEReactions, Reflect] attribute Utf16DOMString rev;
    [CEReactions, Reflect] attribute Utf16DOMString target;

};
HTMLLinkElement includes LinkStyle;
