// https://html.spec.whatwg.org/multipage/media.html#htmlaudioelement
[Exposed=Window, LegacyFactoryFunction=Audio(optional Utf16DOMString src)]
interface HTMLAudioElement : HTMLMediaElement {
    [HTMLConstructor] constructor();
};
