// https://html.spec.whatwg.org/multipage/semantics.html#htmlbaseelement
[Exposed=Window]
interface HTMLBaseElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions] attribute Utf16USVString href;
    [CEReactions, Reflect] attribute Utf16DOMString target;

};
