// https://html.spec.whatwg.org/multipage/iframe-embed-object.html#htmlobjectelement
[Exposed=Window]
interface HTMLObjectElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, URL] attribute Utf16USVString data;
    [CEReactions, Reflect] attribute Utf16DOMString type;
    [CEReactions, Reflect] attribute Utf16DOMString name;
    readonly attribute HTMLFormElement? form;
    [CEReactions, Reflect] attribute Utf16DOMString width;
    [CEReactions, Reflect] attribute Utf16DOMString height;
    readonly attribute Document? contentDocument;
    readonly attribute WindowProxy? contentWindow;
    Document? getSVGDocument();

    readonly attribute boolean willValidate;
    readonly attribute ValidityState validity;
    readonly attribute Utf16DOMString validationMessage;
    boolean checkValidity();
    boolean reportValidity();
    undefined setCustomValidity(Utf16DOMString error);

    // Obsolete
    [CEReactions, Reflect] attribute Utf16DOMString align;
    [CEReactions, Reflect] attribute Utf16DOMString archive;
    [CEReactions, Reflect] attribute Utf16DOMString code;
    [CEReactions, Reflect] attribute boolean declare;
    [CEReactions, Reflect] attribute unsigned long hspace;
    [CEReactions, Reflect] attribute Utf16DOMString standby;
    [CEReactions, Reflect] attribute unsigned long vspace;
    [CEReactions, Reflect=codebase, URL] attribute Utf16USVString codeBase;
    [CEReactions, Reflect=codetype] attribute Utf16DOMString codeType;
    [CEReactions, Reflect=usemap] attribute Utf16DOMString useMap;

    [CEReactions, LegacyNullToEmptyString, Reflect] attribute Utf16DOMString border;

};
