// https://html.spec.whatwg.org/multipage/embedded-content.html#htmlsourceelement
[Exposed=Window]
interface HTMLSourceElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect, URL] attribute Utf16USVString src;
    [CEReactions, Reflect] attribute Utf16DOMString type;
    [CEReactions, Reflect] attribute Utf16USVString srcset;
    [CEReactions, Reflect] attribute Utf16DOMString sizes;
    [CEReactions, Reflect] attribute Utf16DOMString media;
    [CEReactions, Reflect] attribute unsigned long width;
    [CEReactions, Reflect] attribute unsigned long height;

};
