typedef (CanvasRenderingContext2D or WebGLRenderingContext or WebGL2RenderingContext) RenderingContext;

// https://html.spec.whatwg.org/multipage/semantics.html#htmlcanvaselement
[Exposed=Window]
interface HTMLCanvasElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions] attribute unsigned long width;
    [CEReactions] attribute unsigned long height;

    RenderingContext? getContext(Utf16DOMString contextId, optional any options = null);

    Utf16USVString toDataURL(optional Utf16DOMString type = "image/png", optional any quality);
    undefined toBlob(BlobCallback _callback, optional Utf16DOMString type = "image/png", optional any quality);

};

callback BlobCallback = undefined (Blob? blob);
