// https://html.spec.whatwg.org/multipage/semantics.html#htmlframesetelement
[Exposed=Window]
interface HTMLFrameSetElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute Utf16DOMString cols;
    [CEReactions, Reflect] attribute Utf16DOMString rows;

};

HTMLFrameSetElement includes WindowEventHandlers;
