// https://html.spec.whatwg.org/multipage/image-maps.html#htmlareaelement
[Exposed=Window]
interface HTMLAreaElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute Utf16DOMString alt;
    [CEReactions, Reflect] attribute Utf16DOMString coords;
    [CEReactions, Reflect] attribute Utf16DOMString shape;
    [CEReactions, Reflect] attribute Utf16DOMString download;
    [CEReactions, Reflect] attribute Utf16USVString ping;
    [CEReactions, Reflect] attribute Utf16DOMString rel;
    [SameObject, PutForwards=value] readonly attribute DOMTokenList relList;
    [CEReactions, Reflect=referrerpolicy, Enumerated=ReferrerPolicy] attribute Utf16DOMString referrerPolicy;

    // Obsolete
    [Reflect=nohref] attribute boolean noHref;

};

HTMLAreaElement includes HyperlinkElementUtils;
HTMLAreaElement includes HTMLHyperlinkElementUtils;
