// https://html.spec.whatwg.org/multipage/semantics.html#htmlembedelement
[Exposed=Window]
interface HTMLEmbedElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect, URL] attribute Utf16USVString src;
    [CEReactions, Reflect] attribute Utf16DOMString type;
    [CEReactions, Reflect] attribute Utf16DOMString width;
    [CEReactions, Reflect] attribute Utf16DOMString height;
    [FIXME] Document? getSVGDocument();

    // Obsolete
    [CEReactions, Reflect] attribute Utf16DOMString align;
    [CEReactions, Reflect] attribute Utf16DOMString name;

};
