// https://html.spec.whatwg.org/multipage/semantics.html#htmlfieldsetelement
[Exposed=Window]
interface HTMLFieldSetElement : HTMLElement {
    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute boolean disabled;
    readonly attribute HTMLFormElement? form;
    [CEReactions, Reflect] attribute Utf16DOMString name;

    readonly attribute Utf16DOMString type;

    [SameObject] readonly attribute HTMLCollection elements;

    readonly attribute boolean willValidate;
    [SameObject] readonly attribute ValidityState validity;
    readonly attribute Utf16DOMString validationMessage;
    boolean checkValidity();
    boolean reportValidity();
    undefined setCustomValidity(Utf16DOMString error);
};
