// https://html.spec.whatwg.org/multipage/links.html#htmlhyperlinkelementutils
interface mixin HTMLHyperlinkElementUtils {
    [CEReactions] stringifier attribute Utf16USVString href;
    [CEReactions, Reflect] attribute Utf16DOMString target;
};
