// https://html.spec.whatwg.org/multipage/semantics.html#htmlfontelement
[Exposed=Window]
interface HTMLFontElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, LegacyNullToEmptyString, Reflect] attribute Utf16DOMString color;
    [CEReactions, Reflect] attribute Utf16DOMString face;
    [CEReactions, Reflect] attribute Utf16DOMString size;

};
