// https://html.spec.whatwg.org/multipage/image-maps.html#htmlmapelement
[Exposed=Window]
interface HTMLMapElement : HTMLElement {

    [HTMLConstructor] constructor();

    [CEReactions, Reflect] attribute Utf16DOMString name;
    [SameObject] readonly attribute HTMLCollection areas;

};
