// https://html.spec.whatwg.org/multipage/links.html#hyperlinkelementutils
interface mixin HyperlinkElementUtils {
    readonly attribute USVString origin;
    [CEReactions] attribute USVString protocol;
    [CEReactions] attribute USVString username;
    [CEReactions] attribute USVString password;
    [CEReactions] attribute USVString host;
    [CEReactions] attribute USVString hostname;
    [CEReactions] attribute USVString port;
    [CEReactions] attribute USVString pathname;
    [CEReactions] attribute USVString search;
    [CEReactions] attribute USVString hash;
    
    [CEReactions, Reflect] attribute DOMString hreflang;
    [CEReactions, Reflect] attribute DOMString type;
};
