// https://html.spec.whatwg.org/multipage/nav-history-apis.html#location
[Exposed=Window]
interface Location { // but see also additional creation steps and overridden internal methods
    [LegacyUnforgeable] stringifier attribute Utf16USVString href;
    [LegacyUnforgeable] readonly attribute Utf16USVString origin;
    [LegacyUnforgeable] attribute Utf16USVString protocol;
    [LegacyUnforgeable] attribute Utf16USVString host;
    [LegacyUnforgeable] attribute Utf16USVString hostname;
    [LegacyUnforgeable] attribute Utf16USVString port;
    [LegacyUnforgeable] attribute Utf16USVString pathname;
    [LegacyUnforgeable] attribute Utf16USVString search;
    [LegacyUnforgeable] attribute Utf16USVString hash;

    [LegacyUnforgeable] undefined assign(Utf16USVString url);
    [LegacyUnforgeable] undefined replace(Utf16USVString url);
    [LegacyUnforgeable] undefined reload();

    // Intentionally not implemented at this stage due to https://github.com/whatwg/html/issues/1918
    // This is not currently implemented by Firefox due to the above, and only seems to be used by
    // ad tech on real sites.
    // [LegacyUnforgeable, SameObject] readonly attribute DOMStringList ancestorOrigins;
};
