// https://html.spec.whatwg.org/multipage/nav-history-apis.html#location
[Exposed=Window]
interface Location { // but see also additional creation steps and overridden internal methods
    [LegacyUnforgeable, NeedsCallerRealm] stringifier attribute USVString href;
    [LegacyUnforgeable, NeedsCallerRealm] readonly attribute USVString origin;
    [LegacyUnforgeable, NeedsCallerRealm] attribute USVString protocol;
    [LegacyUnforgeable, NeedsCallerRealm] attribute USVString host;
    [LegacyUnforgeable, NeedsCallerRealm] attribute USVString hostname;
    [LegacyUnforgeable, NeedsCallerRealm] attribute USVString port;
    [LegacyUnforgeable, NeedsCallerRealm] attribute USVString pathname;
    [LegacyUnforgeable, NeedsCallerRealm] attribute USVString search;
    [LegacyUnforgeable, NeedsCallerRealm] attribute USVString hash;

    [LegacyUnforgeable, NeedsCallerRealm] undefined assign(USVString url);
    [LegacyUnforgeable] undefined replace(USVString url);
    [LegacyUnforgeable] undefined reload();

    // Intentionally not implemented at this stage due to https://github.com/whatwg/html/issues/1918
    // This is not currently implemented by Firefox due to the above, and only seems to be used by
    // ad tech on real sites.
    // [LegacyUnforgeable, SameObject] readonly attribute DOMStringList ancestorOrigins;
};
