// https://html.spec.whatwg.org/multipage/nav-history-apis.html#navigationtype
[Exposed=Window]
interface NavigationHistoryEntry : EventTarget {
    readonly attribute Utf16USVString? url;
    readonly attribute Utf16DOMString key;
    readonly attribute Utf16DOMString id;
    readonly attribute long long index;
    readonly attribute boolean sameDocument;

    any getState();

    attribute EventHandler ondispose;
};
