[Exposed=Window]
interface NavigationActivation {
    readonly attribute NavigationHistoryEntry? from;
    readonly attribute NavigationHistoryEntry entry;
    readonly attribute NavigationType navigationType;
};
