// https://html.spec.whatwg.org/multipage/system-state.html#navigatorlanguage
interface mixin NavigatorLanguage {
    readonly attribute DOMString language;
    // FIXME: This is supposed always return the same object
    readonly attribute FrozenArray<DOMString> languages;
};
