[Exposed=Window]
interface PageSwapEvent : Event {
    constructor(DOMString type, optional PageSwapEventInit eventInitDict = {});
    readonly attribute NavigationActivation? activation;
    readonly attribute ViewTransition? viewTransition;
};

dictionary PageSwapEventInit : EventInit {
    NavigationActivation? activation = null;
    ViewTransition? viewTransition = null;
};
