// https://html.spec.whatwg.org/multipage/infrastructure.html#plugin
[Exposed=Window, LegacyUnenumerableNamedProperties]
interface Plugin {
    readonly attribute Utf16DOMString name;
    readonly attribute Utf16DOMString description;
    readonly attribute Utf16DOMString filename;
    readonly attribute unsigned long length;
    getter MimeType? item(unsigned long index);
    getter MimeType? namedItem([Utf16FlyString] Utf16DOMString name);
};
