#import <HTML/WorkerGlobalScope.idl>

// https://html.spec.whatwg.org/multipage/workers.html#sharedworkerglobalscope
[Global=(Worker,SharedWorker),Exposed=SharedWorker]
interface SharedWorkerGlobalScope : WorkerGlobalScope {
    [Replaceable] readonly attribute DOMString name;

    undefined close();

    attribute EventHandler onconnect;
};
