// https://html.spec.whatwg.org/multipage/webstorage.html#storage-2
[Exposed=Window]
interface Storage {

    readonly attribute unsigned long length;
    Utf16DOMString? key(unsigned long index);
    getter Utf16DOMString? getItem(Utf16DOMString key);
    setter undefined setItem(Utf16DOMString key, Utf16DOMString value);
    deleter undefined removeItem(Utf16DOMString key);
    undefined clear();

};
