// https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#submitevent
[Exposed=Window]
interface SubmitEvent : Event {
    constructor([Utf16FlyString] Utf16DOMString type, optional SubmitEventInit eventInitDict = {});

    readonly attribute HTMLElement? submitter;
};

dictionary SubmitEventInit : EventInit {
    HTMLElement? submitter = null;
};
