// https://html.spec.whatwg.org/multipage/media.html#timeranges
[Exposed=Window]
interface TimeRanges {
    readonly attribute unsigned long length;
    [NeedsCallerRealm] double start(unsigned long index);
    [NeedsCallerRealm] double end(unsigned long index);
};
