// https://html.spec.whatwg.org/multipage/interaction.html#toggleevent
[Exposed=Window]
interface ToggleEvent : Event {
    constructor([Utf16FlyString] Utf16DOMString type, optional ToggleEventInit eventInitDict = {});
    readonly attribute [Utf16FlyString] Utf16DOMString oldState;
    readonly attribute [Utf16FlyString] Utf16DOMString newState;
    readonly attribute Element? source;
};

dictionary ToggleEventInit : EventInit {
    [Utf16FlyString] Utf16DOMString oldState = "";
    [Utf16FlyString] Utf16DOMString newState = "";
    Element? source = null;
};
