// FIXME: Support VoidFunction in the IDL parser
callback VoidFunction = undefined ();

// https://whatpr.org/html/9893/webappapis.html#universalglobalscope-mixin
interface mixin UniversalGlobalScope {
    // base64 utility methods
    [NeedsCallerRealm] DOMString btoa(DOMString data);
    [NeedsCallerRealm] ByteString atob(DOMString data);

    // microtask queuing
    undefined queueMicrotask(VoidFunction callback);

    // structured cloning
    [NeedsCallerRealm] any structuredClone(any value, optional StructuredSerializeOptions options = {});
};
