// FIXME: Support VoidFunction in the IDL parser
callback VoidFunction = undefined ();

// https://whatpr.org/html/9893/webappapis.html#universalglobalscope-mixin
interface mixin UniversalGlobalScope {
    // base64 utility methods
    Utf16DOMString btoa(Utf16DOMString data);
    ByteString atob(Utf16DOMString data);

    // microtask queuing
    undefined queueMicrotask(VoidFunction callback);

    // structured cloning
    any structuredClone(any value, optional StructuredSerializeOptions options = {});
};
