/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

// Small build-time tool that prints struct field offsets as DSL constants.
// Compiled with the same flags as LibJS so layouts match exactly.

#include <AK/Format.h>
#include <AK/StringBase.h>
#include <AK/Utf16StringData.h>
#include <LibGC/HeapRegion.h>
#include <LibGC/PrimitiveStorage.h>
#include <LibJS/Bytecode/Builtins.h>
#include <LibJS/Bytecode/Executable.h>
#include <LibJS/Bytecode/PropertyNameIterator.h>
#include <LibJS/Bytecode/PutKind.h>
#include <LibJS/Runtime/Accessor.h>
#include <LibJS/Runtime/ArrayBuffer.h>
#include <LibJS/Runtime/DeclarativeEnvironment.h>
#include <LibJS/Runtime/ECMAScriptFunctionObject.h>
#include <LibJS/Runtime/ExecutionContext.h>
#include <LibJS/Runtime/FunctionObject.h>
#include <LibJS/Runtime/GlobalEnvironment.h>
#include <LibJS/Runtime/IndexedProperties.h>
#include <LibJS/Runtime/NativeFunction.h>
#include <LibJS/Runtime/Object.h>
#include <LibJS/Runtime/PrimitiveString.h>
#include <LibJS/Runtime/Realm.h>
#include <LibJS/Runtime/Shape.h>
#include <LibJS/Runtime/SharedFunctionInstanceData.h>
#include <LibJS/Runtime/TypedArray.h>
#include <LibJS/Runtime/VM.h>

#define EMIT_OFFSET(name, type, member) \
    outln("const " #name " = {}", offsetof(type, member))

#define EMIT_SIZEOF(name, type) \
    outln("const " #name " = {}", sizeof(type))

#define EMIT_FIELD(name, owner, field_name, flap_type, type, member, size, nullability, representation) \
    static_assert(sizeof(decltype(type::member)) == size);                                              \
    EMIT_OFFSET(name, type, member);                                                                    \
    outln("field " #owner "." #field_name " " #flap_type " " #name " " #nullability " " #representation)

#define EMIT_PAIRED_FIELD(name, owner, field_name, flap_type, type, member, size, representation, pair) \
    static_assert(sizeof(decltype(type::member)) == size);                                              \
    EMIT_OFFSET(name, type, member);                                                                    \
    outln("field " #owner "." #field_name " " #flap_type " " #name " nullable " #representation " " #pair)

#define EMIT_PAIRED_NONNULL_FIELD(name, owner, field_name, flap_type, type, member, size, representation, pair) \
    static_assert(sizeof(decltype(type::member)) == size);                                                      \
    EMIT_OFFSET(name, type, member);                                                                            \
    outln("field " #owner "." #field_name " " #flap_type " " #name " nonnull " #representation " " #pair)

// Offset of a Vector's outline element pointer, measured rather than assumed, since Flap addresses
// vector elements through it.
template<typename VectorType>
static size_t vector_data_offset()
{
    VectorType vector;
    return reinterpret_cast<uintptr_t>(&vector.m_metadata.outline_buffer) - reinterpret_cast<uintptr_t>(&vector);
}

// Offset of a Vector's element count, likewise measured rather than assumed.
template<typename VectorType>
static size_t vector_size_offset()
{
    VectorType vector;
    return reinterpret_cast<uintptr_t>(&vector.m_size) - reinterpret_cast<uintptr_t>(&vector);
}

int main()
{
    using namespace JS;
    using namespace JS::Bytecode;

    struct PrimitiveStringLayoutAccessor : PrimitiveString {
        using PrimitiveString::DeferredKind;
        using PrimitiveString::m_deferred_kind;
        using PrimitiveString::m_utf16_string;
    };
    outln("# Generated by GenerateLayout.cpp -- DO NOT EDIT\n");

    // Object layout
    outln("# Object layout");
    EMIT_FIELD(OBJECT_SHAPE, Object, shape, Shape, Object, m_shape, 8, nonnull, cell);
    EMIT_FIELD(OBJECT_NAMED_PROPERTIES, Object, named_properties, PropertyStorage, Object, m_named_properties, 8, nonnull, scalar);
    EMIT_FIELD(OBJECT_INDEXED_ELEMENTS, Object, indexed_elements, IndexedElements, Object, m_indexed_elements, 8, nullable, scalar);
    EMIT_FIELD(OBJECT_INDEXED_STORAGE_KIND, Object, indexed_storage_kind, u8, Object, m_indexed_storage_kind, 1, nullable, scalar);
    EMIT_FIELD(OBJECT_INDEXED_ARRAY_LIKE_SIZE, Object, indexed_array_like_size, u32, Object, m_indexed_array_like_size, 4, nullable, scalar);
    EMIT_SIZEOF(OBJECT_SIZE, Object);

    // Accessor layout
    outln("\n# Accessor layout");
    EMIT_FIELD(ACCESSOR_GETTER, Accessor, getter, FunctionObject, Accessor, m_getter, 8, nullable, cell);

    // Object flags
    outln("\n# Object flags");
    EMIT_FIELD(OBJECT_FLAGS, Object, flags, u16, Object, m_flags, 2, nullable, scalar);
    outln("const OBJECT_FLAG_HAS_MAGICAL_LENGTH = {}", Object::Flag::HasMagicalLengthProperty);
    outln("const OBJECT_FLAG_MAY_INTERFERE = {}", Object::Flag::MayInterfereWithIndexedPropertyAccess);
    outln("const OBJECT_FLAG_IS_TYPED_ARRAY = {}", Object::Flag::IsTypedArray);
    outln("const OBJECT_FLAG_IS_FUNCTION = {}", Object::Flag::IsFunction);
    outln("const OBJECT_FLAG_IS_ECMASCRIPT_FUNCTION_OBJECT = {}", Object::Flag::IsECMAScriptFunctionObject);
    outln("const OBJECT_FLAG_IS_RAW_NATIVE_FUNCTION = {}", Object::Flag::IsRawNativeFunction);
    outln("const OBJECT_FLAG_IS_DIRECT_GETTER_FUNCTION = {}", Object::Flag::IsDirectGetterFunction);
    outln("const OBJECT_FLAG_IS_GLOBAL_OBJECT = {}", Object::Flag::IsGlobalObject);

    // Shape layout
    outln("\n# Shape layout");
    EMIT_FIELD(SHAPE_REALM, Shape, realm, Realm, Shape, m_realm, 8, nonnull, cell);
    EMIT_OFFSET(SHAPE_PROTOTYPE, Shape, m_prototype);
    EMIT_FIELD(SHAPE_DICTIONARY_GENERATION, Shape, dictionary_generation, u32, Shape, m_dictionary_generation, 4, nullable, scalar);
    EMIT_SIZEOF(SHAPE_SIZE, Shape);

    // PropertyLookupCache layout
    outln("\n# PropertyLookupCache layout");
    EMIT_OFFSET(PROPERTY_LOOKUP_CACHE_DATA, PropertyLookupCache, m_data);
    outln("const PROPERTY_LOOKUP_CACHE_DATA_POINTER_MASK = 0x{:X}", ~PropertyLookupCache::cache_data_tag_mask);
    EMIT_SIZEOF(PROPERTY_LOOKUP_CACHE_SIZE, PropertyLookupCache);

    // PropertyLookupCache::Entry layout
    outln("\n# PropertyLookupCache::Entry layout");
    EMIT_FIELD(PROPERTY_LOOKUP_CACHE_ENTRY_TYPE, PropertyLookupCache, entry_type, u32, PropertyLookupCache::Entry, type, 4, nullable, scalar);
    outln("const PROPERTY_LOOKUP_CACHE_ENTRY_TYPE_GET_MISSING_PROPERTY = {}", to_underlying(PropertyLookupCache::Entry::Type::GetMissingProperty));
    EMIT_PAIRED_FIELD(PROPERTY_LOOKUP_CACHE_ENTRY_PROPERTY_OFFSET, PropertyLookupCache, property_offset, u32, PropertyLookupCache::Entry, property_offset, 4, scalar, cache_details);
    EMIT_PAIRED_FIELD(PROPERTY_LOOKUP_CACHE_ENTRY_DICTIONARY_GENERATION, PropertyLookupCache, shape_dictionary_generation, u32, PropertyLookupCache::Entry, shape_dictionary_generation, 4, scalar, cache_details);
    EMIT_FIELD(PROPERTY_LOOKUP_CACHE_ENTRY_DIRECT_GETTER_VALIDATED, PropertyLookupCache, direct_getter_validated, bool, PropertyLookupCache::Entry, direct_getter_validated, 1, nullable, scalar);
    EMIT_OFFSET(PROPERTY_LOOKUP_CACHE_ENTRY_FROM_SHAPE, PropertyLookupCache::Entry, from_shape);
    EMIT_PAIRED_FIELD(PROPERTY_LOOKUP_CACHE_ENTRY_SHAPE, PropertyLookupCache, shape, Shape, PropertyLookupCache::Entry, shape, 8, cell, cache_target);
    EMIT_PAIRED_FIELD(PROPERTY_LOOKUP_CACHE_ENTRY_PROTOTYPE, PropertyLookupCache, prototype, Object, PropertyLookupCache::Entry, prototype, 8, cell, cache_target);
    EMIT_FIELD(PROPERTY_LOOKUP_CACHE_ENTRY_PROTOTYPE_CHAIN_VALIDITY, PropertyLookupCache, prototype_chain_validity, PrototypeChainValidity, PropertyLookupCache::Entry, prototype_chain_validity, 8, nullable, cell);
    EMIT_SIZEOF(PROPERTY_LOOKUP_CACHE_ENTRY_SIZE, PropertyLookupCache::Entry);

    // ObjectPropertyIteratorCacheData layout
    outln("\n# ObjectPropertyIteratorCacheData layout");
    EMIT_OFFSET(OBJECT_PROPERTY_ITERATOR_CACHE_DATA_PROPERTIES, ObjectPropertyIteratorCacheData, m_properties);
    EMIT_OFFSET(OBJECT_PROPERTY_ITERATOR_CACHE_DATA_PROPERTY_VALUES, ObjectPropertyIteratorCacheData, m_property_values);
    EMIT_FIELD(OBJECT_PROPERTY_ITERATOR_CACHE_DATA_SHAPE, ObjectPropertyIteratorCacheData, shape, Shape, ObjectPropertyIteratorCacheData, m_shape, 8, nonnull, cell);
    EMIT_FIELD(OBJECT_PROPERTY_ITERATOR_CACHE_DATA_PROTOTYPE_CHAIN_VALIDITY, ObjectPropertyIteratorCacheData, prototype_chain_validity, PrototypeChainValidity, ObjectPropertyIteratorCacheData, m_prototype_chain_validity, 8, nullable, cell);
    EMIT_FIELD(OBJECT_PROPERTY_ITERATOR_CACHE_DATA_INDEXED_PROPERTY_COUNT, ObjectPropertyIteratorCacheData, indexed_property_count, u32, ObjectPropertyIteratorCacheData, m_indexed_property_count, 4, nullable, scalar);
    EMIT_FIELD(OBJECT_PROPERTY_ITERATOR_CACHE_DATA_SHAPE_DICTIONARY_GENERATION, ObjectPropertyIteratorCacheData, shape_dictionary_generation, u32, ObjectPropertyIteratorCacheData, m_shape_dictionary_generation, 4, nullable, scalar);
    EMIT_FIELD(OBJECT_PROPERTY_ITERATOR_CACHE_DATA_FAST_PATH, ObjectPropertyIteratorCacheData, fast_path, u8, ObjectPropertyIteratorCacheData, m_fast_path, 1, nullable, scalar);

    // ObjectPropertyIteratorCache layout
    outln("\n# ObjectPropertyIteratorCache layout");
    EMIT_FIELD(OBJECT_PROPERTY_ITERATOR_CACHE_DATA_PTR, ObjectPropertyIteratorCache, data, ObjectPropertyIteratorCacheData, ObjectPropertyIteratorCache, data, 8, nullable, cell);
    EMIT_FIELD(OBJECT_PROPERTY_ITERATOR_CACHE_REUSABLE_PROPERTY_NAME_ITERATOR, ObjectPropertyIteratorCache, reusable_property_name_iterator, Object, ObjectPropertyIteratorCache, reusable_property_name_iterator, 8, nullable, cell);

    // PropertyNameIterator layout
    outln("\n# PropertyNameIterator layout");
    EMIT_FIELD(PROPERTY_NAME_ITERATOR_OBJECT, PropertyNameIterator, object, Object, PropertyNameIterator, m_object, 8, nullable, cell);
    EMIT_PAIRED_FIELD(PROPERTY_NAME_ITERATOR_PROPERTY_CACHE, PropertyNameIterator, property_cache, ObjectPropertyIteratorCacheData, PropertyNameIterator, m_property_cache, 8, cell, cache_and_shape);
    EMIT_PAIRED_FIELD(PROPERTY_NAME_ITERATOR_SHAPE, PropertyNameIterator, shape, Shape, PropertyNameIterator, m_shape, 8, cell, cache_and_shape);
    EMIT_FIELD(PROPERTY_NAME_ITERATOR_PROTOTYPE_CHAIN_VALIDITY, PropertyNameIterator, prototype_chain_validity, PrototypeChainValidity, PropertyNameIterator, m_prototype_chain_validity, 8, nullable, cell);
    EMIT_FIELD(PROPERTY_NAME_ITERATOR_ITERATOR_CACHE_SLOT, PropertyNameIterator, iterator_cache_slot, ObjectPropertyIteratorCache, PropertyNameIterator, m_iterator_cache_slot, 8, nullable, scalar);
    EMIT_PAIRED_FIELD(PROPERTY_NAME_ITERATOR_INDEXED_PROPERTY_COUNT, PropertyNameIterator, indexed_property_count, u32, PropertyNameIterator, m_indexed_property_count, 4, scalar, indexed_progress);
    EMIT_PAIRED_FIELD(PROPERTY_NAME_ITERATOR_NEXT_INDEXED_PROPERTY, PropertyNameIterator, next_indexed_property, u32, PropertyNameIterator, m_next_indexed_property, 4, scalar, indexed_progress);
    EMIT_FIELD(PROPERTY_NAME_ITERATOR_NEXT_PROPERTY, PropertyNameIterator, next_property, u64, PropertyNameIterator, m_next_property, 8, nullable, scalar);
    EMIT_FIELD(PROPERTY_NAME_ITERATOR_SHAPE_IS_DICTIONARY, PropertyNameIterator, shape_is_dictionary, bool, PropertyNameIterator, m_shape_is_dictionary, 1, nullable, scalar);
    EMIT_FIELD(PROPERTY_NAME_ITERATOR_SHAPE_DICTIONARY_GENERATION, PropertyNameIterator, shape_dictionary_generation, u32, PropertyNameIterator, m_shape_dictionary_generation, 4, nullable, scalar);
    EMIT_FIELD(PROPERTY_NAME_ITERATOR_FAST_PATH, PropertyNameIterator, fast_path, u8, PropertyNameIterator, m_fast_path, 1, nullable, scalar);

    // Executable layout
    outln("\n# Executable layout");
    EMIT_OFFSET(EXECUTABLE_CONSTANTS, Executable, constants);
    EMIT_OFFSET(EXECUTABLE_PROPERTY_LOOKUP_CACHES, Executable, property_lookup_caches);
    EMIT_OFFSET(EXECUTABLE_GLOBAL_VARIABLE_CACHES, Executable, global_variable_caches);
    EMIT_OFFSET(EXECUTABLE_ENVIRONMENT_COORDINATE_CACHES, Executable, environment_coordinate_caches);
    EMIT_PAIRED_FIELD(EXECUTABLE_REGISTERS_AND_LOCALS_COUNT, Executable, registers_and_locals_count, u32, Executable, registers_and_locals_count, 4, scalar, slot_counts);
    EMIT_PAIRED_FIELD(EXECUTABLE_REGISTERS_AND_LOCALS_AND_CONSTANTS_COUNT, Executable, registers_and_locals_and_constants_count, u32, Executable, registers_and_locals_and_constants_count, 4, scalar, slot_counts);
    EMIT_PAIRED_FIELD(EXECUTABLE_ASM_CONSTANTS_SIZE, Executable, asm_constants_size, u64, Executable, asm_constants_size, 8, scalar, constants);
    EMIT_PAIRED_FIELD(EXECUTABLE_ASM_CONSTANTS_DATA, Executable, asm_constants_data, Sequence<Value>, Executable, asm_constants_data, 8, scalar, constants);

    // ExecutionContext layout
    outln("\n# ExecutionContext layout");
    VERIFY(alignof(ExecutionContext) == sizeof(Value));
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_FUNCTION, ExecutionContext, function, Object, ExecutionContext, function, 8, cell, function_and_realm);
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_REALM, ExecutionContext, realm, Realm, ExecutionContext, realm, 8, cell, function_and_realm);
    EMIT_FIELD(EXECUTION_CONTEXT_SCRIPT_OR_MODULE, ExecutionContext, script_or_module, ScriptOrModule, ExecutionContext, script_or_module, 16, nullable, scalar);
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_LEXICAL_ENVIRONMENT, ExecutionContext, lexical_environment, Environment, ExecutionContext, lexical_environment, 8, cell, environments);
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_VARIABLE_ENVIRONMENT, ExecutionContext, variable_environment, Environment, ExecutionContext, variable_environment, 8, cell, environments);
    EMIT_FIELD(EXECUTION_CONTEXT_PRIVATE_ENVIRONMENT, ExecutionContext, private_environment, PrivateEnvironment, ExecutionContext, private_environment, 8, nullable, cell);
    EMIT_FIELD(EXECUTION_CONTEXT_SKIP_WHEN_DETERMINING_INCUMBENT_COUNTER, ExecutionContext, skip_when_determining_incumbent_counter, u32, ExecutionContext, skip_when_determining_incumbent_counter, 4, nullable, scalar);
    EMIT_FIELD(EXECUTION_CONTEXT_YIELD_CONTINUATION, ExecutionContext, yield_continuation, u32, ExecutionContext, yield_continuation, 4, nullable, scalar);
    EMIT_FIELD(EXECUTION_CONTEXT_YIELD_IS_AWAIT, ExecutionContext, yield_is_await, bool, ExecutionContext, yield_is_await, 1, nullable, scalar);
    EMIT_FIELD(EXECUTION_CONTEXT_YIELD_VALUE_IS_ITERATOR_RESULT, ExecutionContext, yield_value_is_iterator_result, bool, ExecutionContext, yield_value_is_iterator_result, 1, nullable, scalar);
    EMIT_FIELD(EXECUTION_CONTEXT_CALLER_IS_CONSTRUCT, ExecutionContext, caller_is_construct, bool, ExecutionContext, caller_is_construct, 1, nullable, scalar);
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_THIS_VALUE, ExecutionContext, this_value, Value, ExecutionContext, this_value, 8, scalar, this_and_executable);
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_EXECUTABLE, ExecutionContext, executable, Executable, ExecutionContext, executable, 8, cell, this_and_executable);
    EMIT_FIELD(EXECUTION_CONTEXT_CALLER_FRAME, ExecutionContext, caller_frame, ExecutionContext, ExecutionContext, caller_frame, 8, nullable, scalar);
    EMIT_FIELD(EXECUTION_CONTEXT_PASSED_ARGUMENT_COUNT, ExecutionContext, passed_argument_count, u32, ExecutionContext, passed_argument_count, 4, nullable, scalar);
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_CALLER_RETURN_PC, ExecutionContext, caller_return_pc, u32, ExecutionContext, caller_return_pc, 4, scalar, caller_return);
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_CALLER_DST_RAW, ExecutionContext, caller_dst_raw, u32, ExecutionContext, caller_dst_raw, 4, scalar, caller_return);
    EMIT_FIELD(EXECUTION_CONTEXT_PROGRAM_COUNTER, ExecutionContext, program_counter, u32, ExecutionContext, program_counter, 4, nullable, scalar);
    EMIT_FIELD(EXECUTION_CONTEXT_FRAME_ID, ExecutionContext, frame_id, u64, ExecutionContext, frame_id, 8, nullable, scalar);
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_REGISTERS_AND_CONSTANTS_AND_LOCALS_AND_ARGUMENTS_COUNT, ExecutionContext, slot_count, u32, ExecutionContext, registers_and_constants_and_locals_and_arguments_count, 4, scalar, counts);
    EMIT_PAIRED_FIELD(EXECUTION_CONTEXT_ARGUMENT_COUNT, ExecutionContext, argument_count, u32, ExecutionContext, argument_count, 4, scalar, counts);
    EMIT_SIZEOF(SIZEOF_EXECUTION_CONTEXT, ExecutionContext);
    outln("field ExecutionContext.slots Sequence<Value> SIZEOF_EXECUTION_CONTEXT embedded scalar");
    outln("const EXECUTION_CONTEXT_ACCUMULATOR = {}", sizeof(ExecutionContext) + static_cast<size_t>(Register::accumulator().index()) * sizeof(Value));
    outln("const EXECUTION_CONTEXT_EXCEPTION = {}", sizeof(ExecutionContext) + static_cast<size_t>(Register::exception().index()) * sizeof(Value));
    outln("const EXECUTION_CONTEXT_THIS_VALUE_REGISTER = {}", sizeof(ExecutionContext) + static_cast<size_t>(Register::this_value().index()) * sizeof(Value));
    outln("const EXECUTION_CONTEXT_RETURN_VALUE = {}", sizeof(ExecutionContext) + static_cast<size_t>(Register::return_value().index()) * sizeof(Value));
    outln("const EXECUTION_CONTEXT_SAVED_LEXICAL_ENVIRONMENT = {}", sizeof(ExecutionContext) + static_cast<size_t>(Register::saved_lexical_environment().index()) * sizeof(Value));
    outln("field ExecutionContext.accumulator Value EXECUTION_CONTEXT_ACCUMULATOR nullable scalar accumulator_and_exception");
    outln("field ExecutionContext.exception Value EXECUTION_CONTEXT_EXCEPTION nullable scalar accumulator_and_exception pinned values EXCEPTION_REG_OFFSET");
    outln("field ExecutionContext.this_value_register Value EXECUTION_CONTEXT_THIS_VALUE_REGISTER nullable scalar pinned values THIS_VALUE_REG_OFFSET");
    outln("field ExecutionContext.return_value Value EXECUTION_CONTEXT_RETURN_VALUE nullable scalar return_and_saved_environment");
    outln("field ExecutionContext.saved_lexical_environment Value EXECUTION_CONTEXT_SAVED_LEXICAL_ENVIRONMENT nullable scalar return_and_saved_environment");
    outln("const ALIGNOF_EXECUTION_CONTEXT = {}", alignof(ExecutionContext));
    outln("const EXECUTION_CONTEXT_NO_YIELD_CONTINUATION = {}", static_cast<u32>(ExecutionContext::no_yield_continuation));
    outln("const SIZEOF_SCRIPT_OR_MODULE = {}", sizeof(ScriptOrModule));
    outln("const SIZEOF_VALUE = {}", sizeof(Value));

    // InterpreterStack layout
    outln("\n# InterpreterStack layout");
    EMIT_OFFSET(INTERPRETER_STACK_LIMIT, InterpreterStack, m_limit);
    EMIT_OFFSET(INTERPRETER_STACK_TOP, InterpreterStack, m_top);
    EMIT_OFFSET(INTERPRETER_STACK_NEXT_FRAME_ID, InterpreterStack, m_next_frame_id);

    // Realm layout
    outln("\n# Realm layout");
    EMIT_FIELD(REALM_GLOBAL_ENVIRONMENT, Realm, global_environment, GlobalEnvironment, Realm, m_global_environment, 8, nonnull, cell);
    EMIT_PAIRED_FIELD(REALM_GLOBAL_OBJECT, Realm, global_object, Object, Realm, m_global_object, 8, cell, global_state);
    EMIT_PAIRED_FIELD(REALM_GLOBAL_DECLARATIVE_ENVIRONMENT, Realm, global_declarative_environment, DeclarativeEnvironment, Realm, m_global_declarative_environment, 8, cell, global_state);

    // VM layout
    outln("\n# VM layout");
    EMIT_OFFSET(VM_RUNNING_EXECUTION_CONTEXT, VM, m_running_execution_context);
    EMIT_OFFSET(VM_INTERPRETER_STACK, VM, m_interpreter_stack);
    EMIT_OFFSET(VM_STACK_INFO, VM, m_stack_info);
    EMIT_OFFSET(VM_EXECUTION_GENERATION, VM, m_execution_generation);
    EMIT_OFFSET(VM_PRIMITIVE_STORAGE_CAGE_BASE, VM, m_primitive_storage_cage_base);
    EMIT_OFFSET(VM_HEAP_REGION_BASE, VM, m_heap_region_base);
    EMIT_OFFSET(VM_NATIVE_FUNCTION_TABLE_DATA, VM, m_native_function_table_data);
    EMIT_OFFSET(VM_BREAKPOINT_CONTROLLER, VM, m_debugger);
    outln("field VM.primitive_storage_cage_base u64 VM_PRIMITIVE_STORAGE_CAGE_BASE nonnull scalar");
    outln("field VM.heap_region_base u64 VM_HEAP_REGION_BASE nonnull scalar");
    outln("field VM.native_function_table Sequence<NativeFunctionTableEntry> VM_NATIVE_FUNCTION_TABLE_DATA nonnull scalar");
    outln("const VM_INTERPRETER_STACK_TOP = {}", offsetof(VM, m_interpreter_stack) + offsetof(InterpreterStack, m_top));
    outln("const VM_INTERPRETER_STACK_LIMIT = {}", offsetof(VM, m_interpreter_stack) + offsetof(InterpreterStack, m_limit));
    outln("const VM_INTERPRETER_STACK_NEXT_FRAME_ID = {}", offsetof(VM, m_interpreter_stack) + offsetof(InterpreterStack, m_next_frame_id));
    outln("const VM_STACK_INFO_BASE = {}", offsetof(VM, m_stack_info) + offsetof(StackInfo, m_base));
    outln("field VM.running_execution_context ExecutionContext VM_RUNNING_EXECUTION_CONTEXT nullable scalar");
    outln("field VM.interpreter_stack_top u64 VM_INTERPRETER_STACK_TOP nonnull scalar interpreter_stack_bounds");
    outln("field VM.interpreter_stack_limit u64 VM_INTERPRETER_STACK_LIMIT nonnull scalar interpreter_stack_bounds");
    outln("field VM.interpreter_stack_next_frame_id u64 VM_INTERPRETER_STACK_NEXT_FRAME_ID nonnull scalar");
    outln("field VM.stack_base u64 VM_STACK_INFO_BASE nullable scalar");
#if defined(HAS_ADDRESS_SANITIZER)
    outln("const VM_STACK_SPACE_LIMIT = {}", 96 * KiB);
#else
    outln("const VM_STACK_SPACE_LIMIT = {}", 32 * KiB);
#endif

    // StackInfo layout
    outln("\n# StackInfo layout");
    EMIT_OFFSET(STACK_INFO_BASE, StackInfo, m_base);

    // IndexedStorageKind enum values
    outln("\n# IndexedStorageKind enum values");
    outln("const INDEXED_STORAGE_KIND_NONE = {}", static_cast<u8>(IndexedStorageKind::None));
    outln("const INDEXED_STORAGE_KIND_PACKED = {}", static_cast<u8>(IndexedStorageKind::Packed));
    outln("const INDEXED_STORAGE_KIND_HOLEY = {}", static_cast<u8>(IndexedStorageKind::Holey));
    outln("const INDEXED_STORAGE_KIND_DICTIONARY = {}", static_cast<u8>(IndexedStorageKind::Dictionary));

    // ObjectPropertyIteratorFastPath enum values
    outln("\n# ObjectPropertyIteratorFastPath enum values");
    outln("const OBJECT_PROPERTY_ITERATOR_FAST_PATH_NONE = {}", static_cast<u8>(ObjectPropertyIteratorFastPath::None));
    outln("const OBJECT_PROPERTY_ITERATOR_FAST_PATH_PLAIN_NAMED = {}", static_cast<u8>(ObjectPropertyIteratorFastPath::PlainNamed));
    outln("const OBJECT_PROPERTY_ITERATOR_FAST_PATH_PACKED_INDEXED = {}", static_cast<u8>(ObjectPropertyIteratorFastPath::PackedIndexed));

    // Vector<Value> layout (used for bytecode)
    outln("\n# Vector<Value> layout");
    {
        Vector<Value> v;
        auto base = reinterpret_cast<uintptr_t>(&v);
        auto vec_data = vector_data_offset<Vector<Value>>();
        auto vec_size = reinterpret_cast<uintptr_t>(&v.m_size) - base;
        auto vec_capacity = reinterpret_cast<uintptr_t>(&v.m_capacity) - base;
        outln("const VECTOR_DATA = {}", vec_data);
        outln("const VECTOR_SIZE = {}", vec_size);
        outln("const INDEXED_ELEMENTS_CAPACITY = {}", static_cast<ptrdiff_t>(vec_capacity) - static_cast<ptrdiff_t>(vec_data));
        outln("field IndexedElements.capacity u32 INDEXED_ELEMENTS_CAPACITY nullable scalar");

        // Composite offset for Executable.bytecode data pointer
        outln("const EXECUTABLE_BYTECODE_DATA = {}", offsetof(Executable, bytecode) + InstructionStream::data_member_offset());
        outln("field Executable.bytecode_data u64 EXECUTABLE_BYTECODE_DATA nonnull scalar");
        outln("const EXECUTABLE_PROPERTY_LOOKUP_CACHES_DATA = {}", offsetof(Executable, property_lookup_caches) + vec_data);
        static_assert(sizeof(PropertyLookupCache) == 8);
        outln("field Executable.property_lookup_caches PropertyLookupCaches EXECUTABLE_PROPERTY_LOOKUP_CACHES_DATA nonnull scalar");
        outln("const EXECUTABLE_GLOBAL_VARIABLE_CACHES_DATA = {}", offsetof(Executable, global_variable_caches) + vec_data);
        outln("field Executable.global_variable_caches GlobalVariableCaches EXECUTABLE_GLOBAL_VARIABLE_CACHES_DATA nonnull scalar");
        outln("const EXECUTABLE_ENVIRONMENT_COORDINATE_CACHES_DATA = {}", offsetof(Executable, environment_coordinate_caches) + vec_data);
        outln("field Executable.environment_coordinate_caches Sequence<EnvironmentCoordinateEntry> EXECUTABLE_ENVIRONMENT_COORDINATE_CACHES_DATA nullable scalar");
        outln("const EXECUTABLE_CONSTANTS_DATA = {}", offsetof(Executable, constants) + vec_data);
        outln("const EXECUTABLE_CONSTANTS_SIZE = {}", offsetof(Executable, constants) + vec_size);
        outln("const OBJECT_PROPERTY_ITERATOR_CACHE_DATA_PROPERTY_VALUES_DATA = {}", offsetof(ObjectPropertyIteratorCacheData, m_property_values) + vec_data);
        outln("const OBJECT_PROPERTY_ITERATOR_CACHE_DATA_PROPERTY_VALUES_SIZE = {}", offsetof(ObjectPropertyIteratorCacheData, m_property_values) + vec_size);
        outln("field ObjectPropertyIteratorCacheData.property_values Sequence<Value> OBJECT_PROPERTY_ITERATOR_CACHE_DATA_PROPERTY_VALUES_DATA nullable scalar");
        outln("field ObjectPropertyIteratorCacheData.property_value_count u64 OBJECT_PROPERTY_ITERATOR_CACHE_DATA_PROPERTY_VALUES_SIZE nullable scalar");
    }

    // PutKind enum
    outln("\n# PutKind enum");
    outln("const PUT_KIND_NORMAL = {}", static_cast<u8>(JS::Bytecode::PutKind::Normal));

    // PrototypeChainValidity layout
    outln("\n# PrototypeChainValidity layout");
    EMIT_FIELD(PROTOTYPE_CHAIN_VALIDITY_VALID, PrototypeChainValidity, valid, bool, PrototypeChainValidity, m_valid, 1, nonnull, scalar);

    // DeclarativeEnvironment layout
    outln("\n# DeclarativeEnvironment layout");
    EMIT_FIELD(DECLARATIVE_ENVIRONMENT_RARE_DATA, DeclarativeEnvironment, rare_data, DeclarativeEnvironmentRareData, DeclarativeEnvironment, m_rare_data, 8, nullable, scalar);
    EMIT_FIELD(DECLARATIVE_ENVIRONMENT_SERIAL, DeclarativeEnvironment, serial_number, u64, DeclarativeEnvironment, m_environment_serial_number, 8, nullable, scalar);

    // GlobalVariableCache layout
    outln("\n# GlobalVariableCache layout");
    EMIT_OFFSET(GLOBAL_VARIABLE_CACHE_ENTRY, GlobalVariableCache, entry);
    EMIT_OFFSET(GLOBAL_VARIABLE_CACHE_ENVIRONMENT_SERIAL, GlobalVariableCache, environment_serial_number);
    EMIT_OFFSET(GLOBAL_VARIABLE_CACHE_ENVIRONMENT_BINDING_INDEX, GlobalVariableCache, environment_binding_index);
    EMIT_OFFSET(GLOBAL_VARIABLE_CACHE_HAS_ENVIRONMENT_BINDING, GlobalVariableCache, has_environment_binding_index);
    EMIT_OFFSET(GLOBAL_VARIABLE_CACHE_IN_MODULE_ENVIRONMENT, GlobalVariableCache, in_module_environment);
    EMIT_SIZEOF(GLOBAL_VARIABLE_CACHE_SIZE, GlobalVariableCache);
    outln("const GLOBAL_VARIABLE_CACHE_ENTRY_PROPERTY_OFFSET = {}", offsetof(GlobalVariableCache, entry) + offsetof(PropertyLookupCache::Entry, property_offset));
    outln("const GLOBAL_VARIABLE_CACHE_ENTRY_DICTIONARY_GENERATION = {}", offsetof(GlobalVariableCache, entry) + offsetof(PropertyLookupCache::Entry, shape_dictionary_generation));
    outln("const GLOBAL_VARIABLE_CACHE_ENTRY_SHAPE = {}", offsetof(GlobalVariableCache, entry) + offsetof(PropertyLookupCache::Entry, shape));
    outln("field GlobalVariableCache.property_offset u32 GLOBAL_VARIABLE_CACHE_ENTRY_PROPERTY_OFFSET nullable scalar global_cache_details stride GLOBAL_VARIABLE_CACHE_SIZE");
    outln("field GlobalVariableCache.shape_dictionary_generation u32 GLOBAL_VARIABLE_CACHE_ENTRY_DICTIONARY_GENERATION nullable scalar global_cache_details");
    outln("field GlobalVariableCache.shape Shape GLOBAL_VARIABLE_CACHE_ENTRY_SHAPE nullable cell");
    outln("field GlobalVariableCache.environment_serial_number u64 GLOBAL_VARIABLE_CACHE_ENVIRONMENT_SERIAL nullable scalar");
    outln("field GlobalVariableCache.environment_binding_index u32 GLOBAL_VARIABLE_CACHE_ENVIRONMENT_BINDING_INDEX nullable scalar");
    outln("field GlobalVariableCache.has_environment_binding_index u8 GLOBAL_VARIABLE_CACHE_HAS_ENVIRONMENT_BINDING nullable scalar");
    outln("field GlobalVariableCache.in_module_environment u8 GLOBAL_VARIABLE_CACHE_IN_MODULE_ENVIRONMENT nullable scalar");

    // Builtin enum values
    outln("\n# Builtin enum values");
    outln("const BUILTIN_MATH_ABS = {}", static_cast<u8>(Bytecode::Builtin::MathAbs));
    outln("const BUILTIN_MATH_FLOOR = {}", static_cast<u8>(Bytecode::Builtin::MathFloor));
    outln("const BUILTIN_MATH_CEIL = {}", static_cast<u8>(Bytecode::Builtin::MathCeil));
    outln("const BUILTIN_MATH_ROUND = {}", static_cast<u8>(Bytecode::Builtin::MathRound));
    outln("const BUILTIN_MATH_SQRT = {}", static_cast<u8>(Bytecode::Builtin::MathSqrt));
    outln("const BUILTIN_MATH_EXP = {}", static_cast<u8>(Bytecode::Builtin::MathExp));
    outln("const BUILTIN_STRING_FROM_CHAR_CODE = {}", static_cast<u8>(Bytecode::Builtin::StringFromCharCode));
    outln("const BUILTIN_STRING_PROTOTYPE_CHAR_CODE_AT = {}", static_cast<u8>(Bytecode::Builtin::StringPrototypeCharCodeAt));
    outln("const BUILTIN_STRING_PROTOTYPE_CHAR_AT = {}", static_cast<u8>(Bytecode::Builtin::StringPrototypeCharAt));

    // FunctionObject layout
    outln("\n# FunctionObject layout");
    EMIT_OFFSET(FUNCTION_OBJECT_BUILTIN, FunctionObject, m_builtin);
    {
        // Optional<Builtin> has a value byte and a has_value byte.
        auto base = offsetof(FunctionObject, m_builtin);
        // Optional<Builtin> stores value at offset 0, has_value bool at offset 1.
        // Verify this assumption at compile time:
        Optional<Bytecode::Builtin> opt_test { Bytecode::Builtin::MathFloor };
        auto const* raw = reinterpret_cast<u8 const*>(&opt_test);
        VERIFY(raw[0] == static_cast<u8>(Bytecode::Builtin::MathFloor));
        VERIFY(raw[1] == 1); // has_value
        outln("const FUNCTION_OBJECT_BUILTIN_VALUE = {}", base);
        outln("const FUNCTION_OBJECT_BUILTIN_HAS_VALUE = {}", base + 1);
        outln("field FunctionObject.builtin u8 FUNCTION_OBJECT_BUILTIN_VALUE nullable scalar");
        outln("field FunctionObject.has_builtin bool FUNCTION_OBJECT_BUILTIN_HAS_VALUE nullable scalar");
    }

    // RawNativeFunction layout
    outln("\n# RawNativeFunction layout");
    EMIT_FIELD(RAW_NATIVE_FUNCTION_NATIVE_FUNCTION_INDEX, RawNativeFunction, native_function_index, u32, RawNativeFunction, m_native_function_index, 4, nullable, scalar);
    static_assert(sizeof(NativeFunctionTableEntry::function) == 8);
    static_assert(sizeof(NativeFunctionTableEntry::type) == 4);
    EMIT_OFFSET(NATIVE_FUNCTION_TABLE_ENTRY_FUNCTION, NativeFunctionTableEntry, function);
    EMIT_OFFSET(NATIVE_FUNCTION_TABLE_ENTRY_TYPE, NativeFunctionTableEntry, type);
    outln("const NATIVE_FUNCTION_TYPE_COUNT = {}", to_underlying(NativeFunctionType::RawNativeFunction) + 1);
    outln("field NativeFunctionTableEntry.function u64 NATIVE_FUNCTION_TABLE_ENTRY_FUNCTION nonnull scalar native_function_table_entry stride {}", sizeof(NativeFunctionTableEntry));
    outln("field NativeFunctionTableEntry.type u32 NATIVE_FUNCTION_TABLE_ENTRY_TYPE nullable scalar native_function_table_entry");

    // DirectGetterFunction layout
    outln("\n# DirectGetterFunction layout");
    EMIT_FIELD(DIRECT_GETTER_FUNCTION_WRAPPER_IMPLEMENTATION_WORD_OFFSET, DirectGetterFunction, wrapper_implementation_word_offset, u32, DirectGetterFunction, m_wrapper_implementation_word_offset, 4, nullable, scalar);
    EMIT_FIELD(DIRECT_GETTER_FUNCTION_IMPLEMENTATION_VALUE_WORD_OFFSET, DirectGetterFunction, implementation_value_word_offset, u32, DirectGetterFunction, m_implementation_value_word_offset, 4, nullable, scalar);
    EMIT_FIELD(DIRECT_GETTER_FUNCTION_MAIN_WORLD_WRAPPER_WORD_OFFSET, DirectGetterFunction, main_world_wrapper_word_offset, u32, DirectGetterFunction, m_main_world_wrapper_word_offset, 4, nullable, scalar);
    EMIT_FIELD(DIRECT_GETTER_FUNCTION_WEAK_IMPL_VALUE_WORD_OFFSET, DirectGetterFunction, weak_impl_value_word_offset, u32, DirectGetterFunction, m_weak_impl_value_word_offset, 4, nullable, scalar);

    // ECMAScriptFunctionObject layout
    outln("\n# ECMAScriptFunctionObject layout");
    EMIT_FIELD(ECMASCRIPT_FUNCTION_OBJECT_SHARED_DATA, ECMAScriptFunctionObject, shared_data, SharedFunctionInstanceData, ECMAScriptFunctionObject, m_shared_data, 8, nonnull, cell);
    EMIT_PAIRED_FIELD(ECMASCRIPT_FUNCTION_OBJECT_ENVIRONMENT, ECMAScriptFunctionObject, environment, Environment, ECMAScriptFunctionObject, m_environment, 8, cell, environment_state);
    EMIT_PAIRED_FIELD(ECMASCRIPT_FUNCTION_OBJECT_PRIVATE_ENVIRONMENT, ECMAScriptFunctionObject, private_environment, PrivateEnvironment, ECMAScriptFunctionObject, m_private_environment, 8, cell, environment_state);
    EMIT_FIELD(ECMASCRIPT_FUNCTION_OBJECT_SCRIPT_OR_MODULE, ECMAScriptFunctionObject, script_or_module, ScriptOrModule, ECMAScriptFunctionObject, m_script_or_module, 16, nullable, scalar);

    // SharedFunctionInstanceData layout
    outln("\n# SharedFunctionInstanceData layout");
    EMIT_PAIRED_FIELD(SHARED_FUNCTION_INSTANCE_DATA_EXECUTABLE, SharedFunctionInstanceData, executable, Executable, SharedFunctionInstanceData, m_executable, 8, cell, call_data);
    EMIT_PAIRED_FIELD(SHARED_FUNCTION_INSTANCE_DATA_ASM_CALL_METADATA, SharedFunctionInstanceData, asm_call_metadata, u64, SharedFunctionInstanceData, m_asm_call_metadata, 8, scalar, call_data);
    EMIT_OFFSET(SHARED_FUNCTION_INSTANCE_DATA_FORMAL_PARAMETER_COUNT, SharedFunctionInstanceData, m_formal_parameter_count);
    EMIT_OFFSET(SHARED_FUNCTION_INSTANCE_DATA_STRICT, SharedFunctionInstanceData, m_strict);
    EMIT_OFFSET(SHARED_FUNCTION_INSTANCE_DATA_FUNCTION_ENVIRONMENT_NEEDED, SharedFunctionInstanceData, m_function_environment_needed);
    EMIT_OFFSET(SHARED_FUNCTION_INSTANCE_DATA_USES_THIS, SharedFunctionInstanceData, m_uses_this);
    EMIT_OFFSET(SHARED_FUNCTION_INSTANCE_DATA_CAN_INLINE_CALL, SharedFunctionInstanceData, m_can_inline_call);
    outln("const SHARED_FUNCTION_INSTANCE_DATA_ASM_CALL_METADATA_CAN_INLINE_CALL = {}", static_cast<u64>(SharedFunctionInstanceData::asm_call_metadata_can_inline_call));
    outln("const SHARED_FUNCTION_INSTANCE_DATA_ASM_CALL_METADATA_NEEDS_ENVIRONMENT_OR_THIS_VALUE_RESOLUTION = {}", static_cast<u64>(SharedFunctionInstanceData::asm_call_metadata_needs_environment_or_this_value_resolution));
    outln("const SHARED_FUNCTION_INSTANCE_DATA_ASM_CALL_METADATA_USES_THIS = {}", static_cast<u64>(SharedFunctionInstanceData::asm_call_metadata_uses_this));
    outln("const SHARED_FUNCTION_INSTANCE_DATA_ASM_CALL_METADATA_STRICT = {}", static_cast<u64>(SharedFunctionInstanceData::asm_call_metadata_strict));

    // GlobalEnvironment layout
    outln("\n# GlobalEnvironment layout");
    EMIT_FIELD(GLOBAL_ENVIRONMENT_GLOBAL_THIS_VALUE, GlobalEnvironment, global_this_value, Object, GlobalEnvironment, m_global_this_value, 8, nullable, cell);

    // PrimitiveString layout
    outln("\n# PrimitiveString layout");
    EMIT_FIELD(PRIMITIVE_STRING_DEFERRED_KIND, PrimitiveString, deferred_kind, u8, PrimitiveStringLayoutAccessor, m_deferred_kind, 1, nullable, scalar);
    EMIT_OFFSET(PRIMITIVE_STRING_UTF16_STRING, PrimitiveStringLayoutAccessor, m_utf16_string);
    outln("field PrimitiveString.utf16_data Utf16StringData PRIMITIVE_STRING_UTF16_STRING nullable scalar");
    outln("const PRIMITIVE_STRING_DEFERRED_KIND_NONE = {}", static_cast<u8>(PrimitiveStringLayoutAccessor::DeferredKind::None));

    // Utf16String / ShortString layout
    outln("\n# Utf16String layout");
    outln("const UTF16_SHORT_STRING_FLAG = {}", AK::Detail::StringBase::SHORT_STRING_FLAG);
    outln("const UTF16_SHORT_STRING_BYTE_COUNT_SHIFT_COUNT = {}", AK::Detail::StringBase::SHORT_STRING_BYTE_COUNT_SHIFT_COUNT);
    EMIT_OFFSET(UTF16_SHORT_STRING_BYTE_COUNT_AND_FLAG, AK::Detail::ShortString, byte_count_and_short_string_flag);
    EMIT_OFFSET(UTF16_SHORT_STRING_STORAGE, AK::Detail::ShortString, storage);
    outln("const PRIMITIVE_STRING_UTF16_SHORT_STRING_BYTE_COUNT_AND_FLAG = {}", offsetof(PrimitiveStringLayoutAccessor, m_utf16_string) + offsetof(AK::Detail::ShortString, byte_count_and_short_string_flag));
    outln("const PRIMITIVE_STRING_UTF16_SHORT_STRING_STORAGE = {}", offsetof(PrimitiveStringLayoutAccessor, m_utf16_string) + offsetof(AK::Detail::ShortString, storage));
    outln("field PrimitiveString.utf16_short_string_byte_count_and_flag u8 PRIMITIVE_STRING_UTF16_SHORT_STRING_BYTE_COUNT_AND_FLAG nullable scalar");
    outln("field PrimitiveString.utf16_short_string_storage Sequence<u8> PRIMITIVE_STRING_UTF16_SHORT_STRING_STORAGE embedded scalar");

    // Utf16StringData layout
    outln("\n# Utf16StringData layout");
    EMIT_OFFSET(UTF16_STRING_DATA_LENGTH_IN_CODE_UNITS, AK::Detail::Utf16StringData, m_header.length_in_code_units);
    EMIT_OFFSET(UTF16_STRING_DATA_FLAGS, AK::Detail::Utf16StringData, m_header.flags);
    outln("const UTF16_STRING_DATA_STRING_STORAGE = {}", AK::Detail::Utf16StringData::offset_of_string_storage());
    outln("const UTF16_STRING_DATA_HAS_UTF16_STORAGE = {}", static_cast<u32>(AK::Detail::Utf16StringData::HasUtf16Storage));
    outln("field Utf16StringData.length_in_code_units u32 UTF16_STRING_DATA_LENGTH_IN_CODE_UNITS nullable scalar");
    outln("field Utf16StringData.flags u32 UTF16_STRING_DATA_FLAGS nullable scalar");
    outln("field Utf16StringData.string_storage Sequence<u8> UTF16_STRING_DATA_STRING_STORAGE embedded scalar");

    // Environment layout
    outln("\n# Environment layout");
    EMIT_FIELD(ENVIRONMENT_SCREWED_BY_EVAL, Environment, permanently_screwed_by_eval, bool, Environment, m_permanently_screwed_by_eval, 1, nullable, scalar);
    EMIT_FIELD(ENVIRONMENT_DECLARATIVE, Environment, declarative, bool, Environment, m_declarative, 1, nullable, scalar);
    EMIT_FIELD(ENVIRONMENT_OUTER, Environment, outer, Environment, Environment, m_outer_environment, 8, nullable, cell);

    // PrivateEnvironment layout
    outln("\n# PrivateEnvironment layout");
    EMIT_FIELD(PRIVATE_ENVIRONMENT_OUTER, PrivateEnvironment, outer, PrivateEnvironment, PrivateEnvironment, m_outer_environment, 8, nullable, cell);

    // DeclarativeEnvironment binding storage layout
    outln("\n# DeclarativeEnvironment binding storage layout");
    EMIT_FIELD(DECLARATIVE_ENVIRONMENT_SHAPE, DeclarativeEnvironment, shape, EnvironmentShape, DeclarativeEnvironment, m_shape, 8, nullable, cell);
    EMIT_OFFSET(DECLARATIVE_ENVIRONMENT_BINDING_VALUES, DeclarativeEnvironment, m_binding_values);
    EMIT_OFFSET(DECLARATIVE_ENVIRONMENT_RARE_DATA_BINDING_FLAGS, DeclarativeEnvironment::RareData, m_binding_flags);
    EMIT_OFFSET(ENVIRONMENT_SHAPE_BINDING_FLAGS, EnvironmentShape, m_binding_flags);
    outln("const BINDING_FLAG_MUTABLE = {}", 1 << 1);

    outln("const BINDING_VALUES_DATA_PTR = {}",
        offsetof(DeclarativeEnvironment, m_binding_values) + vector_data_offset<decltype(DeclarativeEnvironment::m_binding_values)>());
    outln("field DeclarativeEnvironment.binding_values BindingValues BINDING_VALUES_DATA_PTR nonnull scalar");
    outln("const BINDING_FLAGS_DATA_PTR = {}",
        offsetof(DeclarativeEnvironment::RareData, m_binding_flags) + vector_data_offset<decltype(DeclarativeEnvironment::RareData::m_binding_flags)>());
    outln("field DeclarativeEnvironmentRareData.binding_flags BindingFlags BINDING_FLAGS_DATA_PTR nonnull scalar");
    outln("const ENVIRONMENT_SHAPE_BINDING_FLAGS_DATA_PTR = {}",
        offsetof(EnvironmentShape, m_binding_flags) + vector_data_offset<decltype(EnvironmentShape::m_binding_flags)>());
    outln("const ENVIRONMENT_SHAPE_BINDING_FLAGS_SIZE = {}",
        offsetof(EnvironmentShape, m_binding_flags) + vector_size_offset<decltype(EnvironmentShape::m_binding_flags)>());
    outln("field EnvironmentShape.binding_flags_size u64 ENVIRONMENT_SHAPE_BINDING_FLAGS_SIZE nullable scalar");
    outln("field EnvironmentShape.binding_flags BindingFlags ENVIRONMENT_SHAPE_BINDING_FLAGS_DATA_PTR nonnull scalar");

    // EnvironmentCoordinate layout
    outln("\n# EnvironmentCoordinate layout");
    outln("const ENVIRONMENT_COORDINATE_HOPS = {}", offsetof(EnvironmentCoordinate, hops));
    outln("const ENVIRONMENT_COORDINATE_INDEX = {}", offsetof(EnvironmentCoordinate, index));
    outln("const ENVIRONMENT_COORDINATE_INVALID = 0x{:X}", EnvironmentCoordinate::invalid_marker);
    EMIT_SIZEOF(ENVIRONMENT_COORDINATE_SIZE, EnvironmentCoordinate);
    outln("field EnvironmentCoordinateEntry.hops u32 ENVIRONMENT_COORDINATE_HOPS nullable scalar environment_coordinate stride {}", sizeof(EnvironmentCoordinate));
    outln("field EnvironmentCoordinateEntry.binding_index u32 ENVIRONMENT_COORDINATE_INDEX nullable scalar environment_coordinate");

    // TypedArrayBase layout
    outln("\n# TypedArrayBase layout");
    EMIT_OFFSET(TYPED_ARRAY_ELEMENT_SIZE, TypedArrayBase, m_element_size);
    EMIT_OFFSET(TYPED_ARRAY_ARRAY_LENGTH, TypedArrayBase, m_array_length);
    EMIT_OFFSET(TYPED_ARRAY_BYTE_OFFSET, TypedArrayBase, m_byte_offset);
    EMIT_FIELD(TYPED_ARRAY_KIND, Object, typed_array_kind, u8, TypedArrayBase, m_kind, 1, nullable, scalar);
    EMIT_FIELD(TYPED_ARRAY_CACHED_DATA_OFFSET, Object, typed_array_cached_data_offset, u64, TypedArrayBase, m_cached_data_offset, 8, nullable, scalar);
    outln("const TYPED_ARRAY_CACHED_DATA_OFFSET_INVALID = 0x{:X}", static_cast<size_t>(TypedArrayBase::invalid_cached_data_offset));
    outln("const PRIMITIVE_STORAGE_CAGE_OFFSET_MASK = 0x{:X}", static_cast<size_t>(GC::PrimitiveStorage::cage_offset_mask));
    outln("const HEAP_REGION_OFFSET_MASK = 0x{:X}", static_cast<size_t>(GC::HEAP_REGION_OFFSET_MASK));

    // ByteLength (Variant<Auto, Detached, u32>) layout
    outln("\n# ByteLength layout");
    {
        // For Variant<Auto, Detached, u32>: u32 index 2 means it holds a u32
        outln("const BYTE_LENGTH_U32_INDEX = 2");
        EMIT_SIZEOF(BYTE_LENGTH_SIZE, ByteLength);
        // Variant<Auto, Detached, u32> stores its payload first and the alternative index after it.
        // Verify that, since the generated interpreter loads both directly.
        ByteLength probe { 0x1234'5678u };
        auto const* raw = reinterpret_cast<u8 const*>(&probe);
        u32 payload = 0;
        __builtin_memcpy(&payload, raw, sizeof(payload));
        VERIFY(payload == 0x1234'5678u);
        VERIFY(raw[4] == 2);
        // Composite: array_length value (u32) and index byte within TypedArrayBase
        auto ta_al = offsetof(TypedArrayBase, m_array_length);
        outln("const TYPED_ARRAY_ARRAY_LENGTH_VALUE = {}", ta_al); // u32 data at start
        outln("field Object.typed_array_array_length u32 TYPED_ARRAY_ARRAY_LENGTH_VALUE nullable scalar");
        outln("const TYPED_ARRAY_ARRAY_LENGTH_INDEX = {}", ta_al + 4); // index byte after 4 bytes of data
    }

    // TypedArrayBase::Kind enum values
    outln("\n# TypedArrayBase::Kind values");
    static_assert(static_cast<u8>(TypedArrayBase::Kind::Uint8Array) == 0);
    static_assert(static_cast<u8>(TypedArrayBase::Kind::Uint8ClampedArray) == 1);
    static_assert(static_cast<u8>(TypedArrayBase::Kind::Uint16Array) == 2);
    outln("const TYPED_ARRAY_KIND_UINT8 = {}", static_cast<u8>(TypedArrayBase::Kind::Uint8Array));
    outln("const TYPED_ARRAY_KIND_UINT8_CLAMPED = {}", static_cast<u8>(TypedArrayBase::Kind::Uint8ClampedArray));
    outln("const TYPED_ARRAY_KIND_UINT16 = {}", static_cast<u8>(TypedArrayBase::Kind::Uint16Array));
    outln("const TYPED_ARRAY_KIND_UINT32 = {}", static_cast<u8>(TypedArrayBase::Kind::Uint32Array));
    outln("const TYPED_ARRAY_KIND_INT8 = {}", static_cast<u8>(TypedArrayBase::Kind::Int8Array));
    outln("const TYPED_ARRAY_KIND_INT16 = {}", static_cast<u8>(TypedArrayBase::Kind::Int16Array));
    outln("const TYPED_ARRAY_KIND_INT32 = {}", static_cast<u8>(TypedArrayBase::Kind::Int32Array));
    outln("const TYPED_ARRAY_KIND_FLOAT32 = {}", static_cast<u8>(TypedArrayBase::Kind::Float32Array));
    outln("const TYPED_ARRAY_KIND_FLOAT64 = {}", static_cast<u8>(TypedArrayBase::Kind::Float64Array));

    // Value tags
    outln("\n# Value tags");
    outln("const OBJECT_TAG = 0x{:X}", static_cast<u64>(OBJECT_TAG));
    outln("const STRING_TAG = 0x{:X}", static_cast<u64>(STRING_TAG));
    outln("const SYMBOL_TAG = 0x{:X}", static_cast<u64>(SYMBOL_TAG));
    outln("const BIGINT_TAG = 0x{:X}", static_cast<u64>(BIGINT_TAG));
    outln("const ACCESSOR_TAG = 0x{:X}", static_cast<u64>(ACCESSOR_TAG));
    outln("const IS_CELL_PATTERN = 0x{:X}", static_cast<u64>(GC::IS_CELL_PATTERN));
    outln("const INT32_TAG = 0x{:X}", static_cast<u64>(INT32_TAG));
    outln("const BOOLEAN_TAG = 0x{:X}", static_cast<u64>(BOOLEAN_TAG));
    outln("const UNDEFINED_TAG = 0x{:X}", static_cast<u64>(UNDEFINED_TAG));
    outln("const NULL_TAG = 0x{:X}", static_cast<u64>(NULL_TAG));

    // Shifted value constants
    outln("\n# Shifted value constants");
    outln("const OBJECT_TAG_SHIFTED = 0x{:X}", static_cast<u64>(OBJECT_TAG << GC::TAG_SHIFT));
    outln("const EMPTY_VALUE = 0x{:X}", static_cast<u64>(EMPTY_TAG << GC::TAG_SHIFT));
    outln("const INT32_TAG_SHIFTED = 0x{:X}", static_cast<u64>(INT32_TAG << GC::TAG_SHIFT));
    outln("const BOOLEAN_TRUE = 0x{:X}", static_cast<u64>((BOOLEAN_TAG << GC::TAG_SHIFT) | 1));
    outln("const BOOLEAN_FALSE = 0x{:X}", static_cast<u64>(BOOLEAN_TAG << GC::TAG_SHIFT));
    outln("const UNDEFINED_SHIFTED = 0x{:X}", static_cast<u64>(UNDEFINED_TAG << GC::TAG_SHIFT));
    outln("const NULL_VALUE = 0x{:X}", static_cast<u64>(NULL_TAG << GC::TAG_SHIFT));
    outln("const EMPTY_TAG_SHIFTED = 0x{:X}", static_cast<u64>(EMPTY_TAG << GC::TAG_SHIFT));
    outln("const NAN_BASE_TAG = 0x{:X}", static_cast<u64>(GC::BASE_TAG));
    outln("const CANON_NAN_BITS = 0x{:X}", static_cast<u64>(GC::CANON_NAN_BITS));
    outln("const DOUBLE_ONE = 0x{:X}", bit_cast<u64>(1.0));
    outln("const NEGATIVE_ZERO = 0x{:X}", static_cast<u64>(NEGATIVE_ZERO_BITS));
    outln("const SHIFTED_IS_CELL_PATTERN = 0x{:X}", static_cast<u64>(GC::SHIFTED_IS_CELL_PATTERN));

    outln("const ACCUMULATOR_REG_OFFSET = {}", static_cast<size_t>(Register::accumulator().index()) * sizeof(Value));
    outln("const EXCEPTION_REG_OFFSET = {}", static_cast<size_t>(Register::exception().index()) * sizeof(Value));
    outln("const THIS_VALUE_REG_OFFSET = {}", static_cast<size_t>(Register::this_value().index()) * sizeof(Value));
    outln("const RETURN_VALUE_REG_OFFSET = {}", static_cast<size_t>(Register::return_value().index()) * sizeof(Value));
    outln("const SAVED_LEXICAL_ENVIRONMENT_REG_OFFSET = {}", static_cast<size_t>(Register::saved_lexical_environment().index()) * sizeof(Value));
    outln("const RESERVED_REGISTER_COUNT = {}", static_cast<size_t>(Register::reserved_register_count));

    return 0;
}
