// https://w3c.github.io/picture-in-picture/#htmlvideoelement-extensions
partial interface HTMLVideoElement {
    [CEReactions, Reflect=disablepictureinpicture] attribute boolean disablePictureInPicture;
};
