#import <DOM/EventTarget.idl>
#import <WebGPU/GPUQueue.idl>

// https://www.w3.org/TR/webgpu/#gpudevice
[Exposed=(Window,Worker), SecureContext]
interface GPUDevice : EventTarget {
    [SameObject] readonly attribute GPUQueue queue;
};
