// FIXME: https://www.w3.org/TR/webgpu/#gpufeaturename

// https://www.w3.org/TR/webgpu/#gpusupportedfeatures
[Exposed=(Window, Worker), SecureContext]
interface GPUSupportedFeatures {
    // FIXME: Add IDL support for `readonly setlike<T>;`
    setlike<DOMString>;
};
