// https://www.w3.org/TR/webgpu/#gpufeaturename
enum GPUFeatureName {
    "core-features-and-limits",
    "depth-clip-control",
    "depth32float-stencil8",
    "texture-compression-bc",
    "texture-compression-bc-sliced-3d",
    "texture-compression-etc2",
    "texture-compression-astc",
    "texture-compression-astc-sliced-3d",
    "timestamp-query",
    "indirect-first-instance",
    "shader-f16",
    "rg11b10ufloat-renderable",
    "bgra8unorm-storage",
    "float32-filterable",
    "float32-blendable",
    "clip-distances",
    "dual-source-blending",
    "subgroups",
    "texture-formats-tier1",
    "texture-formats-tier2",
};

// https://www.w3.org/TR/webgpu/#gpusupportedfeatures
[Exposed=(Window, Worker), SecureContext]
interface GPUSupportedFeatures {
    // FIXME: Add IDL support for `readonly setlike<T>;`
    setlike<DOMString>;
};
