#import <WebGPU/GPUTextureView.idl>

// https://www.w3.org/TR/webgpu/#dictdef-gputextureviewdescriptor
dictionary GPUTextureViewDescriptor {

};

// https://www.w3.org/TR/webgpu/#gputexture
[Exposed=(Window, Worker), SecureContext]
interface GPUTexture {
    GPUTextureView createView(optional GPUTextureViewDescriptor descriptor = {});
};
