// https://w3c.github.io/performance-timeline/#typedefdef-performanceentrylist
typedef sequence<PerformanceEntry> PerformanceEntryList;

// https://w3c.github.io/hr-time/#sec-performance
[Exposed=(Window, Worker)]
interface Performance : EventTarget {
    DOMHighResTimeStamp now();
    readonly attribute DOMHighResTimeStamp timeOrigin;
    [Default] object toJSON();

    // https://w3c.github.io/user-timing/#extensions-performance-interface
    // "User Timing" extensions to the Performance interface
    PerformanceMark mark(Utf16DOMString markName, optional PerformanceMarkOptions markOptions = {});
    undefined clearMarks(optional Utf16DOMString markName);
    PerformanceMeasure measure(Utf16DOMString measureName, optional (Utf16DOMString or PerformanceMeasureOptions) startOrMeasureOptions = {}, optional Utf16DOMString endMark);
    undefined clearMeasures(optional Utf16DOMString measureName);

    // https://w3c.github.io/resource-timing/#sec-extensions-performance-interface
    // "Resource Timing" extensions to the Performance interface
    undefined clearResourceTimings();
    undefined setResourceTimingBufferSize(unsigned long maxSize);
    attribute EventHandler onresourcetimingbufferfull;

    // https://w3c.github.io/performance-timeline/#extensions-to-the-performance-interface
    // "Performance Timeline" extensions to the Performance interface
    PerformanceEntryList getEntries();
    PerformanceEntryList getEntriesByType([Utf16FlyString] Utf16DOMString type);
    PerformanceEntryList getEntriesByName(Utf16DOMString name, optional [Utf16FlyString] Utf16DOMString type);
};
