#import <Encoding/TextDecoderCommon.idl>

// https://encoding.spec.whatwg.org/#textdecoder
[Exposed=*]
interface TextDecoder {
    constructor(optional DOMString label = "utf-8", optional TextDecoderOptions options = {});

    // FIXME: BufferSource is really a AllowSharedBufferSource
    USVString decode(optional BufferSource input, optional TextDecodeOptions options = {});
};
TextDecoder includes TextDecoderCommon;
