#import <Encoding/TextDecoderCommon.idl>
#import <Streams/GenericTransformStream.idl>

// https://encoding.spec.whatwg.org/#interface-textdecoderstream
[Exposed=*]
interface TextDecoderStream {
    constructor(optional DOMString label = "utf-8", optional TextDecoderOptions options = {});
};
TextDecoderStream includes TextDecoderCommon;
TextDecoderStream includes GenericTransformStream;
