#import <Encoding/TextEncoder.idl>
#import <Streams/GenericTransformStream.idl>

// https://encoding.spec.whatwg.org/#textencoderstream
[Exposed=*]
interface TextEncoderStream {
    constructor();
};

TextEncoderStream includes TextEncoderCommon;
TextEncoderStream includes GenericTransformStream;
