// https://registry.khronos.org/webgl/extensions/OES_element_index_uint/
// NOTE: Original OES_element_index_uint name is changed to title case, so it matches corresponding C++ class name, and
// does not require IDL generator to handle snake_case to TitleCase conversion. Having a different name is totally
// fine, because LegacyNoInterfaceObject prevents the name from being exposed to JavaScript.
[Exposed=(Window,Worker), LegacyNoInterfaceObject]
interface OESElementIndexUint {
};
