typedef sequence<ClipboardItem> ClipboardItems;

// https://w3c.github.io/clipboard-apis/#clipboard
[SecureContext, Exposed=Window]
interface Clipboard : EventTarget {
    Promise<ClipboardItems> read(optional ClipboardUnsanitizedFormats formats = {});
    Promise<Utf16DOMString> readText();
    Promise<undefined> write(ClipboardItems data);
    Promise<undefined> writeText(Utf16DOMString data);
};

dictionary ClipboardUnsanitizedFormats {
    sequence<Utf16DOMString> unsanitized;
};
