#import <Clipboard/ClipboardItem.idl>
#import <DOM/EventTarget.idl>

typedef sequence<ClipboardItem> ClipboardItems;

// https://w3c.github.io/clipboard-apis/#clipboard
[SecureContext, Exposed=Window]
interface Clipboard : EventTarget {
    [FIXME] Promise<ClipboardItems> read();
    Promise<DOMString> readText();
    Promise<undefined> write(ClipboardItems data);
    Promise<undefined> writeText(DOMString data);
};
