dictionary ClipboardEventInit : EventInit {
    DataTransfer? clipboardData = null;
};

// https://w3c.github.io/clipboard-apis/#clipboardevent
[Exposed=Window]
interface ClipboardEvent : Event {
    constructor(DOMString type, optional ClipboardEventInit eventInitDict = {});
    [DirectGetter] readonly attribute DataTransfer? clipboardData;
};
