dictionary ClipboardEventInit : EventInit {
    DataTransfer? clipboardData = null;
};

// https://w3c.github.io/clipboard-apis/#clipboardevent
[Exposed=Window]
interface ClipboardEvent : Event {
    constructor([Utf16FlyString] Utf16DOMString type, optional ClipboardEventInit eventInitDict = {});
    readonly attribute DataTransfer? clipboardData;
};
