[Exposed=Window, SecureContext]
interface CredentialsContainer {
    [CreatesPromise, NeedsCallerRealm] Promise<Credential?> get(optional CredentialRequestOptions options = {});
    [CreatesPromise, NeedsCallerRealm] Promise<undefined> store(Credential credential);
    [CreatesPromise, NeedsCallerRealm] Promise<Credential?> create(optional CredentialCreationOptions options = {});
    [CreatesPromise, NeedsCallerRealm] Promise<undefined> preventSilentAccess();
};

dictionary CredentialRequestOptions {
    CredentialMediationRequirement mediation = "optional";
    AbortSignal signal;
};

dictionary CredentialCreationOptions {
    CredentialMediationRequirement mediation = "optional";
    AbortSignal signal;
};
