#import <CredentialManagement/Credential.idl>
[Exposed=Window, SecureContext]
interface CredentialsContainer {
    Promise<Credential?> get(optional CredentialRequestOptions options = {});
    Promise<undefined> store(Credential credential);
    Promise<Credential?> create(optional CredentialCreationOptions options = {});
    Promise<undefined> preventSilentAccess();
};

dictionary CredentialData {
    required USVString id;
};
