[Exposed=Window, SecureContext]
interface Credential {
    readonly attribute Utf16USVString id;
    readonly attribute [Utf16FlyString] Utf16DOMString type;
    static Promise<boolean> isConditionalMediationAvailable();
};

[SecureContext]
interface mixin CredentialUserData {
    readonly attribute Utf16USVString name;
    readonly attribute Utf16USVString iconURL;
};

dictionary CredentialData {
    required Utf16USVString id;
};

enum CredentialMediationRequirement {
    "silent",
    "optional",
    "conditional",
    "required"
};
