[Exposed=Window, SecureContext]
interface FederatedCredential : Credential {
    constructor(FederatedCredentialInit data);
    readonly attribute Utf16USVString provider;
    readonly attribute Utf16DOMString? protocol;
};
FederatedCredential includes CredentialUserData;

dictionary FederatedCredentialRequestOptions {
    sequence<Utf16USVString> providers;
    sequence<Utf16DOMString> protocols;
};

partial dictionary CredentialRequestOptions {
    FederatedCredentialRequestOptions federated;
};

dictionary FederatedCredentialInit : CredentialData {
    Utf16USVString name;
    Utf16USVString iconURL;
    required Utf16USVString provider;
    Utf16DOMString protocol;

    // We don't carry the "origin" field from the spec.
    // https://github.com/w3c/webappsec-credential-management/pull/131
};

partial dictionary CredentialCreationOptions {
    FederatedCredentialInit federated;
};
