#import <CredentialManagement/Credential.idl>

[Exposed=Window, SecureContext]
interface PasswordCredential : Credential {
    constructor(HTMLFormElement form);
    constructor(PasswordCredentialData data);
    readonly attribute USVString password;
};
PasswordCredential includes CredentialUserData;

partial dictionary CredentialRequestOptions {
    boolean password = false;
};

dictionary PasswordCredentialData : CredentialData {
    USVString name;
    USVString iconURL;
    required USVString password;

    // We don't carry the "origin" field from the spec.
    // https://github.com/w3c/webappsec-credential-management/pull/131
};

typedef (PasswordCredentialData or HTMLFormElement) PasswordCredentialInit;

partial dictionary CredentialCreationOptions {
    PasswordCredentialInit password;
};
