// https://w3c.github.io/mediacapture-main/#mediastreamtrack

enum MediaStreamTrackState { "live", "ended" };
enum MediaStreamTrackKind { "audio", "video" };

[Exposed=Window]
interface MediaStreamTrack : EventTarget {
    [ImplementedAs=track_kind] readonly attribute MediaStreamTrackKind kind;
    readonly attribute DOMString id;
    readonly attribute DOMString label;
    attribute boolean enabled;
    readonly attribute boolean muted;
    [ImplementedAs=track_ready_state] readonly attribute MediaStreamTrackState readyState;
    undefined stop();
    [ImplementedAs=get_capabilities] MediaTrackCapabilities getCapabilities();
    MediaTrackConstraints getConstraints();
    MediaTrackSettings getSettings();
    [NeedsThisObjectRealm] Promise<undefined> applyConstraints(optional MediaTrackConstraints constraints = {});
};
