// https://w3c.github.io/mediacapture-main/#dom-mediadevicekind
enum MediaDeviceKind {
    "audioinput",
    "audiooutput",
    "videoinput"
};

// https://w3c.github.io/mediacapture-main/#mediadeviceinfo
[Exposed=Window, SecureContext]
interface MediaDeviceInfo {
    readonly attribute Utf16DOMString deviceId;
    readonly attribute MediaDeviceKind kind;
    readonly attribute Utf16DOMString label;
    readonly attribute Utf16DOMString groupId;
    [Default] object toJSON();
};
