// https://w3c.github.io/FileAPI/#FileReaderSync
[Exposed=(DedicatedWorker,SharedWorker)]
interface FileReaderSync {
    constructor();
    // Synchronously return strings

    ArrayBuffer readAsArrayBuffer(Blob blob);
    Utf16DOMString readAsText(Blob blob, optional Utf16DOMString encoding);
    Utf16DOMString readAsBinaryString(Blob blob);
    Utf16DOMString readAsDataURL(Blob blob);
};
