// https://wicg.github.io/speech-api/#speechrecognitionalternative
[Exposed=Window]
interface SpeechRecognitionAlternative {
    readonly attribute DOMString transcript;
    readonly attribute float confidence;
};
