#import <Speech/SpeechGrammar.idl>

// https://wicg.github.io/speech-api/#speechgrammarlist
[Exposed=Window]
interface SpeechGrammarList {
    constructor();

    readonly attribute unsigned long length;
    getter SpeechGrammar item(unsigned long index);
    [FIXME] undefined addFromURI(DOMString src, optional float weight = 1.0);
    [FIXME] undefined addFromString(DOMString string, optional float weight = 1.0);
};
