// https://wicg.github.io/speech-api/#speechsynthesisvoice
[Exposed=Window]
interface SpeechSynthesisVoice {
    readonly attribute Utf16DOMString voiceURI;
    readonly attribute Utf16DOMString name;
    readonly attribute Utf16DOMString lang;
    readonly attribute boolean localService;
    [ImplementedAs=is_default] readonly attribute boolean default;
};
