#import <Speech/SpeechRecognitionAlternative.idl>

// https://wicg.github.io/speech-api/#speechrecognitionresult
[Exposed=Window]
interface SpeechRecognitionResult {
    readonly attribute unsigned long length;
    getter SpeechRecognitionAlternative item(unsigned long index);
    readonly attribute boolean isFinal;
};
