// https://wicg.github.io/speech-api/#speechgrammarlist
[Exposed=Window]
interface SpeechGrammarList {
    constructor();

    readonly attribute unsigned long length;
    getter SpeechGrammar item(unsigned long index);
    [FIXME] undefined addFromURI(Utf16DOMString src, optional float weight = 1.0);
    [FIXME] undefined addFromString(Utf16DOMString string, optional float weight = 1.0);
};
