// https://wicg.github.io/speech-api/#speechrecognitionphrase
[Exposed=Window]
interface SpeechRecognitionPhrase {
    constructor(Utf16DOMString phrase, optional float boost = 1.0);
    readonly attribute Utf16DOMString phrase;
    readonly attribute float boost;
};
