// https://wicg.github.io/speech-api/#speechsynthesisutterance
[Exposed=Window]
interface SpeechSynthesisUtterance : EventTarget {
    constructor(optional Utf16DOMString text = "");

    attribute Utf16DOMString text;
    attribute Utf16DOMString lang;
    attribute SpeechSynthesisVoice? voice;
    attribute float volume;
    attribute float rate;
    attribute float pitch;

    attribute EventHandler onstart;
    attribute EventHandler onend;
    attribute EventHandler onerror;
    attribute EventHandler onpause;
    attribute EventHandler onresume;
    attribute EventHandler onmark;
    attribute EventHandler onboundary;
};
