#!/usr/bin/env python3

# Copyright (c) 2026, Callum Law <callumlaw1709@outlook.com>
#
# SPDX-License-Identifier: BSD-2-Clause

import argparse
import json
import sys

from pathlib import Path
from typing import Any
from typing import TextIO

sys.path.append(str(Path(__file__).resolve().parent.parent))

from Utils.CSSGrammar.generator import generate_css_parser_expression_for_grammar
from Utils.utils import snake_casify


def json_is_valid(value_type_data: dict[str, Any], json_path: str) -> bool:
    is_valid = True
    most_recent_value_type_name = ""

    for value_type_name, value_type_definition in value_type_data.items():
        if value_type_name.lower() < most_recent_value_type_name.lower():
            print(
                f"{json_path}: Value type `{value_type_name}` is in the wrong position. Please keep this list alphabetical!",
                file=sys.stderr,
            )
            is_valid = False

        most_recent_value_type_name = value_type_name

        if not isinstance(value_type_definition, dict):
            print(f"{json_path}: Value type `{value_type_name}` is not an object", file=sys.stderr)
            is_valid = False
            continue

        if "spec" not in value_type_definition:
            print(f"{json_path}: Value type `{value_type_name}` is missing a spec link", file=sys.stderr)
            is_valid = False
        elif not isinstance(value_type_definition["spec"], str):
            print(f"{json_path}: Value type `{value_type_name}` has a spec field that is not a string", file=sys.stderr)
            is_valid = False

        if "grammar" not in value_type_definition:
            print(f"{json_path}: Value type `{value_type_name}` is missing a grammar", file=sys.stderr)
            is_valid = False
        elif not isinstance(value_type_definition["grammar"], str):
            print(
                f"{json_path}: Value type `{value_type_name}` has a grammar field that is not a string",
                file=sys.stderr,
            )
            is_valid = False

        for field_name in value_type_definition:
            if field_name in ("spec", "grammar", "__comment"):
                continue

            print(
                f"{json_path}: Value type `{value_type_name}` has an unexpected field `{field_name}`",
                file=sys.stderr,
            )
            is_valid = False

    return is_valid


def value_type_name_to_snake_case(value_type_name: str) -> str:
    return snake_casify(value_type_name[1:-1])


def generate_header_file(out: TextIO, value_type_data: dict[str, Any]) -> None:
    out.write("""// This file is generated by generate_libweb_css_value_types_parsing.py

#pragma once

namespace Web::CSS {

#define ENUMERATE_GENERATED_CSS_VALUE_TYPES \\
""")

    for value_type_name in value_type_data:
        out.write(f"    __ENUMERATE_GENERATED_CSS_VALUE_TYPE({value_type_name_to_snake_case(value_type_name)}) \\\n")

    out.write("\n")
    out.write("}")


def generate_implementation_file(out: TextIO, value_type_data: dict[str, Any]) -> None:
    out.write("""// This file is generated by generate_libweb_css_value_types_parsing.py

#include <LibWeb/CSS/Parser/Parser.h>

#include <LibWeb/CSS/StyleValues/CustomIdentStyleValue.h>
#include <LibWeb/CSS/StyleValues/StringStyleValue.h>

namespace Web::CSS::Parser {

""")

    for value_type_name, value_type_definition in value_type_data.items():
        spec_link = value_type_definition["spec"]
        grammar = value_type_definition["grammar"]
        name_snake_case = value_type_name_to_snake_case(value_type_name)

        out.write(f"""
// {spec_link}
RefPtr<StyleValue const> Parser::parse_{name_snake_case}_value(TokenStream<ComponentValue>& tokens)
{{
    // {value_type_name} = {grammar}
""")
        generate_css_parser_expression_for_grammar(out, name_snake_case, grammar)
        out.write(f"""    return {name_snake_case};
}}
""")

    out.write("}\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate CSS value types parsing methods", add_help=False)
    parser.add_argument("--help", action="help", help="Show this help message and exit")
    parser.add_argument(
        "-h",
        "--header",
        required=True,
        help="Path to the GeneratedValueTypesParsing header file to generate",
    )
    parser.add_argument(
        "-c",
        "--implementation",
        required=True,
        help="Path to the GeneratedValueTypesParsing implementation file to generate",
    )
    parser.add_argument("-j", "--json", required=True, help="Path to the JSON file to read from")
    args = parser.parse_args()

    with open(args.json, "r", encoding="utf-8") as json_file:
        value_type_data = json.load(json_file)

    if not isinstance(value_type_data, dict):
        raise RuntimeError(f"{args.json}: expected a JSON object")

    if not json_is_valid(value_type_data, args.json):
        sys.exit(1)

    with (
        open(args.header, "w", encoding="utf-8") as header_file,
        open(args.implementation, "w", encoding="utf-8") as implementation_file,
    ):
        generate_header_file(header_file, value_type_data)
        generate_implementation_file(implementation_file, value_type_data)

    return 0


if __name__ == "__main__":
    sys.exit(main())
