#import <Fetch/Request.idl>

// https://w3c.github.io/ServiceWorker/#cachestorage-interface
[SecureContext, Exposed=(Window,Worker)]
interface CacheStorage {
    //[NewObject] Promise<(Response or undefined)> match(RequestInfo request, optional MultiCacheQueryOptions options = {});
    //[NewObject] Promise<boolean> has(DOMString cacheName);
    [NewObject] Promise<Cache> open(DOMString cacheName);
    //[NewObject] Promise<boolean> delete(DOMString cacheName);
    //[NewObject] Promise<sequence<DOMString>> keys();
};

//dictionary MultiCacheQueryOptions : CacheQueryOptions {
//    DOMString cacheName;
//};
