// https://w3c.github.io/ServiceWorker/#cachestorage-interface
[SecureContext, Exposed=(Window,Worker)]
interface CacheStorage {
    [NeedsCallerRealm, NewObject] Promise<(Response or undefined)> match(RequestInfo request, optional MultiCacheQueryOptions options = {});
    [NeedsCallerRealm, NewObject] Promise<boolean> has(DOMString cacheName);
    [NeedsCallerRealm, NewObject] Promise<Cache> open(DOMString cacheName);
    [NeedsCallerRealm, NewObject] Promise<boolean> delete(DOMString cacheName);
    [NeedsCallerRealm, NewObject] Promise<sequence<DOMString>> keys();
};

dictionary MultiCacheQueryOptions : CacheQueryOptions {
    DOMString cacheName;
};

// https://w3c.github.io/ServiceWorker/#self-caches
partial interface mixin WindowOrWorkerGlobalScope {
    [SecureContext, SameObject] readonly attribute CacheStorage caches;
};
