/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Generated CSS property metadata for the Rust style computation core.
//!
//! The tables are generated by build.rs from Properties.json, replicating the
//! property identifier assignment of the C++ generator exactly: Custom is 0,
//! then shorthands, inherited longhands and non-inherited longhands in JSON
//! order, skipping legacy aliases. A C++ unit test compares every table
//! against the C++-generated equivalents so the two generators cannot drift.
//!
//! Property identifiers cross the FFI as opaque u16 values, like keywords.

include!(concat!(env!("OUT_DIR"), "/property_metadata_generated.rs"));

pub(crate) const NUMBER_OF_LONGHAND_PROPERTIES: usize =
    (LAST_LONGHAND_PROPERTY_ID - FIRST_LONGHAND_PROPERTY_ID + 1) as usize;

/// How much of the computation a property needs, mirroring the C++
/// requires-computation levels: 0 = never, 1 = with the cascaded value,
/// 2 = with any non-inherited value, 3 = always.
pub const REQUIRES_COMPUTATION_NEVER: u8 = 0;
pub const REQUIRES_COMPUTATION_CASCADED: u8 = 1;
pub const REQUIRES_COMPUTATION_NON_INHERITED: u8 = 2;
pub const REQUIRES_COMPUTATION_ALWAYS: u8 = 3;

fn longhand_index(property_id: u16) -> usize {
    debug_assert!((FIRST_LONGHAND_PROPERTY_ID..=LAST_LONGHAND_PROPERTY_ID).contains(&property_id));
    (property_id - FIRST_LONGHAND_PROPERTY_ID) as usize
}

pub fn property_is_inherited(property_id: u16) -> bool {
    (FIRST_INHERITED_PROPERTY_ID..=LAST_INHERITED_PROPERTY_ID).contains(&property_id)
}

pub fn property_requires_computation_level(property_id: u16) -> u8 {
    REQUIRES_COMPUTATION_LEVELS[longhand_index(property_id)]
}

/// Returns the longhand property identifiers in computation order.
pub fn property_computation_order() -> &'static [u16] {
    &PROPERTY_COMPUTATION_ORDER
}

/// FFI accessors for the parity test on the C++ side.
///
/// # Safety
/// `out_length` must be a valid pointer.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rust_property_metadata_computation_order(out_length: *mut usize) -> *const u16 {
    unsafe { *out_length = PROPERTY_COMPUTATION_ORDER.len() };
    PROPERTY_COMPUTATION_ORDER.as_ptr()
}

#[unsafe(no_mangle)]
pub extern "C" fn rust_property_metadata_is_inherited(property_id: u16) -> bool {
    property_is_inherited(property_id)
}

#[unsafe(no_mangle)]
pub extern "C" fn rust_property_metadata_requires_computation_level(property_id: u16) -> u8 {
    property_requires_computation_level(property_id)
}

/// # Safety
/// All out-pointers must be valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rust_property_metadata_bounds(
    out_first_longhand: *mut u16,
    out_last_longhand: *mut u16,
    out_first_inherited: *mut u16,
    out_last_inherited: *mut u16,
) {
    unsafe {
        *out_first_longhand = FIRST_LONGHAND_PROPERTY_ID;
        *out_last_longhand = LAST_LONGHAND_PROPERTY_ID;
        *out_first_inherited = FIRST_INHERITED_PROPERTY_ID;
        *out_last_inherited = LAST_INHERITED_PROPERTY_ID;
    }
}

pub fn property_is_shorthand(property_id: u16) -> bool {
    (FIRST_SHORTHAND_PROPERTY_ID..=LAST_SHORTHAND_PROPERTY_ID).contains(&property_id)
}

/// Returns the longhands a shorthand expands to, in Properties.json order.
pub fn longhands_for_shorthand(property_id: u16) -> &'static [u16] {
    if !property_is_shorthand(property_id) {
        return &[];
    }
    SHORTHAND_EXPANSIONS[(property_id - FIRST_SHORTHAND_PROPERTY_ID) as usize]
}

/// FFI accessors for the parity test on the C++ side.
#[unsafe(no_mangle)]
pub extern "C" fn rust_property_metadata_is_shorthand(property_id: u16) -> bool {
    property_is_shorthand(property_id)
}

/// # Safety
/// `out_length` must be a valid pointer.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rust_property_metadata_longhands_for_shorthand(
    property_id: u16,
    out_length: *mut usize,
) -> *const u16 {
    let longhands = longhands_for_shorthand(property_id);
    unsafe { *out_length = longhands.len() };
    longhands.as_ptr()
}
