[GenerateToValue]
dictionary CookieListItem {
    Utf16USVString name;
    Utf16USVString value;
};

typedef sequence<CookieListItem> CookieList;

dictionary CookieStoreGetOptions {
    Utf16USVString name;
    Utf16USVString url;
};

enum CookieSameSite {
    "strict",
    "lax",
    "none"
};

dictionary CookieInit {
    required Utf16USVString name;
    required Utf16USVString value;
    DOMHighResTimeStamp? expires = null;
    Utf16USVString? domain = null;
    Utf16USVString path = "/";
    CookieSameSite sameSite = "strict";
    boolean partitioned = false;
};

dictionary CookieStoreDeleteOptions {
    required Utf16USVString name;
    Utf16USVString? domain = null;
    Utf16USVString path = "/";
    boolean partitioned = false;
};

// https://cookiestore.spec.whatwg.org/#cookiestore
[Exposed=(ServiceWorker,Window), SecureContext]
interface CookieStore : EventTarget {
    Promise<CookieListItem?> get(Utf16USVString name);
    Promise<CookieListItem?> get(optional CookieStoreGetOptions options = {});

    Promise<CookieList> getAll(Utf16USVString name);
    Promise<CookieList> getAll(optional CookieStoreGetOptions options = {});

    Promise<undefined> set(Utf16USVString name, Utf16USVString value);
    Promise<undefined> set(CookieInit options);

    Promise<undefined> delete(Utf16USVString name);
    Promise<undefined> delete(CookieStoreDeleteOptions options);

    [Exposed=Window] attribute EventHandler onchange;
};

// https://cookiestore.spec.whatwg.org/#Window
[SecureContext]
partial interface Window {
    [SameObject] readonly attribute CookieStore cookieStore;
};

// https://cookiestore.spec.whatwg.org/#ServiceWorkerGlobalScope
partial interface ServiceWorkerGlobalScope {
    [SameObject] readonly attribute CookieStore cookieStore;
};
