/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

use std::env;
use std::error::Error;
use std::fmt::Write;
use std::path::{Path, PathBuf};

// Mirrors title_casify() in Meta/Utils/utils.py.
fn title_casify(dashy_name: &str) -> String {
    dashy_name
        .split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let first = chars.next().unwrap().to_ascii_uppercase();
            format!("{first}{}", chars.as_str())
        })
        .collect()
}

fn write_enum_and_from_ffi(output: &mut String, enum_name: &str, variants: &[String]) {
    writeln!(output, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]").unwrap();
    writeln!(output, "#[repr(u8)]").unwrap();
    writeln!(output, "pub enum {enum_name} {{").unwrap();
    for variant in variants {
        writeln!(output, "    {variant},").unwrap();
    }
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
    let fn_name = if enum_name == "PseudoClassType" {
        "pseudo_class_from_ffi"
    } else {
        "pseudo_element_from_ffi"
    };
    writeln!(output, "fn {fn_name}(value: u8) -> {enum_name} {{").unwrap();
    writeln!(output, "    match value {{").unwrap();
    for (index, variant) in variants.iter().enumerate() {
        writeln!(output, "        {index} => {enum_name}::{variant},").unwrap();
    }
    writeln!(output, "        _ => panic!(\"invalid {enum_name} {{value}}\"),").unwrap();
    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
}

// Generates the Rust twins of the C++ PseudoClass and PseudoElement enums from the same JSON
// sources as Meta/Generators/generate_libweb_css_pseudo_{class,element}.py, so the numeric
// values that cross the selector FFI cannot drift out of sync with the C++ side.
fn generate_selector_pseudo_types(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let css_dir = manifest_dir.parent().unwrap();
    let pseudo_classes_path = css_dir.join("PseudoClasses.json");
    let pseudo_elements_path = css_dir.join("PseudoElements.json");
    println!("cargo:rerun-if-changed={}", pseudo_classes_path.display());
    println!("cargo:rerun-if-changed={}", pseudo_elements_path.display());

    let parse_object = |path: &Path| -> Result<serde_json::Map<String, serde_json::Value>, Box<dyn Error>> {
        let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(path)?)?;
        match value {
            serde_json::Value::Object(object) => Ok(object),
            _ => Err(format!("{} does not contain a JSON object", path.display()).into()),
        }
    };

    let pseudo_class_names = parse_object(&pseudo_classes_path)?
        .iter()
        .filter(|(_, value)| !value.as_object().unwrap().contains_key("legacy-alias-for"))
        .map(|(name, _)| title_casify(name))
        .collect::<Vec<_>>();

    let mut synthetic_pseudo_elements = Vec::new();
    let mut element_reference_pseudo_elements = Vec::new();
    let mut functional_pseudo_elements = Vec::new();
    for (name, value) in &parse_object(&pseudo_elements_path)? {
        let object = value.as_object().unwrap();
        if object.contains_key("alias-for") {
            continue;
        }
        if object.get("type").and_then(|value| value.as_str()) == Some("function") {
            functional_pseudo_elements.push(title_casify(name));
            continue;
        }
        match object.get("implementation").and_then(|value| value.as_str()) {
            Some("synthetic") => synthetic_pseudo_elements.push(title_casify(name)),
            Some("element-reference") => element_reference_pseudo_elements.push(title_casify(name)),
            other => return Err(format!("invalid or missing implementation type for ::{name}: {other:?}").into()),
        }
    }
    let mut pseudo_element_names = synthetic_pseudo_elements;
    pseudo_element_names.extend(element_reference_pseudo_elements);
    pseudo_element_names.extend(functional_pseudo_elements);
    // NB: The C++ generator emits UnknownWebKit after KnownPseudoElementCount, so its FFI value is
    //     the number of known pseudo-elements.
    pseudo_element_names.push("UnknownWebKit".to_string());

    let mut output = String::new();
    writeln!(
        output,
        "// Generated by build.rs from CSS/PseudoClasses.json and CSS/PseudoElements.json."
    )
    .unwrap();
    writeln!(output).unwrap();
    write_enum_and_from_ffi(&mut output, "PseudoClassType", &pseudo_class_names);
    write_enum_and_from_ffi(&mut output, "PseudoElementType", &pseudo_element_names);

    std::fs::write(out_dir.join("selector_pseudo_generated.rs"), output)?;
    Ok(())
}

// Generates the property metadata tables for the Rust style computation core from
// Properties.json, replicating the C++ generator's identifier assignment exactly:
// Custom is 0, then shorthands, inherited longhands and non-inherited longhands in
// JSON order, skipping legacy aliases. A C++ unit test compares the tables against
// the C++-generated equivalents so the two generators cannot drift.
fn generate_property_metadata(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let properties_path = manifest_dir.parent().unwrap().join("Properties.json");
    println!("cargo:rerun-if-changed={}", properties_path.display());

    let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&properties_path)?)?;
    let serde_json::Value::Object(properties) = value else {
        return Err("Properties.json does not contain a JSON object".into());
    };

    // Logical alias properties take their metadata from the first physical property of
    // their logical group, with local overrides, mirroring the C++ generator.
    let groups_path = manifest_dir.parent().unwrap().join("LogicalPropertyGroups.json");
    println!("cargo:rerun-if-changed={}", groups_path.display());
    let groups_value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&groups_path)?)?;
    let serde_json::Value::Object(groups) = groups_value else {
        return Err("LogicalPropertyGroups.json does not contain a JSON object".into());
    };
    let first_physical_in_group =
        |group_name: &str| -> Option<&str> { groups[group_name]["physical"].as_object()?.values().next()?.as_str() };
    let property_field = |name: &str, field: &str| -> Option<serde_json::Value> {
        let object = properties[name].as_object().unwrap();
        if let Some(value) = object.get(field) {
            return Some(value.clone());
        }
        let group = object.get("logical-alias-for")?.as_object()?.get("group")?.as_str()?;
        let physical = first_physical_in_group(group)?;
        properties[physical].as_object().unwrap().get(field).cloned()
    };

    let mut shorthands = Vec::new();
    let mut inherited_longhands = Vec::new();
    let mut noninherited_longhands = Vec::new();
    for (name, value) in &properties {
        let object = value.as_object().unwrap();
        if object.contains_key("legacy-alias-for") {
            continue;
        }
        // NB: The C++ generator populates the "all" shorthand's longhand list
        //     programmatically, so it has no explicit "longhands" key.
        if object.contains_key("longhands") || name == "all" {
            shorthands.push(name.clone());
        } else if property_field(name, "inherited").unwrap().as_bool().unwrap() {
            inherited_longhands.push(name.clone());
        } else {
            noninherited_longhands.push(name.clone());
        }
    }

    // Identifier assignment: Custom = 0, then the three runs in order.
    let mut ids = std::collections::HashMap::new();
    for (index, name) in shorthands
        .iter()
        .chain(&inherited_longhands)
        .chain(&noninherited_longhands)
        .enumerate()
    {
        ids.insert(name.clone(), (index + 1) as u16);
    }
    let first_longhand = ids[&inherited_longhands[0]];
    let last_longhand = ids[noninherited_longhands.last().unwrap()];
    let first_inherited = ids[&inherited_longhands[0]];
    let last_inherited = ids[inherited_longhands.last().unwrap()];

    // NB: Must match manually_specified_computation_order in
    //     Meta/Generators/generate_libweb_css_property_id.py; the parity test enforces it.
    let manual_order = [
        "math-depth",
        "font-family",
        "font-feature-settings",
        "font-kerning",
        "font-optical-sizing",
        "font-size",
        "font-style",
        "font-variant-alternates",
        "font-variant-caps",
        "font-variant-east-asian",
        "font-variant-emoji",
        "font-variant-ligatures",
        "font-variant-numeric",
        "font-variant-position",
        "font-variation-settings",
        "font-weight",
        "font-width",
        "text-rendering",
        "line-height",
        "color-scheme",
        "background-image",
        "direction",
        "writing-mode",
    ];
    let mut order = Vec::new();
    for name in manual_order {
        order.push(ids[name]);
    }
    // NB: The remainder follows Properties.json iteration order across all longhands,
    //     matching the C++ generator, not grouped by inheritance.
    for (name, value) in &properties {
        let object = value.as_object().unwrap();
        if object.contains_key("legacy-alias-for") || object.contains_key("longhands") || name == "all" {
            continue;
        }
        if !manual_order.contains(&name.as_str()) {
            order.push(ids[name]);
        }
    }

    let mut levels = vec![0u8; (last_longhand - first_longhand + 1) as usize];
    for name in inherited_longhands.iter().chain(&noninherited_longhands) {
        let requires_computation = property_field(name, "requires-computation").unwrap();
        let level = match requires_computation.as_str().unwrap() {
            "never" => 0u8,
            "cascaded-value" => 1,
            "non-inherited-value" => 2,
            "always" => 3,
            other => return Err(format!("unknown requires-computation '{other}' for {name}").into()),
        };
        levels[(ids[name] - first_longhand) as usize] = level;
    }

    let mut output = String::new();
    output.push_str("// Generated by build.rs from Properties.json. Do not edit.\n\n");
    // Shorthand expansion tables for the cascade. The "all" shorthand expands to every
    // longhand except direction and unicode-bidi, mirroring the C++ generator.
    let mut shorthand_rows = Vec::new();
    for name in &shorthands {
        let longhand_names: Vec<String> = if name == "all" {
            properties
                .iter()
                .filter(|(name, value)| {
                    let object = value.as_object().unwrap();
                    !object.contains_key("longhands")
                        && !object.contains_key("legacy-alias-for")
                        && name.as_str() != "all"
                        && name.as_str() != "direction"
                        && name.as_str() != "unicode-bidi"
                })
                .map(|(name, _)| name.clone())
                .collect()
        } else {
            properties[name]["longhands"]
                .as_array()
                .unwrap()
                .iter()
                .map(|longhand| longhand.as_str().unwrap().to_string())
                .collect()
        };
        let ids_row: Vec<u16> = longhand_names.iter().map(|longhand| ids[longhand]).collect();
        shorthand_rows.push(format!("    &{ids_row:?},"));
    }
    output.push_str(&format!(
        "pub(crate) static SHORTHAND_EXPANSIONS: [&[u16]; {}] = [\n{}\n];\n\n",
        shorthand_rows.len(),
        shorthand_rows.join("\n")
    ));
    output.push_str(&format!(
        "pub const FIRST_SHORTHAND_PROPERTY_ID: u16 = {};\n",
        ids[&shorthands[0]]
    ));
    output.push_str(&format!(
        "pub const LAST_SHORTHAND_PROPERTY_ID: u16 = {};\n\n",
        ids[shorthands.last().unwrap()]
    ));
    output.push_str("#[allow(dead_code)]\npub mod property_id {\n");
    output.push_str("    pub const CUSTOM: u16 = 0;\n");
    for name in shorthands
        .iter()
        .chain(&inherited_longhands)
        .chain(&noninherited_longhands)
    {
        let constant = name.replace('-', "_").to_uppercase();
        output.push_str(&format!("    pub const {constant}: u16 = {};\n", ids[name]));
    }
    output.push_str("}\n\n");
    output.push_str(&format!(
        "pub const FIRST_LONGHAND_PROPERTY_ID: u16 = {first_longhand};\n"
    ));
    output.push_str(&format!(
        "pub const LAST_LONGHAND_PROPERTY_ID: u16 = {last_longhand};\n"
    ));
    output.push_str(&format!(
        "pub const FIRST_INHERITED_PROPERTY_ID: u16 = {first_inherited};\n"
    ));
    output.push_str(&format!(
        "pub const LAST_INHERITED_PROPERTY_ID: u16 = {last_inherited};\n\n"
    ));
    output.push_str(&format!(
        "pub(crate) static PROPERTY_COMPUTATION_ORDER: [u16; {}] = {:?};\n\n",
        order.len(),
        order
    ));
    output.push_str(&format!(
        "pub(crate) static REQUIRES_COMPUTATION_LEVELS: [u8; {}] = {:?};\n",
        levels.len(),
        levels
    ));
    std::fs::write(out_dir.join("property_metadata_generated.rs"), output)?;
    Ok(())
}

// Generates the length unit table for the Rust style computation core from Units.json.
// Unit codes are the alphabetical index within the "length" object, matching the C++
// LengthUnit enum; absolute units carry their canonical px ratio.
fn generate_length_units(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let units_path = manifest_dir.parent().unwrap().join("Units.json");
    println!("cargo:rerun-if-changed={}", units_path.display());
    let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&units_path)?)?;
    let lengths = value["length"].as_object().ok_or("Units.json has no length object")?;

    let mut names = Vec::new();
    let mut ratios = Vec::new();
    for (name, unit) in lengths {
        names.push(name.clone());
        let object = unit.as_object().unwrap();
        if object
            .get("is-canonical-unit")
            .is_some_and(|canonical| canonical.as_bool() == Some(true))
        {
            ratios.push("1.0".to_string());
        } else if let Some(ratio) = object.get("number-of-canonical-unit") {
            ratios.push(format!("{:?}", ratio.as_f64().unwrap()));
        } else {
            ratios.push("f64::NAN".to_string());
        }
    }

    let mut output = String::new();
    output.push_str("// Generated by build.rs from Units.json. Do not edit.\n\n");
    output.push_str(&format!(
        "pub(crate) static LENGTH_UNIT_NAMES: [&str; {}] = {:?};\n\n",
        names.len(),
        names
    ));
    output.push_str(&format!(
        "pub(crate) static LENGTH_UNIT_CANONICAL_PX_RATIOS: [f64; {}] = [{}];\n",
        ratios.len(),
        ratios.join(", ")
    ));
    std::fs::write(out_dir.join("length_units_generated.rs"), output)?;

    // Canonical-unit ratios for the other dimensions, indexed by unit code in
    // JSON order like the C++ unit enums. Relative units (none exist outside
    // lengths) would be NaN.
    let mut output = String::from("// Generated by build.rs from Units.json. Do not edit.\n");
    for dimension in ["angle", "flex", "frequency", "resolution", "time"] {
        let units = value[dimension]
            .as_object()
            .ok_or_else(|| format!("Units.json has no {dimension} object"))?;
        let mut ratios = Vec::new();
        for (_, unit) in units {
            let object = unit.as_object().unwrap();
            if object
                .get("is-canonical-unit")
                .is_some_and(|canonical| canonical.as_bool() == Some(true))
            {
                ratios.push("1.0".to_string());
            } else if let Some(ratio) = object.get("number-of-canonical-unit") {
                ratios.push(format!("{:?}", ratio.as_f64().unwrap()));
            } else {
                ratios.push("f64::NAN".to_string());
            }
        }
        output.push_str(&format!(
            "\npub(crate) static {}_UNIT_CANONICAL_RATIOS: [f64; {}] = [{}];\n",
            dimension.to_uppercase(),
            ratios.len(),
            ratios.join(", ")
        ));
        let names: Vec<&str> = units.keys().map(String::as_str).collect();
        output.push_str(&format!(
            "\n#[allow(dead_code)]\npub(crate) static {}_UNIT_NAMES: [&str; {}] = {:?};\n",
            dimension.to_uppercase(),
            names.len(),
            names
        ));
    }
    std::fs::write(out_dir.join("dimension_units_generated.rs"), output)?;
    Ok(())
}

// Generates keyword codes for the Rust style computation core from Keywords.json.
// Invalid is 0 and the codes follow the array order, matching the C++ Keyword enum.
fn generate_keywords(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let keywords_path = manifest_dir.parent().unwrap().join("Keywords.json");
    println!("cargo:rerun-if-changed={}", keywords_path.display());
    let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&keywords_path)?)?;
    let keywords = value.as_array().ok_or("Keywords.json is not an array")?;

    let mut output = String::new();
    output.push_str("// Generated by build.rs from Keywords.json. Do not edit.\n\n");
    output.push_str("#[allow(dead_code)]\npub mod keyword {\n");
    output.push_str("    pub const INVALID: u16 = 0;\n");
    for (index, keyword) in keywords.iter().enumerate() {
        let name = keyword.as_str().unwrap();
        let constant = name.replace('-', "_").to_uppercase();
        output.push_str(&format!("    pub const {constant}: u16 = {};\n", index + 1));
    }
    output.push_str("}\n");
    std::fs::write(out_dir.join("keywords_generated.rs"), output)?;
    Ok(())
}

// Generates enum value codes for the Rust style computation core from Enums.json.
// Values follow the array order skipping aliases, matching the C++ enum generator.
fn generate_css_enums(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let enums_path = manifest_dir.parent().unwrap().join("Enums.json");
    println!("cargo:rerun-if-changed={}", enums_path.display());
    let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&enums_path)?)?;
    let enums = value.as_object().ok_or("Enums.json is not an object")?;

    let mut output = String::new();
    output.push_str("// Generated by build.rs from Enums.json. Do not edit.\n\n");
    for (name, values) in enums {
        let values = values.as_array().ok_or("enum values are not an array")?;
        let module = name.replace('-', "_");
        output.push_str(&format!("#[allow(dead_code)]\npub mod {module} {{\n"));
        let mut code: u8 = 0;
        for value in values {
            let value = value.as_str().ok_or("enum value is not a string")?;
            // Aliases are not included in the enum.
            if value.contains('=') {
                continue;
            }
            let constant = value.replace('-', "_").to_uppercase();
            output.push_str(&format!("    pub const {constant}: u8 = {code};\n"));
            code = code.checked_add(1).ok_or("enum has too many values for u8")?;
        }
        output.push_str("}\n\n");

        // The keyword-to-enum-value mapping, mirroring the C++ keyword_to_<enum> generator,
        // including its alias handling ("keyword=member" maps the keyword to member's value).
        let mut member_codes = std::collections::HashMap::new();
        let mut member_code: u8 = 0;
        for value in values {
            let value = value.as_str().ok_or("enum value is not a string")?;
            if value.contains('=') {
                continue;
            }
            member_codes.insert(value.to_string(), member_code);
            member_code = member_code.checked_add(1).ok_or("enum has too many values for u8")?;
        }
        output.push_str(&format!(
            "#[allow(dead_code)]\npub fn keyword_to_{module}(keyword: u16) -> Option<u8> {{\n    match keyword {{\n"
        ));
        for value in values {
            let value = value.as_str().ok_or("enum value is not a string")?;
            let (keyword_name, member_name) = match value.split_once('=') {
                Some((keyword, member)) => (keyword, member),
                None => (value, value),
            };
            let keyword_constant = keyword_name.replace('-', "_").to_uppercase();
            let code = member_codes
                .get(member_name)
                .ok_or("enum alias targets an unknown member")?;
            output.push_str(&format!("        keyword::{keyword_constant} => Some({code}),\n"));
        }
        output.push_str("        _ => None,\n    }\n}\n\n");
    }
    std::fs::write(out_dir.join("css_enums_generated.rs"), output)?;
    Ok(())
}

fn generate_ffi_header(
    config: cbindgen::Config,
    sources: &[PathBuf],
    out_dir: &Path,
    ffi_out_dir: &Path,
    header: &Path,
) {
    let builder = sources
        .iter()
        .fold(cbindgen::Builder::new().with_config(config), |builder, source| {
            builder.with_src(source)
        });
    builder.generate().map_or_else(
        |error| match error {
            cbindgen::Error::ParseSyntaxError { .. } => {}
            other => panic!("{other:?}"),
        },
        |bindings| {
            let output_header = out_dir.join(header);
            std::fs::create_dir_all(output_header.parent().unwrap()).unwrap();
            bindings.write_to_file(output_header);
            if ffi_out_dir != out_dir {
                let ffi_header = ffi_out_dir.join(header);
                std::fs::create_dir_all(ffi_header.parent().unwrap()).unwrap();
                bindings.write_to_file(ffi_header);
            }
        },
    );
}

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");
    println!("cargo:rerun-if-env-changed=FFI_OUTPUT_DIR");
    println!("cargo:rerun-if-changed=src");

    generate_selector_pseudo_types(&manifest_dir, &out_dir)?;
    generate_property_metadata(&manifest_dir, &out_dir)?;
    generate_length_units(&manifest_dir, &out_dir)?;
    generate_keywords(&manifest_dir, &out_dir)?;
    generate_css_enums(&manifest_dir, &out_dir)?;

    let ffi_out_dir = env::var("FFI_OUTPUT_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| out_dir.clone());

    let base_config = cbindgen::Config::from_file(manifest_dir.join("cbindgen.toml"))?;

    // CSS tokenizer header — namespace Web::CSS::Parser::FFI, CSS types only.
    let mut css_config = base_config.clone();
    css_config.namespaces = Some(vec![
        "Web".to_string(),
        "CSS".to_string(),
        "Parser".to_string(),
        "FFI".to_string(),
    ]);
    css_config.export.include = vec![
        "CssHashType".to_string(),
        "CssNumberType".to_string(),
        "CssToken".to_string(),
        "CssTokenType".to_string(),
    ];

    generate_ffi_header(
        css_config,
        &[manifest_dir.join("src/css_tokenizer.rs")],
        &out_dir,
        &ffi_out_dir,
        Path::new("RustFFI.h"),
    );

    // Selector matching header - namespace Web::CSS::SelectorFFI. Generate both sides of this
    // ABI from the Rust declarations so changes to layouts or signatures cannot drift silently.
    let mut selector_config = base_config.clone();
    selector_config.namespaces = Some(vec!["Web".to_string(), "CSS".to_string(), "SelectorFFI".to_string()]);
    for (rust_name, cxx_name) in [
        ("FfiSimpleSelectorType", "SimpleSelectorType"),
        ("FfiDirection", "Direction"),
        ("FfiPseudoElementValueType", "PseudoElementValueType"),
        ("FfiStringView", "StringView"),
        ("FfiSimpleSelector", "SimpleSelector"),
        ("FfiCompoundSelector", "CompoundSelector"),
        ("FfiSelector", "Selector"),
        ("FfiElement", "Element"),
        ("FfiElementQualifiedName", "ElementQualifiedName"),
        ("FfiInternedStringList", "InternedStringList"),
        ("FfiDomStringView", "DomStringView"),
        ("FfiDomAttribute", "DomAttribute"),
        ("FfiResolvedNamespaceType", "ResolvedNamespaceType"),
        ("FfiResolvedNamespace", "ResolvedNamespace"),
        ("FfiElementAndShadowHost", "ElementAndShadowHost"),
    ] {
        selector_config
            .export
            .rename
            .insert(rust_name.to_string(), cxx_name.to_string());
    }

    generate_ffi_header(
        selector_config,
        &[
            manifest_dir.join("src/selector_engine.rs"),
            manifest_dir.join("src/ffi_support.rs"),
        ],
        &out_dir,
        &ffi_out_dir,
        Path::new("SelectorRustFFI.h"),
    );

    // Style value header - namespace Web::CSS::StyleValueFFI. The StyleValueData layout is
    // exposed so converted C++ StyleValue subclasses can read variant payloads inline without
    // an FFI call.
    let mut style_value_config = base_config.clone();
    style_value_config.namespaces = Some(vec!["Web".to_string(), "CSS".to_string(), "StyleValueFFI".to_string()]);
    style_value_config.export.include = vec!["StyleValueData".to_string()];

    generate_ffi_header(
        style_value_config,
        &[
            manifest_dir.join("src/style_value.rs"),
            manifest_dir.join("src/calc.rs"),
            manifest_dir.join("src/ffi_stats.rs"),
        ],
        &out_dir,
        &ffi_out_dir,
        Path::new("StyleValueRustFFI.h"),
    );

    // Computed values header - namespace Web::CSS::ComputedValuesFFI. Exposes the style group
    // vtable and lifecycle functions; the reference count header layout is documented in
    // computed_values.rs and mirrored by StyleStructRef.
    let mut computed_values_config = base_config;
    computed_values_config.namespaces = Some(vec![
        "Web".to_string(),
        "CSS".to_string(),
        "ComputedValuesFFI".to_string(),
    ]);
    computed_values_config.export.include = vec![
        "StyleGroupVTable".to_string(),
        "STYLE_GROUP_STATIC_REFCOUNT".to_string(),
        "CascadeOrigin".to_string(),
    ];

    generate_ffi_header(
        computed_values_config,
        &[
            manifest_dir.join("src/computed_values.rs"),
            manifest_dir.join("src/property_metadata.rs"),
            manifest_dir.join("src/style_compute.rs"),
            manifest_dir.join("src/css_pixels.rs"),
            manifest_dir.join("src/cascaded_properties.rs"),
            manifest_dir.join("src/custom_properties.rs"),
        ],
        &out_dir,
        &ffi_out_dir,
        Path::new("ComputedValuesRustFFI.h"),
    );

    Ok(())
}
