#import <HTML/MessagePort.idl>

// https://webaudio.github.io/web-audio-api/#audioworkletprocessor
[Exposed=Worklet]
interface AudioWorkletProcessor {
    constructor();

    readonly attribute MessagePort port;
};
