// https://webaudio.github.io/web-audio-api/#MediaStreamAudioSourceOptions
dictionary MediaStreamAudioSourceOptions {
    required MediaStream mediaStream;
};

// https://webaudio.github.io/web-audio-api/#MediaStreamAudioSourceNode
[Exposed=Window]
interface MediaStreamAudioSourceNode : AudioNode {
    constructor (AudioContext context, MediaStreamAudioSourceOptions options);
    [SameObject] readonly attribute MediaStream mediaStream;
};
