#import <HTML/HTMLMediaElement.idl>
#import <WebAudio/AudioContext.idl>
#import <WebAudio/AudioNode.idl>
#import <WebAudio/AudioParam.idl>
#import <WebAudio/AudioParam.idl>

// https://webaudio.github.io/web-audio-api/#MediaElementAudioSourceOptions
dictionary MediaElementAudioSourceOptions {
    required HTMLMediaElement mediaElement;
};

// https://webaudio.github.io/web-audio-api/#MediaElementAudioSourceNode
[Exposed=Window]
interface MediaElementAudioSourceNode : AudioNode {
    constructor (AudioContext context, MediaElementAudioSourceOptions options);
    [SameObject] readonly attribute HTMLMediaElement mediaElement;
};
