#import <MediaCapture/MediaStreamTrack.idl>
#import <WebAudio/AudioContext.idl>

// https://webaudio.github.io/web-audio-api/#MediaStreamTrackAudioSourceNode
[Exposed=Window]
interface MediaStreamTrackAudioSourceNode : AudioNode {
    constructor (AudioContext context, MediaStreamTrackAudioSourceOptions options);
};

dictionary MediaStreamTrackAudioSourceOptions {
    required MediaStreamTrack mediaStreamTrack;
};
