#import <DOM/Event.idl>
#import <WebAudio/AudioBuffer.idl>

// https://webaudio.github.io/web-audio-api/#OfflineAudioCompletionEvent
[Exposed=Window]
interface OfflineAudioCompletionEvent : Event {
    constructor(DOMString type, OfflineAudioCompletionEventInit eventInitDict);
    readonly attribute AudioBuffer renderedBuffer;
};

// https://webaudio.github.io/web-audio-api/#OfflineAudioCompletionEventInit
dictionary OfflineAudioCompletionEventInit : EventInit {
    required AudioBuffer renderedBuffer;
};
