// https://webaudio.github.io/web-audio-api/#OfflineAudioContextOptions
dictionary OfflineAudioContextOptions {
    unsigned long numberOfChannels = 1;
    required unsigned long length;
    required float sampleRate;
    // FIXME: (AudioContextRenderSizeCategory or unsigned long) renderSizeHint = "default";
};

// https://webaudio.github.io/web-audio-api/#OfflineAudioContext
[Exposed=Window]
interface OfflineAudioContext : BaseAudioContext {
    constructor(OfflineAudioContextOptions contextOptions);
    constructor(unsigned long numberOfChannels, unsigned long length, float sampleRate);
    [CreatesPromise, NeedsThisObjectRealm] Promise<AudioBuffer> startRendering();
    [CreatesPromise] Promise<undefined> resume();
    [CreatesPromise] Promise<undefined> suspend(double suspendTime);
    readonly attribute unsigned long length;
    attribute EventHandler oncomplete;
};
