#import <Credentials/Credential.idl>
#import <DOM/AbortSignal.idl>

// https://www.w3.org/TR/credential-management-1/#framework-credential-management
[Exposed=Window, SecureContext]
interface CredentialsContainer {
    Promise<Credential?> get(optional CredentialRequestOptions options = {});
    [FIXME] Promise<undefined> store(Credential credential);
    [FIXME] Promise<Credential?> create(optional CredentialCreationOptions options = {});
    [FIXME] Promise<undefined> preventSilentAccess();
};

dictionary CredentialRequestOptions {
    CredentialMediationRequirement mediation = "optional";
    AbortSignal signal;
};

enum CredentialMediationRequirement {
    "silent",
    "optional",
    "conditional",
    "required"
};

dictionary CredentialCreationOptions {
    CredentialMediationRequirement mediation = "optional";
    AbortSignal signal;
};
