#import <Credentials/CredentialsContainer.idl>

// FIXME: This is a partial interface not an interface mixin
// https://www.w3.org/TR/credential-management-1/#framework-credential-management
interface mixin NavigatorCredentialsContainer {
    [SecureContext, SameObject] readonly attribute CredentialsContainer credentials;
};
