#import <CSS/CSSNumericValue.idl>

// https://drafts.csswg.org/web-animations-2/#the-animationtimeline-interface
[Exposed=Window]
interface AnimationTimeline {
    readonly attribute double? currentTime;
    [ImplementedAs=duration_for_bindings] readonly attribute CSSNumberish? duration;
    [FIXME] Animation play (optional AnimationEffect? effect = null);
};
