// https://drafts.csswg.org/web-animations-1/#dictdef-documenttimelineoptions
dictionary DocumentTimelineOptions {
    DOMHighResTimeStamp originTime = 0;
};

// https://drafts.csswg.org/web-animations-1/#documenttimeline
[Exposed=Window]
interface DocumentTimeline : AnimationTimeline {
    constructor(optional DocumentTimelineOptions options = {});
};
