// https://drafts.csswg.org/web-animations-1/#the-compositeoperation-enumeration
enum CompositeOperation { "replace", "add", "accumulate" };

// https://drafts.csswg.org/web-animations-1/#enumdef-compositeoperationorauto
enum CompositeOperationOrAuto { "replace", "add", "accumulate", "auto" };

// https://drafts.csswg.org/web-animations-1/#the-keyframeeffectoptions-dictionary
dictionary KeyframeEffectOptions : EffectTiming {
    CompositeOperation composite = "replace";
    CSSOMString? pseudoElement = null;
};

// https://drafts.csswg.org/web-animations-1/#the-keyframeeffect-interface
[Exposed=Window]
interface KeyframeEffect : AnimationEffect {
    constructor(Element? target, object? keyframes, optional (unrestricted double or KeyframeEffectOptions) options = {});
    constructor(KeyframeEffect source);

    attribute Element? target;
    attribute CSSOMString? pseudoElement;
    attribute CompositeOperation composite;
    [NeedsCallerRealm] sequence<object> getKeyframes();
    [ImplementedAs=set_keyframes_from_js, NeedsCallerRealm] undefined setKeyframes(object? keyframes);
};
