/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Writes LibJS/Embedding/ABI.h, the C declarations of the embedding ABI, with cbindgen from src/embedding alone.

use std::fs;
use std::io;
use std::path::Path;

/// The C types that LibJS/HostObjectABI.h defines, which the generated header includes rather than declares again.
const TYPES_FROM_HOST_OBJECT_ABI_HEADER: &[&str] = &[
    "JSValue",
    "JSPropertyKey",
    "JSCompletion",
    "JSObject",
    "JSVM",
    "JSModule",
    "JSPromiseCapability",
    "JSGetCacheMetadata",
    "JSSetCacheMetadata",
    "JSPropertyDescriptor",
    "JSValueSink",
    "JSStringSink",
    "JSHostObjectHooks",
    "JSHostFunctionHooks",
    "JSHostArrayHooks",
    "JSResolvedBinding",
    "JSHostModuleHooks",
    "JSHostClass",
];

fn configuration() -> cbindgen::Config {
    let mut configuration = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        header: Some(
            "/*\n * Copyright (c) 2026-present, the Ladybird developers.\n *\n * SPDX-License-Identifier: BSD-2-Clause\n */"
                .to_string(),
        ),
        include_guard: Some("LIBJS_EMBEDDING_ABI_H".to_string()),
        autogen_warning: Some(
            "// Generated by the libjs_runtime_rust build script from src/embedding -- DO NOT EDIT".to_string(),
        ),
        no_includes: true,
        sys_includes: vec!["LibJS/HostObjectABI.h".to_string()],
        documentation_style: cbindgen::DocumentationStyle::C99,
        line_length: 120,
        tab_width: 4,
        usize_is_size_t: true,
        ..Default::default()
    };
    configuration.export.exclude = TYPES_FROM_HOST_OBJECT_ABI_HEADER
        .iter()
        .map(|name| name.to_string())
        .collect();
    configuration
}

/// Parses the embedding module, whose mod.rs leads cbindgen to every file under it, and writes the header to `output`
/// if it changed.
pub fn generate(embedding_module: &Path, output: &Path) {
    match cbindgen::Builder::new()
        .with_config(configuration())
        .with_src(embedding_module)
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file(output);
        }
        // The build script does not fail here, so that rustc reports a syntax error it shares with cbindgen in its own
        // words. Removing the header of the previous build keeps it from being copied out in place of the new one when
        // only cbindgen rejects the code.
        Err(error @ cbindgen::Error::ParseSyntaxError { .. }) => {
            println!("cargo:warning=cbindgen could not parse src/embedding, so it wrote no ABI.h: {error}");
            if let Err(remove_error) = fs::remove_file(output)
                && remove_error.kind() != io::ErrorKind::NotFound
            {
                panic!("remove the outdated {}: {remove_error}", output.display());
            }
        }
        Err(error) => panic!("cbindgen failed to generate {}: {error}", output.display()),
    }
}
