/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

//! Writes a #[repr(C)] view of every bytecode instruction, laid out as flapc lays it out, and the Values record of
//! every instruction whose slow path receives one. Each offset flapc computed is asserted on the generated type.

use std::collections::BTreeSet;
use std::fmt::Write;

use flapc::metadata::{InstructionDefinition, SlowPathLayout, field_type_info};

const RUST_KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "do", "dyn", "else", "enum",
    "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "macro", "match", "mod", "move",
    "mut", "override", "priv", "pub", "ref", "return", "static", "struct", "trait", "true", "try", "type", "typeof",
    "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

pub fn rust_identifier(name: &str) -> String {
    if RUST_KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

/// The Rust name of a bytecode field, which C++ prefixes with m_.
pub fn field_name(name: &str) -> String {
    rust_identifier(name.strip_prefix("m_").unwrap_or(name))
}

fn rust_type(ty: &str) -> String {
    match ty {
        "Operand" => "Operand".to_string(),
        "Optional<Operand>" => "OptionalOperand".to_string(),
        "Label" => "Label".to_string(),
        "Optional<Label>" => "OptionalLabel".to_string(),
        "IdentifierTableIndex" | "PropertyKeyTableIndex" | "StringTableIndex" | "RegexTableIndex" => ty.to_string(),
        "Optional<IdentifierTableIndex>" => "OptionalIndex<IdentifierTableIndex>".to_string(),
        "Optional<StringTableIndex>" => "OptionalIndex<StringTableIndex>".to_string(),
        "EnvironmentCoordinate" => "EnvironmentCoordinate".to_string(),
        "Value" => "Value".to_string(),
        "Builtin" => "u8".to_string(),
        _ => {
            let info = field_type_info(ty);
            match info.kind {
                "bool" | "u8" | "i32" | "u32" | "u64" => info.kind.to_string(),
                other => panic!("no Rust view for bytecode field type {ty} ({other})"),
            }
        }
    }
}

pub fn generate(ops: &[InstructionDefinition], ops_with_values: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("// Generated by the libjs_runtime_rust build script -- DO NOT EDIT\n\n");

    for op in ops {
        if op.name == "Instruction" {
            continue;
        }
        let _ = writeln!(
            out,
            "#[repr(C)]\npub struct {} {{\n    pub header: InstructionHeader,",
            op.name
        );
        let mut assertions = String::new();
        for field in &op.fields {
            if field.name == "m_type" || field.name == "m_strict" {
                continue;
            }
            let name = field_name(&field.name);
            let ty = rust_type(&field.ty);
            if field.is_array {
                let _ = writeln!(out, "    pub {name}: [{ty}; 0],");
            } else {
                let _ = writeln!(out, "    pub {name}: {ty},");
            }
            let offset = op.layout.field_offsets[&field.name];
            let _ = writeln!(
                assertions,
                "const _: () = assert!(core::mem::offset_of!({}, {name}) == {offset});",
                op.name
            );
        }
        out.push_str("}\n");
        out.push_str(&assertions);
        match (op.layout.size, op.layout.m_length_offset) {
            (Some(size), _) => {
                let _ = writeln!(
                    out,
                    "impl {} {{\n    /// The instruction's size in the bytecode, as C++ sizeof(Op::{}).\n    pub const LENGTH: u32 = {size};\n\n    pub fn length(&self) -> u32 {{\n        Self::LENGTH\n    }}\n}}",
                    op.name, op.name
                );
            }
            (None, Some(_)) => {
                let _ = writeln!(
                    out,
                    "impl {} {{\n    /// The instruction's size in the bytecode, which it records itself.\n    pub fn length(&self) -> u32 {{\n        self.length\n    }}\n}}",
                    op.name
                );
            }
            (None, None) => panic!("{} has neither a fixed size nor a length field", op.name),
        }

        if ops_with_values.contains(&op.name) {
            let layout = SlowPathLayout::new(op);
            let _ = writeln!(out, "#[repr(C)]\npub struct {}Values {{", op.name);
            let mut assertions = String::new();
            for field in &layout.fields {
                let name = field_name(&field.name);
                let _ = writeln!(out, "    pub {name}: Value,");
                let _ = writeln!(
                    assertions,
                    "const _: () = assert!(core::mem::offset_of!({}Values, {name}) == {});",
                    op.name, field.value_offset
                );
            }
            if let Some(array) = &layout.array {
                let _ = writeln!(out, "    pub {}: [Value; 0],", field_name(&array.name));
            }
            out.push_str("}\n");
            out.push_str(&assertions);
        }
        out.push('\n');
    }
    out
}
