/*
 * Copyright (c) 2026-present, the Ladybird developers.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

use std::env;
use std::error::Error;
use std::fmt::Write;
use std::path::{Path, PathBuf};

// Mirrors title_casify() in Meta/Utils/utils.py.
fn title_casify(dashy_name: &str) -> String {
    dashy_name
        .split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let first = chars.next().unwrap().to_ascii_uppercase();
            format!("{first}{}", chars.as_str())
        })
        .collect()
}

fn ordered_pseudo_element_names(
    pseudo_elements: &serde_json::Map<String, serde_json::Value>,
) -> Result<Vec<String>, Box<dyn Error>> {
    let mut synthetic = Vec::new();
    let mut element_reference = Vec::new();
    let mut functional = Vec::new();
    for (name, value) in pseudo_elements {
        let object = value.as_object().unwrap();
        if object.contains_key("alias-for") {
            continue;
        }
        if object.get("type").and_then(|value| value.as_str()) == Some("function") {
            functional.push(name.clone());
            continue;
        }
        match object.get("implementation").and_then(|value| value.as_str()) {
            Some("synthetic") => synthetic.push(name.clone()),
            Some("element-reference") => element_reference.push(name.clone()),
            other => return Err(format!("invalid or missing implementation type for ::{name}: {other:?}").into()),
        }
    }
    synthetic.extend(element_reference);
    synthetic.extend(functional);
    Ok(synthetic)
}

fn load_property_groups(path: &Path) -> Result<std::collections::HashMap<String, Vec<String>>, Box<dyn Error>> {
    let mut groups = std::collections::HashMap::new();
    let mut current_group = None;
    for raw_line in std::fs::read_to_string(path)?.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(group) = line.strip_prefix('[').and_then(|line| line.strip_suffix(']')) {
            groups.insert(format!("#{group}"), Vec::new());
            current_group = Some(format!("#{group}"));
            continue;
        }
        let Some(group) = current_group.as_ref() else {
            return Err(format!("property outside a pseudo-element property group: {line}").into());
        };
        groups.get_mut(group).unwrap().push(line.to_string());
    }
    Ok(groups)
}

fn write_enum_and_from_ffi(output: &mut String, enum_name: &str, variants: &[String]) {
    writeln!(output, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]").unwrap();
    writeln!(output, "#[repr(u8)]").unwrap();
    writeln!(output, "pub enum {enum_name} {{").unwrap();
    for variant in variants {
        writeln!(output, "    {variant},").unwrap();
    }
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
    let fn_name = if enum_name == "PseudoClassType" {
        "pseudo_class_from_ffi"
    } else {
        "pseudo_element_from_ffi"
    };
    writeln!(output, "fn {fn_name}(value: u8) -> {enum_name} {{").unwrap();
    writeln!(output, "    match value {{").unwrap();
    for (index, variant) in variants.iter().enumerate() {
        writeln!(output, "        {index} => {enum_name}::{variant},").unwrap();
    }
    writeln!(output, "        _ => panic!(\"invalid {enum_name} {{value}}\"),").unwrap();
    writeln!(output, "    }}").unwrap();
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
}

fn generate_style_engine_event_kinds(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let specification_path = manifest_dir.join("StyleEngineBoundary.json");
    println!("cargo:rerun-if-changed={}", specification_path.display());
    let specification: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&specification_path)?)?;
    let events = specification["events"]
        .as_array()
        .ok_or("StyleEngineBoundary.json does not contain an events array")?;

    let mut event_kind = String::from(
        "// Generated by build.rs from StyleEngineBoundary.json.\n\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
         #[repr(u16)]\n\
         pub enum EventKind {\n",
    );
    let mut all_event_kinds = String::from("}\n\npub const ALL_EVENT_KINDS: &[EventKind] = &[\n");
    let mut decode =
        String::from("\nimpl EventKind {\n    fn decode(raw: u64) -> Result<Self, Error> {\n        match raw {\n");
    let mut stub = String::from(
        "// Generated by build.rs from StyleEngineBoundary.json.\n\n\
         #[allow(dead_code)]\n\
         pub enum EventKind {\n",
    );
    let mut previous_id = 0;
    let mut names = std::collections::HashSet::new();
    for event in events {
        let fields = event.as_array().ok_or("event entry is not an array")?;
        if fields.len() != 2 {
            return Err("event entry must contain an ID and name".into());
        }
        let id = fields[0].as_u64().ok_or("event ID is not an unsigned integer")?;
        let name = fields[1].as_str().ok_or("event name is not a string")?;
        if id <= previous_id {
            return Err("event IDs must be strictly increasing and never reused".into());
        }
        if !names.insert(name) {
            return Err(format!("duplicate event name {name}").into());
        }
        writeln!(event_kind, "    {name} = {id},")?;
        writeln!(all_event_kinds, "    EventKind::{name},")?;
        writeln!(decode, "            {id} => Ok(Self::{name}),")?;
        writeln!(stub, "    {name},")?;
        previous_id = id;
    }
    event_kind.push_str(&all_event_kinds);
    event_kind.push_str("];\n");
    event_kind.push_str(&decode);
    event_kind.push_str("            _ => Err(Error::UnknownEvent(raw)),\n        }\n    }\n}\n");
    stub.push_str("}\n");
    std::fs::write(out_dir.join("style_engine_event_kind_generated.rs"), event_kind)?;
    std::fs::write(out_dir.join("style_engine_event_kind_stub_generated.rs"), stub)?;
    Ok(())
}

fn boundary_string<'a>(
    object: &'a serde_json::Map<String, serde_json::Value>,
    field: &str,
) -> Result<&'a str, Box<dyn Error>> {
    object
        .get(field)
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| format!("boundary operation is missing string field {field}").into())
}

fn boundary_type_names(kind: &str) -> Result<(&'static str, &'static str, &'static str, &'static str), Box<dyn Error>> {
    match kind {
        "bool" => Ok(("bool", "bool", "write_bool", "read_bool")),
        "cascade_origin" => Ok((
            "FfiCascadeOrigin",
            "StyleEngineFFI::FfiCascadeOrigin",
            "write_u8",
            "read_cascade_origin",
        )),
        "u8" => Ok(("u8", "u8", "write_u8", "read_u8")),
        "u32" => Ok(("u32", "u32", "write_u32", "read_u32")),
        "sheet_id" => Ok(("u32", "SheetID", "write_u32", "read_u32")),
        "style_atom" => Ok(("u32", "StyleAtomID", "write_u32", "read_u32")),
        "style_node" => Ok(("u32", "StyleNodeID", "write_u32", "read_u32")),
        "style_rule_id" => Ok(("u32", "StyleEngineRuleID", "write_u32", "read_u32")),
        "tree_scope_id" => Ok(("u32", "TreeScopeID", "write_u32", "read_u32")),
        "u64" => Ok(("u64", "u64", "write_u64", "read_u64")),
        "style_record" => Ok(("u64", "StyleRecordID", "write_u64", "read_u64")),
        "usize_u64" => Ok(("usize", "size_t", "write_u64", "read_u64")),
        "u16_slice" => Ok(("*const u16", "ReadonlySpan<u16>", "write_u16_slice", "read_u16_vec")),
        "u32_slice" => Ok(("*const u32", "ReadonlySpan<u32>", "write_u32_slice", "read_u32_vec")),
        "style_atom_slice" => Ok((
            "*const u32",
            "ReadonlySpan<StyleAtomID>",
            "write_u32_slice",
            "read_u32_vec",
        )),
        "style_node_slice" => Ok((
            "*const u32",
            "ReadonlySpan<StyleNodeID>",
            "write_u32_slice",
            "read_u32_vec",
        )),
        _ => Err(format!("unknown boundary type {kind}").into()),
    }
}

fn generate_style_engine_boundary(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let specification_path = manifest_dir.join("StyleEngineBoundary.json");
    let specification: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&specification_path)?)?;
    let operations = specification["operations"]
        .as_array()
        .ok_or("StyleEngineBoundary.json does not contain an operations array")?;
    let declared_events = specification["events"]
        .as_array()
        .ok_or("StyleEngineBoundary.json does not contain an events array")?
        .iter()
        .map(|event| {
            event
                .as_array()
                .and_then(|fields| fields.get(1))
                .and_then(serde_json::Value::as_str)
                .ok_or_else(|| "event entry must contain a string name".into())
        })
        .collect::<Result<std::collections::BTreeSet<_>, Box<dyn Error>>>()?;
    let bespoke_events = specification["bespoke_events"]
        .as_array()
        .ok_or("StyleEngineBoundary.json does not contain a bespoke_events array")?
        .iter()
        .map(|event| {
            event
                .as_str()
                .ok_or_else(|| "bespoke event name is not a string".into())
        })
        .collect::<Result<std::collections::BTreeSet<_>, Box<dyn Error>>>()?;

    let mut rust = String::from("// Generated by build.rs from StyleEngineBoundary.json.\n\n");
    let mut replay = String::from(
        "// Generated by build.rs from StyleEngineBoundary.json.\n\n\
         fn replay_generated_boundary_event(\n\
             kind: EventKind,\n\
             payload: &mut PayloadReader<'_>,\n\
             live_engines: &[Option<*mut c_void>],\n\
         ) -> Result<bool, Box<dyn std::error::Error>> {\n\
             match kind {\n",
    );
    let mut cpp_declarations =
        String::from("// Generated by Libraries/LibWeb/Rust/build.rs from StyleEngineBoundary.json.\n");
    let mut cpp_definitions =
        String::from("// Generated by Libraries/LibWeb/Rust/build.rs from StyleEngineBoundary.json.\n\n");
    let mut ffi_names = std::collections::HashSet::new();
    let mut operation_events = std::collections::HashSet::new();

    for operation in operations {
        let object = operation.as_object().ok_or("boundary operation is not an object")?;
        let event = boundary_string(object, "event")?;
        let ffi = boundary_string(object, "ffi")?;
        let return_kind = boundary_string(object, "return")?;
        let body = boundary_string(object, "body")?;
        let receiver = object
            .get("receiver")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("mut");
        let cpp_const = object
            .get("cpp_const")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or(receiver == "const");
        if !ffi_names.insert(ffi) {
            return Err(format!("duplicate boundary function {ffi}").into());
        }
        if !operation_events.insert(event) {
            return Err(format!("duplicate generated boundary event {event}").into());
        }
        let arguments = object["args"]
            .as_array()
            .ok_or("boundary operation args is not an array")?;
        let mut parsed_arguments = Vec::new();
        for argument in arguments {
            let fields = argument.as_array().ok_or("boundary argument is not an array")?;
            if fields.len() != 2 {
                return Err("boundary argument must contain a name and type".into());
            }
            let name = fields[0].as_str().ok_or("boundary argument name is not a string")?;
            let kind = fields[1].as_str().ok_or("boundary argument type is not a string")?;
            let names = boundary_type_names(kind)?;
            parsed_arguments.push((name, kind, names));
        }
        let recorded_arguments = match object.get("record_order") {
            Some(order) => {
                let order = order.as_array().ok_or("boundary record_order is not an array")?;
                if order.len() != parsed_arguments.len() {
                    return Err("boundary record_order must contain every argument".into());
                }
                let mut seen = std::collections::HashSet::new();
                order
                    .iter()
                    .map(|name| {
                        let name = name.as_str().ok_or("boundary record_order name is not a string")?;
                        if !seen.insert(name) {
                            return Err(format!("duplicate boundary record_order argument {name}").into());
                        }
                        parsed_arguments
                            .iter()
                            .find(|argument| argument.0 == name)
                            .ok_or_else(|| format!("unknown boundary record_order argument {name}").into())
                    })
                    .collect::<Result<Vec<_>, Box<dyn Error>>>()?
            }
            None => parsed_arguments.iter().collect(),
        };
        let (rust_return, cpp_return, result_writer, result_reader) = match return_kind {
            "void" => ("", "void", "", ""),
            other => {
                let (rust_type, cpp_type, writer, reader) = boundary_type_names(other)?;
                (rust_type, cpp_type, writer, reader)
            }
        };
        let engine_type = if receiver == "const" {
            "*const c_void"
        } else {
            "*mut c_void"
        };
        let engine_borrow = if receiver == "const" {
            "&*engine.cast::<StyleEngine>()"
        } else {
            "&mut *engine.cast::<StyleEngine>()"
        };

        writeln!(
            rust,
            "/// Generated from the StyleEngine boundary specification.\n///\n/// # Safety\n/// `engine` and every borrowed argument must be live for this call.\n#[unsafe(no_mangle)]"
        )?;
        write!(rust, "pub unsafe extern \"C\" fn {ffi}(engine: {engine_type}")?;
        for (name, kind, (rust_type, _, _, _)) in &parsed_arguments {
            write!(rust, ", {name}: {rust_type}")?;
            if kind.ends_with("_slice") {
                write!(rust, ", {name}_count: usize")?;
            }
        }
        if return_kind != "void" {
            writeln!(rust, ") -> {rust_return} {{")?;
        } else {
            rust.push_str(") {\n");
        }
        writeln!(
            rust,
            "    abort_on_panic(|| {{\n        let engine = unsafe {{ {engine_borrow} }};"
        )?;
        for (name, kind, (rust_type, _, _, _)) in &parsed_arguments {
            if kind.ends_with("_slice") {
                let element_type = rust_type.trim_start_matches("*const ");
                writeln!(
                    rust,
                    "        let recorded_{name}: &[{element_type}] = if {name}_count == 0 || {name}.is_null() {{ &[] }} else {{ unsafe {{ std::slice::from_raw_parts({name}, {name}_count) }} }};"
                )?;
                writeln!(rust, "        let {name} = recorded_{name};")?;
            } else {
                writeln!(rust, "        let recorded_{name} = {name};")?;
            }
        }
        writeln!(rust, "        {body}")?;
        let payload_name = if parsed_arguments.is_empty() && return_kind == "void" {
            "_"
        } else {
            "payload"
        };
        writeln!(
            rust,
            "        engine.record_boundary_call(EventKind::{event}, |{payload_name}| {{"
        )?;
        for (name, kind, (_, _, writer, _)) in &recorded_arguments {
            if *kind == "cascade_origin" {
                writeln!(rust, "            payload.{writer}(recorded_{name} as u8);")?;
            } else if *kind == "usize_u64" {
                writeln!(
                    rust,
                    "            payload.{writer}(u64::try_from(recorded_{name}).expect(\"boundary value exceeds u64\"));"
                )?;
            } else {
                writeln!(rust, "            payload.{writer}(recorded_{name});")?;
            }
        }
        if return_kind != "void" {
            if return_kind == "usize_u64" {
                writeln!(
                    rust,
                    "            payload.{result_writer}(u64::try_from(result).expect(\"boundary result exceeds u64\"));"
                )?;
            } else {
                writeln!(rust, "            payload.{result_writer}(result);")?;
            }
        }
        rust.push_str("        });\n");
        if return_kind != "void" {
            rust.push_str("        result\n");
            rust.push_str("    })\n}\n\n");
        } else {
            rust.push_str("    });\n}\n\n");
        }

        let generate_replay = object
            .get("replay")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or(true);
        if generate_replay {
            writeln!(replay, "        EventKind::{event} => {{")?;
            writeln!(replay, "            let engine = read_engine(payload, live_engines)?;")?;
            for (name, kind, (_, _, _, reader)) in &recorded_arguments {
                if *kind == "cascade_origin" {
                    writeln!(replay, "            let {name} = {reader}(payload)?;")?;
                } else {
                    writeln!(replay, "            let {name} = payload.{reader}()?;")?;
                }
            }
            if return_kind == "void" {
                write!(replay, "            unsafe {{ bridge::{ffi}(engine")?;
            } else {
                write!(replay, "            let actual = unsafe {{ bridge::{ffi}(engine")?;
            }
            for (name, kind, _) in &parsed_arguments {
                if kind.ends_with("_slice") {
                    write!(replay, ", {name}.as_ptr(), {name}.len()")?;
                } else {
                    write!(replay, ", {name}")?;
                }
            }
            replay.push_str(") };\n");
            if return_kind != "void" {
                writeln!(replay, "            let expected = payload.{result_reader}()?;")?;
                writeln!(
                    replay,
                    "            if actual != expected {{ return Err(format!(\"{ffi} diverged: expected {{expected:?}}, got {{actual:?}}\").into()); }}"
                )?;
            }
            replay.push_str("            Ok(true)\n        }\n");
        }

        let Some(cpp) = object.get("cpp").and_then(serde_json::Value::as_str) else {
            continue;
        };
        let cpp_result = object.get("cpp_result").and_then(serde_json::Value::as_str);
        let cpp_return = match cpp_result {
            Some("optional_u32") => "Optional<u32>",
            Some(other) => return Err(format!("unknown C++ boundary result {other}").into()),
            None => cpp_return,
        };
        if return_kind != "void" {
            cpp_declarations.push_str("[[nodiscard]] ");
        }
        write!(cpp_declarations, "{cpp_return} {cpp}(")?;
        for (index, (name, _, (_, cpp_type, _, _))) in parsed_arguments.iter().enumerate() {
            if index != 0 {
                cpp_declarations.push_str(", ");
            }
            write!(cpp_declarations, "{cpp_type} {name}")?;
        }
        if cpp_const {
            cpp_declarations.push_str(") const;\n");
        } else {
            cpp_declarations.push_str(");\n");
        }

        write!(cpp_definitions, "{cpp_return} StyleEngine::{cpp}(")?;
        for (index, (name, _, (_, cpp_type, _, _))) in parsed_arguments.iter().enumerate() {
            if index != 0 {
                cpp_definitions.push_str(", ");
            }
            write!(cpp_definitions, "{cpp_type} {name}")?;
        }
        if cpp_const {
            cpp_definitions.push_str(") const\n{\n");
        } else {
            cpp_definitions.push_str(")\n{\n");
        }
        if cpp_result == Some("optional_u32") {
            cpp_definitions.push_str("    auto result = ");
        } else if return_kind != "void" {
            if matches!(
                return_kind,
                "sheet_id" | "style_atom" | "style_node" | "style_rule_id" | "tree_scope_id"
            ) {
                write!(cpp_definitions, "    return {cpp_return} {{ ")?;
            } else {
                cpp_definitions.push_str("    return ");
            }
        } else {
            cpp_definitions.push_str("    ");
        }
        write!(cpp_definitions, "StyleEngineFFI::{ffi}(m_impl")?;
        for (name, kind, _) in &parsed_arguments {
            if matches!(
                *kind,
                "sheet_id" | "style_atom" | "style_node" | "style_record" | "style_rule_id" | "tree_scope_id"
            ) {
                write!(cpp_definitions, ", {name}.value()")?;
            } else if matches!(*kind, "style_atom_slice" | "style_node_slice") {
                write!(
                    cpp_definitions,
                    ", reinterpret_cast<u32 const*>({name}.data()), {name}.size()"
                )?;
            } else if kind.ends_with("_slice") {
                write!(cpp_definitions, ", {name}.data(), {name}.size()")?;
            } else {
                write!(cpp_definitions, ", {name}")?;
            }
        }
        if matches!(
            return_kind,
            "sheet_id" | "style_atom" | "style_node" | "style_rule_id" | "tree_scope_id"
        ) {
            cpp_definitions.push_str(") };\n");
        } else {
            cpp_definitions.push_str(");\n");
        }
        if cpp_result == Some("optional_u32") {
            cpp_definitions.push_str("    if (result == 0)\n        return {};\n    return result;\n");
        }
        cpp_definitions.push_str("}\n\n");
    }

    replay.push_str("        _ => Ok(false),\n    }\n}\n");
    let generated_events = operation_events.into_iter().collect::<std::collections::BTreeSet<_>>();
    if !generated_events.is_disjoint(&bespoke_events) {
        return Err("boundary event cannot be both generated and bespoke".into());
    }
    let covered_events = generated_events.union(&bespoke_events).copied().collect();
    if declared_events != covered_events {
        return Err("every boundary event must be generated or explicitly bespoke".into());
    }
    std::fs::write(out_dir.join("style_engine_boundary_generated.rs"), rust)?;
    std::fs::write(out_dir.join("style_engine_replay_generated.rs"), replay)?;
    std::fs::write(out_dir.join("StyleEngineBridgeGenerated.h"), cpp_declarations)?;
    std::fs::write(out_dir.join("StyleEngineBridgeGenerated.inc"), cpp_definitions)?;
    Ok(())
}

// Generates the Rust twins of the C++ PseudoClass and PseudoElement enums from the same JSON
// sources as Meta/Generators/generate_libweb_css_pseudo_{class,element}.py, so the numeric
// values that cross the selector FFI cannot drift out of sync with the C++ side.
fn generate_selector_pseudo_types(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let css_dir = manifest_dir.parent().unwrap().join("CSS");
    let pseudo_classes_path = css_dir.join("PseudoClasses.json");
    let pseudo_elements_path = css_dir.join("PseudoElements.json");
    println!("cargo:rerun-if-changed={}", pseudo_classes_path.display());
    println!("cargo:rerun-if-changed={}", pseudo_elements_path.display());

    let parse_object = |path: &Path| -> Result<serde_json::Map<String, serde_json::Value>, Box<dyn Error>> {
        let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(path)?)?;
        match value {
            serde_json::Value::Object(object) => Ok(object),
            _ => Err(format!("{} does not contain a JSON object", path.display()).into()),
        }
    };

    let pseudo_classes = parse_object(&pseudo_classes_path)?;
    let pseudo_class_names = pseudo_classes
        .iter()
        .filter(|(_, value)| !value.as_object().unwrap().contains_key("legacy-alias-for"))
        .map(|(name, _)| title_casify(name))
        .collect::<Vec<_>>();
    let mut state_fact_names = pseudo_classes
        .iter()
        .filter(|(_, value)| value["style-engine-state"].as_bool() == Some(true))
        .map(|(name, _)| title_casify(name))
        .collect::<Vec<_>>();
    // NB: FfiStateFact discriminants persist in replay streams. PopoverOpen historically follows
    //     Playing, so preserve that ordering at the compatibility boundary.
    if let Some(popover_open) = state_fact_names.iter().position(|name| name == "PopoverOpen") {
        let popover_open = state_fact_names.remove(popover_open);
        let playing = state_fact_names
            .iter()
            .position(|name| name == "Playing")
            .expect("PopoverOpen requires Playing in the state fact catalog");
        state_fact_names.insert(playing + 1, popover_open);
    }

    let pseudo_elements = parse_object(&pseudo_elements_path)?;
    let mut pseudo_element_names = ordered_pseudo_element_names(&pseudo_elements)?
        .iter()
        .map(|name| title_casify(name))
        .collect::<Vec<_>>();
    // NB: The C++ generator emits UnknownWebKit after KnownPseudoElementCount, so its FFI value is
    //     the number of known pseudo-elements.
    pseudo_element_names.push("UnknownWebKit".to_string());

    let mut output = String::new();
    writeln!(
        output,
        "// Generated by build.rs from CSS/PseudoClasses.json and CSS/PseudoElements.json."
    )
    .unwrap();
    writeln!(output).unwrap();
    write_enum_and_from_ffi(&mut output, "PseudoClassType", &pseudo_class_names);
    write_enum_and_from_ffi(&mut output, "PseudoElementType", &pseudo_element_names);

    std::fs::write(out_dir.join("selector_pseudo_generated.rs"), output)?;

    let mut state_facts = String::from(
        "// Generated by build.rs from CSS/PseudoClasses.json.\n\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]\n\
         #[repr(u8)]\n\
         pub enum StateFact {\n",
    );
    for name in &state_fact_names {
        writeln!(state_facts, "    {name},")?;
    }
    writeln!(state_facts, "}}\n\nimpl StateFact {{")?;
    writeln!(state_facts, "    pub const ALL: [Self; {}] = [", state_fact_names.len())?;
    for name in &state_fact_names {
        writeln!(state_facts, "        Self::{name},")?;
    }
    state_facts.push_str("    ];\n}\n");
    std::fs::write(out_dir.join("style_state_fact_generated.rs"), state_facts)?;

    let mut compiler_mapping = String::from(
        "// Generated by build.rs from CSS/PseudoClasses.json.\n\n\
         fn state_fact_for(pseudo_class: PseudoClassType) -> Option<StateFact> {\n\
         \x20   match pseudo_class {\n",
    );
    for name in &state_fact_names {
        writeln!(
            compiler_mapping,
            "        PseudoClassType::{name} => Some(StateFact::{name}),"
        )?;
    }
    compiler_mapping.push_str("        _ => None,\n    }\n}\n");
    std::fs::write(out_dir.join("style_state_fact_compiler_generated.rs"), compiler_mapping)?;

    let mut ffi_state_facts = String::from(
        "// Generated by build.rs from CSS/PseudoClasses.json.\n\n\
         #[derive(Clone, Copy, PartialEq, Eq)]\n\
         #[repr(u8)]\n\
         pub enum FfiStateFact {\n",
    );
    for (index, name) in state_fact_names.iter().enumerate() {
        writeln!(ffi_state_facts, "    {name} = {index},")?;
    }
    ffi_state_facts.push_str(
        "}\n\n\
         fn decode_state_fact(fact: FfiStateFact) -> StateFact {\n\
         \x20   StateFact::ALL[fact as usize]\n\
         }\n",
    );
    std::fs::write(out_dir.join("ffi_state_fact_generated.rs"), ffi_state_facts)?;

    let mut cpp_mapping = String::from(
        "// Generated by Rust/build.rs from CSS/PseudoClasses.json.\n\n\
         static Optional<StyleEngineFFI::FfiStateFact> state_fact_for(PseudoClass pseudo_class)\n\
         {\n\
         \x20   switch (pseudo_class) {\n",
    );
    for name in &state_fact_names {
        writeln!(
            cpp_mapping,
            "    case PseudoClass::{name}:\n        return StyleEngineFFI::FfiStateFact::{name};"
        )?;
    }
    cpp_mapping.push_str("    default:\n        return {};\n    }\n}\n");
    std::fs::write(out_dir.join("StyleEngineStateFactsGenerated.inc"), cpp_mapping)?;
    Ok(())
}

// Generates the property metadata tables for the Rust style computation core from
// Properties.json, replicating the C++ generator's identifier assignment exactly:
// Custom is 0, then shorthands, inherited longhands and non-inherited longhands in
// JSON order, skipping legacy aliases. A C++ unit test compares the tables against
// the C++-generated equivalents so the two generators cannot drift.
fn generate_property_metadata(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let properties_path = manifest_dir.parent().unwrap().join("CSS/Properties.json");
    println!("cargo:rerun-if-changed={}", properties_path.display());

    let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&properties_path)?)?;
    let serde_json::Value::Object(properties) = value else {
        return Err("Properties.json does not contain a JSON object".into());
    };

    // Logical alias properties take their metadata from the first physical property of
    // their logical group, with local overrides, mirroring the C++ generator.
    let groups_path = manifest_dir.parent().unwrap().join("CSS/LogicalPropertyGroups.json");
    println!("cargo:rerun-if-changed={}", groups_path.display());
    let groups_value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&groups_path)?)?;
    let serde_json::Value::Object(groups) = groups_value else {
        return Err("LogicalPropertyGroups.json does not contain a JSON object".into());
    };
    let first_physical_in_group =
        |group_name: &str| -> Option<&str> { groups[group_name]["physical"].as_object()?.values().next()?.as_str() };
    let property_field = |name: &str, field: &str| -> Option<serde_json::Value> {
        let object = properties[name].as_object().unwrap();
        if let Some(value) = object.get(field) {
            return Some(value.clone());
        }
        let group = object.get("logical-alias-for")?.as_object()?.get("group")?.as_str()?;
        let physical = first_physical_in_group(group)?;
        properties[physical].as_object().unwrap().get(field).cloned()
    };

    let mut shorthands = Vec::new();
    let mut inherited_longhands = Vec::new();
    let mut noninherited_longhands = Vec::new();
    for (name, value) in &properties {
        let object = value.as_object().unwrap();
        if object.contains_key("legacy-alias-for") {
            continue;
        }
        // NB: The C++ generator populates the "all" shorthand's longhand list
        //     programmatically, so it has no explicit "longhands" key.
        if object.contains_key("longhands") || name == "all" {
            shorthands.push(name.clone());
        } else if property_field(name, "inherited").unwrap().as_bool().unwrap() {
            inherited_longhands.push(name.clone());
        } else {
            noninherited_longhands.push(name.clone());
        }
    }

    // Identifier assignment: Custom = 0, then the three runs in order.
    let mut ids = std::collections::HashMap::new();
    for (index, name) in shorthands
        .iter()
        .chain(&inherited_longhands)
        .chain(&noninherited_longhands)
        .enumerate()
    {
        ids.insert(name.clone(), (index + 1) as u16);
    }
    let first_longhand = ids[&inherited_longhands[0]];
    let last_longhand = ids[noninherited_longhands.last().unwrap()];
    let first_inherited = ids[&inherited_longhands[0]];
    let last_inherited = ids[inherited_longhands.last().unwrap()];

    let pseudo_elements_path = manifest_dir.parent().unwrap().join("CSS/PseudoElements.json");
    let property_groups_path = manifest_dir
        .parent()
        .unwrap()
        .join("CSS/PseudoElementPropertyGroups.txt");
    println!("cargo:rerun-if-changed={}", pseudo_elements_path.display());
    println!("cargo:rerun-if-changed={}", property_groups_path.display());
    let pseudo_elements_value: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&pseudo_elements_path)?)?;
    let serde_json::Value::Object(pseudo_elements) = pseudo_elements_value else {
        return Err("PseudoElements.json does not contain a JSON object".into());
    };
    let property_groups = load_property_groups(&property_groups_path)?;
    let property_id = |name: &str| -> Result<u16, Box<dyn Error>> {
        if name == "custom" {
            return Ok(0);
        }
        ids.get(name)
            .copied()
            .ok_or_else(|| format!("unknown pseudo-element property '{name}'").into())
    };
    let property_ids = |entries: &[String]| -> Result<Vec<u16>, Box<dyn Error>> {
        let mut result = std::collections::BTreeSet::new();
        for entry in entries {
            if entry.starts_with("FIXME:") {
                continue;
            }
            if let Some(properties) = property_groups.get(entry) {
                for property in properties {
                    result.insert(property_id(property)?);
                }
            } else if entry.starts_with('#') {
                return Err(format!("unknown pseudo-element property group '{entry}'").into());
            } else {
                result.insert(property_id(entry)?);
            }
        }
        Ok(result.into_iter().collect())
    };
    let always_allowed_pseudo_properties = property_ids(
        property_groups
            .get("#always-allowed-properties")
            .ok_or("missing always-allowed pseudo-element property group")?,
    )?;
    let mut pseudo_property_whitelist_rows = Vec::new();
    for name in ordered_pseudo_element_names(&pseudo_elements)? {
        let object = pseudo_elements[&name].as_object().unwrap();
        let Some(whitelist) = object.get("property-whitelist") else {
            pseudo_property_whitelist_rows.push("    None,".to_string());
            continue;
        };
        let entries = whitelist
            .as_array()
            .unwrap()
            .iter()
            .map(|entry| entry.as_str().unwrap().to_string())
            .collect::<Vec<_>>();
        let whitelist = property_ids(&entries)?;
        pseudo_property_whitelist_rows.push(format!("    Some(&{whitelist:?}),"));
    }
    // UnknownWebKit follows the known pseudo-elements and accepts all properties.
    pseudo_property_whitelist_rows.push("    None,".to_string());

    // NB: Must match manually_specified_computation_order in
    //     Meta/Generators/generate_libweb_css_property_id.py; the parity test enforces it.
    let manual_order = [
        "math-depth",
        "font-family",
        "font-feature-settings",
        "font-kerning",
        "font-optical-sizing",
        "font-size",
        "font-style",
        "font-variant-alternates",
        "font-variant-caps",
        "font-variant-east-asian",
        "font-variant-emoji",
        "font-variant-ligatures",
        "font-variant-numeric",
        "font-variant-position",
        "font-variation-settings",
        "font-weight",
        "font-width",
        "text-rendering",
        "line-height",
        "color-scheme",
        "background-image",
        "direction",
        "writing-mode",
    ];
    let mut order = Vec::new();
    for name in manual_order {
        order.push(ids[name]);
    }
    // NB: The remainder follows Properties.json iteration order across all longhands,
    //     matching the C++ generator, not grouped by inheritance.
    for (name, value) in &properties {
        let object = value.as_object().unwrap();
        if object.contains_key("legacy-alias-for") || object.contains_key("longhands") || name == "all" {
            continue;
        }
        if !manual_order.contains(&name.as_str()) {
            order.push(ids[name]);
        }
    }

    let mut levels = vec![0u8; (last_longhand - first_longhand + 1) as usize];
    let mut animation_types = vec![0u8; levels.len()];
    let mut numeric_range_rows = vec![String::new(); levels.len()];
    let value_types = [
        "anchor",
        "anchor-size",
        "angle",
        "angle-percentage",
        "background-position",
        "basic-shape",
        "color",
        "corner-shape",
        "counter",
        "counter-style",
        "custom-ident",
        "dashed-ident",
        "easing-function",
        "filter-value-list",
        "fit-content",
        "flex",
        "font-style",
        "font-variant-alternates",
        "font-variant-east-asian",
        "font-variant-ligatures",
        "font-variant-numeric",
        "frequency",
        "frequency-percentage",
        "image",
        "integer",
        "length",
        "length-percentage",
        "number",
        "opacity-value",
        "opentype-tag",
        "paint",
        "percentage",
        "position",
        "ratio",
        "rect",
        "resolution",
        "scroll-function",
        "string",
        "time",
        "time-percentage",
        "transform-function",
        "transform-list",
        "url",
        "view-function",
        "view-timeline-inset",
    ];
    for name in inherited_longhands.iter().chain(&noninherited_longhands) {
        let index = (ids[name] - first_longhand) as usize;
        let requires_computation = property_field(name, "requires-computation").unwrap();
        let level = match requires_computation.as_str().unwrap() {
            "never" => 0u8,
            "cascaded-value" => 1,
            "non-inherited-value" => 2,
            "always" => 3,
            other => return Err(format!("unknown requires-computation '{other}' for {name}").into()),
        };
        levels[index] = level;

        animation_types[index] = match property_field(name, "animation-type").unwrap().as_str().unwrap() {
            "discrete" => 0,
            "by-computed-value" => 1,
            "repeatable-list" => 2,
            "custom" => 3,
            "none" => 4,
            other => return Err(format!("unknown animation-type '{other}' for {name}").into()),
        };

        let mut ranges = Vec::new();
        if let Some(valid_types) = property_field(name, "valid-types").and_then(|value| value.as_array().cloned()) {
            for valid_type in valid_types {
                let valid_type = valid_type.as_str().unwrap();
                let Some((type_name, range)) = valid_type.split_once(' ') else {
                    continue;
                };
                if !range.starts_with('[') || !range.ends_with(']') || !range.contains(',') {
                    continue;
                }
                if type_name == "custom-ident" {
                    continue;
                }
                let value_type = value_types
                    .iter()
                    .position(|candidate| *candidate == type_name)
                    .ok_or_else(|| format!("unknown ranged value type '{type_name}' for {name}"))?;
                let (min, max) = range[1..range.len() - 1]
                    .split_once(',')
                    .ok_or_else(|| format!("bad numeric range '{range}' for {name}"))?;
                let format_bound = |bound: &str| match (type_name, bound) {
                    ("integer", "-∞") => "i32::MIN as f64".to_string(),
                    ("integer", "∞") => "i32::MAX as f64".to_string(),
                    (_, "-∞") => "f32::MIN as f64".to_string(),
                    (_, "∞") => "f32::MAX as f64".to_string(),
                    _ if bound.contains('.') => bound.to_string(),
                    _ => format!("{bound}.0"),
                };
                ranges.push(format!(
                    "FfiPropertyNumericRange {{ value_type: {value_type}, min: {}, max: {} }}",
                    format_bound(min),
                    format_bound(max)
                ));
            }
        }
        numeric_range_rows[index] = ranges.join(", ");
    }

    let mut output = String::new();
    output.push_str("// Generated by build.rs from CSS metadata. Do not edit.\n\n");
    // Shorthand expansion tables for the cascade. The "all" shorthand expands to every
    // longhand except direction and unicode-bidi, mirroring the C++ generator.
    let mut shorthand_rows = Vec::new();
    for name in &shorthands {
        let longhand_names: Vec<String> = if name == "all" {
            properties
                .iter()
                .filter(|(name, value)| {
                    let object = value.as_object().unwrap();
                    !object.contains_key("longhands")
                        && !object.contains_key("legacy-alias-for")
                        && name.as_str() != "all"
                        && name.as_str() != "direction"
                        && name.as_str() != "unicode-bidi"
                })
                .map(|(name, _)| name.clone())
                .collect()
        } else {
            properties[name]["longhands"]
                .as_array()
                .unwrap()
                .iter()
                .map(|longhand| longhand.as_str().unwrap().to_string())
                .collect()
        };
        let ids_row: Vec<u16> = longhand_names.iter().map(|longhand| ids[longhand]).collect();
        shorthand_rows.push(format!("    &{ids_row:?},"));
    }
    output.push_str(&format!(
        "pub(crate) static SHORTHAND_EXPANSIONS: [&[u16]; {}] = [\n{}\n];\n\n",
        shorthand_rows.len(),
        shorthand_rows.join("\n")
    ));
    let property_names: Vec<&str> = shorthands
        .iter()
        .chain(&inherited_longhands)
        .chain(&noninherited_longhands)
        .map(String::as_str)
        .collect();
    fn expanded_longhands(
        name: &str,
        properties: &serde_json::Map<String, serde_json::Value>,
        all_longhands: &[String],
        result: &mut Vec<String>,
    ) {
        if name == "all" {
            result.extend_from_slice(all_longhands);
            return;
        }
        let Some(longhands) = properties[name].get("longhands").and_then(|value| value.as_array()) else {
            result.push(name.to_string());
            return;
        };
        for longhand in longhands {
            expanded_longhands(longhand.as_str().unwrap(), properties, all_longhands, result);
        }
    }
    let all_longhands: Vec<String> = inherited_longhands
        .iter()
        .chain(&noninherited_longhands)
        .filter(|name| name.as_str() != "direction" && name.as_str() != "unicode-bidi")
        .cloned()
        .collect();
    let expanded_shorthand_longhands: Vec<Vec<String>> = shorthands
        .iter()
        .map(|name| {
            let mut result = Vec::new();
            expanded_longhands(name, &properties, &all_longhands, &mut result);
            result
        })
        .collect();
    let camel_case_property_name = |name: &str| {
        let mut parts = name.split('-').filter(|part| !part.is_empty());
        let mut result = parts.next().unwrap_or_default().to_string();
        for part in parts {
            let mut characters = part.chars();
            if let Some(first) = characters.next() {
                result.extend(first.to_uppercase());
                result.extend(characters);
            }
        }
        result
    };
    let idl_names: Vec<String> = property_names
        .iter()
        .map(|name| camel_case_property_name(name))
        .collect();
    let logical_aliases: Vec<bool> = property_names
        .iter()
        .enumerate()
        .map(|(index, name)| {
            let name: &str = if index < shorthands.len() {
                expanded_shorthand_longhands[index][0].as_str()
            } else {
                name
            };
            properties[name].as_object().unwrap().contains_key("logical-alias-for")
        })
        .collect();
    let expanded_longhand_counts: Vec<usize> = expanded_shorthand_longhands.iter().map(Vec::len).collect();
    output.push_str(&format!(
        "pub(crate) static PROPERTY_IDL_NAMES: [&str; {}] = {:?};\n",
        idl_names.len(),
        idl_names
    ));
    output.push_str(&format!(
        "pub(crate) static PROPERTY_IS_LOGICAL_ALIAS: [bool; {}] = {:?};\n\n",
        logical_aliases.len(),
        logical_aliases
    ));
    output.push_str(&format!(
        "pub(crate) static SHORTHAND_EXPANDED_LONGHAND_COUNTS: [usize; {}] = {:?};\n\n",
        expanded_longhand_counts.len(),
        expanded_longhand_counts
    ));
    output.push_str(&format!(
        "pub const FIRST_SHORTHAND_PROPERTY_ID: u16 = {};\n",
        ids[&shorthands[0]]
    ));
    output.push_str(&format!(
        "pub const LAST_SHORTHAND_PROPERTY_ID: u16 = {};\n\n",
        ids[shorthands.last().unwrap()]
    ));
    output.push_str("#[allow(dead_code)]\npub mod property_id {\n");
    output.push_str("    pub const CUSTOM: u16 = 0;\n");
    for name in shorthands
        .iter()
        .chain(&inherited_longhands)
        .chain(&noninherited_longhands)
    {
        let constant = name.replace('-', "_").to_uppercase();
        output.push_str(&format!("    pub const {constant}: u16 = {};\n", ids[name]));
    }
    output.push_str("}\n\n");
    output.push_str(&format!(
        "pub const FIRST_LONGHAND_PROPERTY_ID: u16 = {first_longhand};\n"
    ));
    output.push_str(&format!(
        "pub const LAST_LONGHAND_PROPERTY_ID: u16 = {last_longhand};\n"
    ));
    output.push_str(&format!(
        "pub const FIRST_INHERITED_PROPERTY_ID: u16 = {first_inherited};\n"
    ));
    output.push_str(&format!(
        "pub const LAST_INHERITED_PROPERTY_ID: u16 = {last_inherited};\n\n"
    ));
    output.push_str(&format!(
        "pub(crate) static PROPERTY_COMPUTATION_ORDER: [u16; {}] = {:?};\n\n",
        order.len(),
        order
    ));
    output.push_str(&format!(
        "pub(crate) static REQUIRES_COMPUTATION_LEVELS: [u8; {}] = {:?};\n",
        levels.len(),
        levels
    ));
    output.push_str(&format!(
        "pub(crate) static PROPERTY_ANIMATION_TYPES: [u8; {}] = {:?};\n",
        animation_types.len(),
        animation_types
    ));
    output.push_str(&format!(
        "pub(crate) static PROPERTY_NUMERIC_RANGES: [&[FfiPropertyNumericRange]; {}] = [\n{}\n];\n",
        numeric_range_rows.len(),
        numeric_range_rows
            .iter()
            .map(|ranges| format!("    &[{ranges}],"))
            .collect::<Vec<_>>()
            .join("\n")
    ));
    output.push_str(&format!(
        "\npub(crate) static PSEUDO_ELEMENT_ALWAYS_ALLOWED_PROPERTIES: &[u16] = &{always_allowed_pseudo_properties:?};\n"
    ));
    let positional_shorthands: Vec<u16> = properties
        .iter()
        .filter(|(_, value)| {
            value.as_object().is_some_and(|object| {
                object
                    .get("positional-value-list-shorthand")
                    .and_then(|flag| flag.as_bool())
                    == Some(true)
            })
        })
        .map(|(name, _)| ids[name])
        .collect();
    output.push_str(&format!(
        "\npub(crate) static POSITIONAL_VALUE_LIST_SHORTHANDS: &[u16] = &{positional_shorthands:?};\n"
    ));
    output.push_str(&format!(
        "pub(crate) static PSEUDO_ELEMENT_PROPERTY_WHITELISTS: [Option<&[u16]>; {}] = [\n{}\n];\n",
        pseudo_property_whitelist_rows.len(),
        pseudo_property_whitelist_rows.join("\n")
    ));
    std::fs::write(out_dir.join("property_metadata_generated.rs"), output)?;
    Ok(())
}

// Generates the length unit table for the Rust style computation core from Units.json.
// Unit codes are the alphabetical index within the "length" object, matching the C++
// LengthUnit enum; absolute units carry their canonical px ratio.
fn generate_length_units(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let units_path = manifest_dir.parent().unwrap().join("CSS/Units.json");
    println!("cargo:rerun-if-changed={}", units_path.display());
    let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&units_path)?)?;
    let lengths = value["length"].as_object().ok_or("Units.json has no length object")?;

    let mut names = Vec::new();
    let mut ratios = Vec::new();
    for (name, unit) in lengths {
        names.push(name.clone());
        let object = unit.as_object().unwrap();
        if object
            .get("is-canonical-unit")
            .is_some_and(|canonical| canonical.as_bool() == Some(true))
        {
            ratios.push("1.0".to_string());
        } else if let Some(ratio) = object.get("number-of-canonical-unit") {
            ratios.push(format!("{:?}", ratio.as_f64().unwrap()));
        } else {
            ratios.push("f64::NAN".to_string());
        }
    }

    let mut output = String::new();
    output.push_str("// Generated by build.rs from Units.json. Do not edit.\n\n");
    output.push_str(&format!(
        "pub(crate) static LENGTH_UNIT_NAMES: [&str; {}] = {:?};\n\n",
        names.len(),
        names
    ));
    output.push_str(&format!(
        "pub(crate) static LENGTH_UNIT_CANONICAL_PX_RATIOS: [f64; {}] = [{}];\n",
        ratios.len(),
        ratios.join(", ")
    ));
    std::fs::write(out_dir.join("length_units_generated.rs"), output)?;

    // Canonical-unit ratios for the other dimensions, indexed by unit code in
    // JSON order like the C++ unit enums. Relative units (none exist outside
    // lengths) would be NaN.
    let mut output = String::from("// Generated by build.rs from Units.json. Do not edit.\n");
    for dimension in ["angle", "flex", "frequency", "resolution", "time"] {
        let units = value[dimension]
            .as_object()
            .ok_or_else(|| format!("Units.json has no {dimension} object"))?;
        let mut ratios = Vec::new();
        for (_, unit) in units {
            let object = unit.as_object().unwrap();
            if object
                .get("is-canonical-unit")
                .is_some_and(|canonical| canonical.as_bool() == Some(true))
            {
                ratios.push("1.0".to_string());
            } else if let Some(ratio) = object.get("number-of-canonical-unit") {
                ratios.push(format!("{:?}", ratio.as_f64().unwrap()));
            } else {
                ratios.push("f64::NAN".to_string());
            }
        }
        output.push_str(&format!(
            "\npub(crate) static {}_UNIT_CANONICAL_RATIOS: [f64; {}] = [{}];\n",
            dimension.to_uppercase(),
            ratios.len(),
            ratios.join(", ")
        ));
        let names: Vec<&str> = units.keys().map(String::as_str).collect();
        output.push_str(&format!(
            "\n#[allow(dead_code)]\npub(crate) static {}_UNIT_NAMES: [&str; {}] = {:?};\n",
            dimension.to_uppercase(),
            names.len(),
            names
        ));
    }
    std::fs::write(out_dir.join("dimension_units_generated.rs"), output)?;
    Ok(())
}

// Generates transform function names for the Rust serializer from TransformFunctions.json,
// following the C++ generator's enum member order (the file's key order).
fn generate_transform_functions(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let path = manifest_dir.parent().unwrap().join("CSS/TransformFunctions.json");
    println!("cargo:rerun-if-changed={}", path.display());
    let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&path)?)?;
    let functions = value.as_object().ok_or("TransformFunctions.json is not an object")?;

    let mut output = String::new();
    output.push_str("// Generated by build.rs from TransformFunctions.json. Do not edit.\n\n");
    output.push_str(&format!(
        "#[allow(dead_code)]\npub(crate) static TRANSFORM_FUNCTION_NAMES: [&str; {}] = [\n",
        functions.len()
    ));
    for name in functions.keys() {
        output.push_str(&format!("    \"{name}\",\n"));
    }
    output.push_str("];\n\n");

    // Function index constants mirroring the C++ TransformFunction enum, which
    // the generator emits in the JSON object's order.
    output.push_str("#[allow(dead_code)]\npub(crate) mod transform_function {\n");
    for (index, name) in functions.keys().enumerate() {
        let mut constant = String::new();
        for character in name.chars() {
            if character.is_ascii_uppercase() {
                constant.push('_');
            }
            constant.push(character.to_ascii_uppercase());
        }
        output.push_str(&format!("    pub const {constant}: u8 = {index};\n"));
    }
    output.push_str("}\n\n");

    // Parameter types per function, mirroring the C++
    // TransformFunctionParameterType codes: angle 0, length 1, length-none 2,
    // length-percentage 3, number 4, number-percentage 5.
    let parameter_type_code = |name: &str| -> Result<u8, Box<dyn Error>> {
        Ok(match name {
            "angle" => 0,
            "length" => 1,
            "length-none" => 2,
            "length-percentage" => 3,
            "number" => 4,
            "number-percentage" => 5,
            _ => return Err(format!("unknown transform function parameter type {name}").into()),
        })
    };
    output.push_str(&format!(
        "#[allow(dead_code)]\npub(crate) static TRANSFORM_FUNCTION_PARAMETER_TYPES: [&[u8]; {}] = [\n",
        functions.len()
    ));
    for (name, function) in functions {
        let parameters = function
            .get("parameters")
            .and_then(serde_json::Value::as_array)
            .ok_or_else(|| format!("transform function {name} has no parameters array"))?;
        let mut codes = Vec::new();
        for parameter in parameters {
            let parameter_type = parameter
                .get("type")
                .and_then(serde_json::Value::as_str)
                .ok_or_else(|| format!("transform function {name} parameter has no type"))?;
            codes.push(parameter_type_code(parameter_type.trim_matches(['<', '>']))?.to_string());
        }
        output.push_str(&format!("    &[{}],\n", codes.join(", ")));
    }
    output.push_str("];\n");
    std::fs::write(out_dir.join("transform_functions_generated.rs"), output)?;
    Ok(())
}

// Generates keyword codes for the Rust style computation core from Keywords.json.
// Invalid is 0 and the codes follow the array order, matching the C++ Keyword enum.
fn generate_keywords(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let keywords_path = manifest_dir.parent().unwrap().join("CSS/Keywords.json");
    println!("cargo:rerun-if-changed={}", keywords_path.display());
    let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&keywords_path)?)?;
    let keywords = value.as_array().ok_or("Keywords.json is not an array")?;

    let mut output = String::new();
    output.push_str("// Generated by build.rs from Keywords.json. Do not edit.\n\n");
    output.push_str("#[allow(dead_code)]\npub mod keyword {\n");
    output.push_str("    pub const INVALID: u16 = 0;\n");
    for (index, keyword) in keywords.iter().enumerate() {
        let name = keyword.as_str().unwrap();
        let constant = name.replace('-', "_").to_uppercase();
        output.push_str(&format!("    pub const {constant}: u16 = {};\n", index + 1));
    }
    // Keyword names indexed by code, for serialization; index 0 is the invalid keyword.
    output.push_str("    pub static NAMES: [&str; ");
    output.push_str(&format!("{}] = [\n        \"\",\n", keywords.len() + 1));
    for keyword in keywords {
        let name = keyword.as_str().unwrap();
        output.push_str(&format!("        \"{name}\",\n"));
    }
    output.push_str("    ];\n");
    output.push_str("}\n");
    std::fs::write(out_dir.join("keywords_generated.rs"), output)?;
    Ok(())
}

// Generates enum value codes for the Rust style computation core from Enums.json.
// Values follow the array order skipping aliases, matching the C++ enum generator.
fn generate_css_enums(manifest_dir: &Path, out_dir: &Path) -> Result<(), Box<dyn Error>> {
    let enums_path = manifest_dir.parent().unwrap().join("CSS/Enums.json");
    println!("cargo:rerun-if-changed={}", enums_path.display());
    let value: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&enums_path)?)?;
    let enums = value.as_object().ok_or("Enums.json is not an object")?;

    let mut output = String::new();
    output.push_str("// Generated by build.rs from Enums.json. Do not edit.\n\n");
    for (name, values) in enums {
        let values = values.as_array().ok_or("enum values are not an array")?;
        let module = name.replace('-', "_");
        output.push_str(&format!("#[allow(dead_code)]\npub mod {module} {{\n"));
        let mut code: u8 = 0;
        for value in values {
            let value = value.as_str().ok_or("enum value is not a string")?;
            // Aliases are not included in the enum.
            if value.contains('=') {
                continue;
            }
            let constant = value.replace('-', "_").to_uppercase();
            output.push_str(&format!("    pub const {constant}: u8 = {code};\n"));
            code = code.checked_add(1).ok_or("enum has too many values for u8")?;
        }
        // Member names indexed by value code, for serialization; mirrors the C++
        // string_from_<enum> generator (aliases are not members and have no name slot).
        output.push_str(&format!("    pub static NAMES: [&str; {code}] = [\n"));
        for value in values {
            let value = value.as_str().ok_or("enum value is not a string")?;
            if value.contains('=') {
                continue;
            }
            output.push_str(&format!("        \"{value}\",\n"));
        }
        output.push_str("    ];\n");
        output.push_str("}\n\n");

        // The keyword-to-enum-value mapping, mirroring the C++ keyword_to_<enum> generator,
        // including its alias handling ("keyword=member" maps the keyword to member's value).
        let mut member_codes = std::collections::HashMap::new();
        let mut member_code: u8 = 0;
        for value in values {
            let value = value.as_str().ok_or("enum value is not a string")?;
            if value.contains('=') {
                continue;
            }
            member_codes.insert(value.to_string(), member_code);
            member_code = member_code.checked_add(1).ok_or("enum has too many values for u8")?;
        }
        output.push_str(&format!(
            "#[allow(dead_code)]\npub fn keyword_to_{module}(keyword: u16) -> Option<u8> {{\n    match keyword {{\n"
        ));
        for value in values {
            let value = value.as_str().ok_or("enum value is not a string")?;
            let (keyword_name, member_name) = match value.split_once('=') {
                Some((keyword, member)) => (keyword, member),
                None => (value, value),
            };
            let keyword_constant = keyword_name.replace('-', "_").to_uppercase();
            let code = member_codes
                .get(member_name)
                .ok_or("enum alias targets an unknown member")?;
            output.push_str(&format!("        keyword::{keyword_constant} => Some({code}),\n"));
        }
        output.push_str("        _ => None,\n    }\n}\n\n");
    }
    std::fs::write(out_dir.join("css_enums_generated.rs"), output)?;
    Ok(())
}

fn generate_ffi_header(config: cbindgen::Config, sources: &[PathBuf], out_dir: &Path, header: &Path) {
    let builder = sources
        .iter()
        .fold(cbindgen::Builder::new().with_config(config), |builder, source| {
            builder.with_src(source)
        });
    builder.generate().map_or_else(
        |error| match error {
            cbindgen::Error::ParseSyntaxError { .. } => {
                // Do nothing, the build will fail later with a nicer error message when compiling with rustc
            }
            other => panic!("{other:?}"),
        },
        |bindings| {
            let output_header = out_dir.join(header);
            std::fs::create_dir_all(output_header.parent().unwrap()).unwrap();
            bindings.write_to_file(output_header);
        },
    );
}

// CssPixels is a single i32 fixed-point value shared with the CSS module; C++
// already has the matching CSSPixels class, so expose its raw representation in
// the generated ABI rather than generating a second C++ pixel type in the
// RustFFI namespace.
fn expose_css_pixels_as_raw_i32(config: &mut cbindgen::Config) {
    config.export.exclude.push("CssPixels".to_string());
    config
        .export
        .rename
        .insert("CssPixels".to_string(), "int32_t".to_string());
}

fn public_type_names(path: &Path) -> Result<Vec<String>, Box<dyn Error>> {
    println!("cargo:rerun-if-changed={}", path.display());
    let mut names = Vec::new();
    for line in std::fs::read_to_string(path)?.lines() {
        for prefix in ["pub struct ", "pub enum "] {
            if let Some(rest) = line.strip_prefix(prefix) {
                let name: String = rest.chars().take_while(|c| c.is_alphanumeric() || *c == '_').collect();
                if !name.is_empty() {
                    names.push(name);
                }
            }
        }
    }
    Ok(names)
}

struct DisplayListCommandImplFacts {
    name: String,
    has_bounding_rect: bool,
    has_is_clip: bool,
}

fn display_list_command_impl_facts(path: &Path) -> Result<Vec<DisplayListCommandImplFacts>, Box<dyn Error>> {
    let source = std::fs::read_to_string(path)?;
    let mut facts = Vec::new();
    let mut lines = source.lines();
    while let Some(line) = lines.next() {
        let Some(rest) = line.strip_prefix("impl DisplayListCommand for ") else {
            continue;
        };
        let name: String = rest.chars().take_while(|c| c.is_alphanumeric() || *c == '_').collect();
        if name.is_empty() {
            return Err(format!("unparsable DisplayListCommand impl header: {line}").into());
        }
        let mut has_bounding_rect = false;
        let mut has_is_clip = false;
        let mut closed = false;
        for body_line in lines.by_ref() {
            if body_line == "}" {
                closed = true;
                break;
            }
            let body_line = body_line.trim_start();
            has_bounding_rect |= body_line.starts_with("fn bounding_rect");
            has_is_clip |= body_line.starts_with("fn is_clip");
        }
        if !closed {
            return Err(format!("unterminated DisplayListCommand impl for {name}").into());
        }
        facts.push(DisplayListCommandImplFacts {
            name,
            has_bounding_rect,
            has_is_clip,
        });
    }
    if facts.is_empty() {
        return Err("no DisplayListCommand impls found".into());
    }
    Ok(facts)
}

fn generate_ffi_header_strict(config: cbindgen::Config, sources: &[PathBuf], out_dir: &Path, header: &Path) {
    let builder = sources
        .iter()
        .fold(cbindgen::Builder::new().with_config(config), |builder, source| {
            builder.with_src(source)
        });
    builder.generate().map_or_else(
        |error| panic!("{error}"),
        |bindings| {
            let output_header = out_dir.join(header);
            std::fs::create_dir_all(output_header.parent().unwrap()).unwrap();
            bindings.write_to_file(output_header);
        },
    );
}

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");
    println!("cargo:rerun-if-changed=src");

    generate_selector_pseudo_types(&manifest_dir, &out_dir)?;
    generate_property_metadata(&manifest_dir, &out_dir)?;
    generate_length_units(&manifest_dir, &out_dir)?;
    generate_keywords(&manifest_dir, &out_dir)?;
    generate_css_enums(&manifest_dir, &out_dir)?;
    generate_transform_functions(&manifest_dir, &out_dir)?;
    generate_style_engine_event_kinds(&manifest_dir, &out_dir)?;
    generate_style_engine_boundary(&manifest_dir, &out_dir)?;

    let base_config = cbindgen::Config::from_file(manifest_dir.join("cbindgen.toml"))?;

    // CSS tokenizer header — namespace Web::CSS::Parser::FFI, CSS types only.
    let mut css_config = base_config.clone();
    css_config.namespaces = Some(vec![
        "Web".to_string(),
        "CSS".to_string(),
        "Parser".to_string(),
        "FFI".to_string(),
    ]);
    css_config.export.include = vec![
        "CssHashType".to_string(),
        "CssNumberType".to_string(),
        "CssToken".to_string(),
        "CssTokenType".to_string(),
    ];

    generate_ffi_header(
        css_config,
        &[manifest_dir.join("src/css/css_tokenizer.rs")],
        &out_dir,
        Path::new("RustFFI.h"),
    );

    // Selector matching header - namespace Web::CSS::SelectorFFI. Generate both sides of this
    // ABI from the Rust declarations so changes to layouts or signatures cannot drift silently.
    let mut selector_config = base_config.clone();
    selector_config.namespaces = Some(vec!["Web".to_string(), "CSS".to_string(), "SelectorFFI".to_string()]);
    for (rust_name, cxx_name) in [
        ("FfiSimpleSelectorType", "SimpleSelectorType"),
        ("FfiDirection", "Direction"),
        ("FfiPseudoElementValueType", "PseudoElementValueType"),
        ("FfiStringView", "StringView"),
        ("FfiSimpleSelector", "SimpleSelector"),
        ("FfiCompoundSelector", "CompoundSelector"),
        ("FfiSelector", "Selector"),
        ("FfiElement", "Element"),
        ("FfiElementQualifiedName", "ElementQualifiedName"),
        ("FfiInternedStringList", "InternedStringList"),
        ("FfiDomStringView", "DomStringView"),
        ("FfiDomAttribute", "DomAttribute"),
        ("FfiResolvedNamespaceType", "ResolvedNamespaceType"),
        ("FfiResolvedNamespace", "ResolvedNamespace"),
        ("FfiElementAndShadowHost", "ElementAndShadowHost"),
    ] {
        selector_config
            .export
            .rename
            .insert(rust_name.to_string(), cxx_name.to_string());
    }

    generate_ffi_header(
        selector_config,
        &[
            manifest_dir.join("src/css/selector.rs"),
            manifest_dir.join("src/css/ffi_support.rs"),
        ],
        &out_dir,
        Path::new("SelectorRustFFI.h"),
    );

    // Style value header - namespace Web::CSS::StyleValueFFI. The StyleValueData layout is
    // exposed so converted C++ StyleValue subclasses can read variant payloads inline without
    // an FFI call.
    let mut style_value_config = base_config.clone();
    style_value_config.namespaces = Some(vec!["Web".to_string(), "CSS".to_string(), "StyleValueFFI".to_string()]);
    style_value_config.export.include = vec!["StyleValueData".to_string()];

    generate_ffi_header(
        style_value_config,
        &[
            manifest_dir.join("src/css/style_value.rs"),
            manifest_dir.join("src/css/retained_fly_string.rs"),
            manifest_dir.join("src/css/color_interpolation.rs"),
            manifest_dir.join("src/css/animation.rs"),
            manifest_dir.join("src/css/transition.rs"),
            manifest_dir.join("src/css/calc.rs"),
            manifest_dir.join("src/css/serialize.rs"),
            manifest_dir.join("src/css/color_resolution.rs"),
            manifest_dir.join("src/css/absolutize.rs"),
            manifest_dir.join("src/css/ffi_stats.rs"),
        ],
        &out_dir,
        Path::new("StyleValueRustFFI.h"),
    );

    // StyleEngine header - namespace Web::CSS::StyleEngineFFI. The flat input transaction and the
    // engine lifecycle entry points; no string or owning pointer appears in this ABI.
    let mut style_engine_config = base_config.clone();
    style_engine_config.namespaces = Some(vec!["Web".to_string(), "CSS".to_string(), "StyleEngineFFI".to_string()]);

    generate_ffi_header(
        style_engine_config,
        &[
            manifest_dir.join("src/css/style/bridge.rs"),
            out_dir.join("ffi_state_fact_generated.rs"),
            out_dir.join("style_engine_boundary_generated.rs"),
        ],
        &out_dir,
        Path::new("StyleEngineRustFFI.h"),
    );

    // Computed values header - namespace Web::CSS::ComputedValuesFFI. Exposes the style group
    // vtable and lifecycle functions; the reference count header layout is documented in
    // computed_values.rs and mirrored by StyleStructRef.
    let mut computed_values_config = base_config.clone();
    computed_values_config.namespaces = Some(vec![
        "Web".to_string(),
        "CSS".to_string(),
        "ComputedValuesFFI".to_string(),
    ]);
    computed_values_config.export.include = vec![
        "StyleGroupVTable".to_string(),
        "STYLE_GROUP_STATIC_REFCOUNT".to_string(),
        "GRID_NO_INDEX".to_string(),
        "ComputedGridTrackEntryKind".to_string(),
        "ComputedGridPlacementKind".to_string(),
        "CascadeOrigin".to_string(),
        "TransformValues".to_string(),
        "EffectsValues".to_string(),
        "ComputedColorOrAuto".to_string(),
        "ComputedCursor".to_string(),
        "RetainedComputedCursorList".to_string(),
        "ComputedScrollbarColor".to_string(),
        "InheritedUIValues".to_string(),
        "ComputedSvgPaint".to_string(),
        "ComputedSvgDash".to_string(),
        "RetainedComputedSvgDashList".to_string(),
        "InheritedSVGValues".to_string(),
        "ComputedTextIndent".to_string(),
        "ComputedTextUnderlinePosition".to_string(),
        "ComputedTextUnderlineOffset".to_string(),
        "InheritedTextValues".to_string(),
        "AnimationValues".to_string(),
        "MaskValues".to_string(),
        "BackgroundValues".to_string(),
        "BorderValues".to_string(),
        "InheritedListValues".to_string(),
        "ContentValues".to_string(),
        "ComputedOverflowClipMarginSide".to_string(),
        "ComputedOverflowClipMargin".to_string(),
        "MiscResetValues".to_string(),
        "FontValues".to_string(),
        "FfiFontGroupBuildInputs".to_string(),
        "TextResetValues".to_string(),
        "AnchorValues".to_string(),
        "FfiTableInheritanceDependentValue".to_string(),
        "FfiEffectiveLonghandValue".to_string(),
        "EFFECTIVE_LONGHAND_SOURCE_TABLE".to_string(),
        "EFFECTIVE_LONGHAND_SOURCE_OVERLAY".to_string(),
        "EFFECTIVE_LONGHAND_SOURCE_SPECIFIED".to_string(),
    ];

    generate_ffi_header(
        computed_values_config,
        &[
            manifest_dir.join("src/css/computed_values.rs"),
            manifest_dir.join("src/css/property_metadata.rs"),
            manifest_dir.join("src/css/style_compute.rs"),
            manifest_dir.join("src/css/display.rs"),
            manifest_dir.join("src/css/computed_value_types.rs"),
            manifest_dir.join("src/css/retained_fly_string.rs"),
            manifest_dir.join("src/css/css_pixels.rs"),
            manifest_dir.join("src/css/animated_overlay.rs"),
            manifest_dir.join("src/css/cascaded_properties.rs"),
            manifest_dir.join("src/css/computed_longhand_table.rs"),
            manifest_dir.join("src/css/custom_properties.rs"),
            manifest_dir.join("src/css/table_group_builder.rs"),
        ],
        &out_dir,
        Path::new("ComputedValuesRustFFI.h"),
    );

    // Encoding-detection header - namespace Web::HTML::Parser, rust_detect_encoding only.
    let mut html_config = base_config.clone();
    html_config.namespaces = Some(vec!["Web".to_string(), "HTML".to_string(), "Parser".to_string()]);
    html_config.export.include = vec!["rust_detect_encoding".to_string()];

    generate_ffi_header(
        html_config,
        &[manifest_dir.join("src/encoding_detection.rs")],
        &out_dir,
        Path::new("HTML/Parser/RustFFI.h"),
    );

    // Layout tree-builder header - namespace Web::Layout::RustFFI. The node arena and its
    // node records are read directly by the C++ layout tree wrappers.
    let mut tree_builder_config = base_config.clone();
    tree_builder_config.namespaces = Some(vec!["Web".to_string(), "Layout".to_string(), "RustFFI".to_string()]);
    tree_builder_config.export.include = vec![
        "FfiNodeKindFacts".to_string(),
        "FfiReplacedContentFacts".to_string(),
        "FfiStylePayloads".to_string(),
        "NodeAllocation".to_string(),
        "NodeData".to_string(),
        "NodeFlag".to_string(),
        "NodeKind".to_string(),
        "NodeSlotId".to_string(),
    ];
    tree_builder_config.export.exclude = vec![
        "rust_calc_node_create_numeric_dimension".to_string(),
        "rust_calc_resolve".to_string(),
    ];
    expose_css_pixels_as_raw_i32(&mut tree_builder_config);
    generate_ffi_header(
        tree_builder_config,
        &[
            manifest_dir.join("src/layout/layout_node_arena.rs"),
            manifest_dir.join("src/layout/node_data.rs"),
            manifest_dir.join("src/layout/tree_builder.rs"),
            manifest_dir.join("../../RustAllocator.rs"),
        ],
        &out_dir,
        Path::new("Layout/TreeBuilderRustFFI.h"),
    );

    // Layout engine header - namespace Web::Layout::RustFFI, layered on the tree-builder
    // header.
    let mut layout_config = base_config.clone();
    layout_config.namespaces = Some(vec!["Web".to_string(), "Layout".to_string(), "RustFFI".to_string()]);
    layout_config.export.exclude = vec![
        "rust_calc_node_create_numeric_dimension".to_string(),
        "rust_calc_resolve".to_string(),
        "rust_calc_root_from_calculated".to_string(),
        "rust_calc_external_resolutions".to_string(),
        "rust_calc_external_resolutions_release".to_string(),
    ];
    expose_css_pixels_as_raw_i32(&mut layout_config);
    layout_config
        .includes
        .push("LibWeb/Layout/TreeBuilderRustFFI.h".to_string());
    layout_config.export.include = vec![
        "FfiGridTrackType".to_string(),
        "FfiGridTrackState".to_string(),
        "FfiFormattingContextType".to_string(),
        "FfiFlexLayoutClampState".to_string(),
        "FfiFlexLayoutGrowthState".to_string(),
        "PaintableFlag".to_string(),
    ];
    generate_ffi_header(
        layout_config,
        &[
            manifest_dir.join("src/layout/used_values.rs"),
            manifest_dir.join("src/layout/commit.rs"),
            manifest_dir.join("src/layout/geometry.rs"),
            manifest_dir.join("src/layout/style_values.rs"),
            manifest_dir.join("src/layout/node_facts.rs"),
            manifest_dir.join("src/css/computed_value_types.rs"),
            manifest_dir.join("src/css/display.rs"),
            manifest_dir.join("src/layout/formatting_context.rs"),
            manifest_dir.join("src/layout/flex_formatting_context.rs"),
            manifest_dir.join("src/layout/grid_formatting_context.rs"),
            manifest_dir.join("src/layout/svg_formatting_context.rs"),
            manifest_dir.join("src/layout/table_formatting_context.rs"),
            manifest_dir.join("src/layout/inline_formatting_context.rs"),
            manifest_dir.join("src/layout/inline_level_iterator.rs"),
            manifest_dir.join("src/layout/line_builder.rs"),
            manifest_dir.join("src/layout/line_box.rs"),
            manifest_dir.join("src/layout/line_box_fragment.rs"),
            manifest_dir.join("src/painting/paintable_data.rs"),
            manifest_dir.join("src/painting/paintable_build.rs"),
            manifest_dir.join("src/painting/host/mod.rs"),
            manifest_dir.join("src/painting/host/visual_context.rs"),
            manifest_dir.join("src/painting/host/hit_test.rs"),
            manifest_dir.join("src/painting/host/paint.rs"),
            manifest_dir.join("src/painting/ffi.rs"),
        ],
        &out_dir,
        Path::new("Layout/LayoutRustFFI.h"),
    );

    let mut painting_config = base_config.clone();
    painting_config.namespaces = Some(vec!["Web".to_string(), "Painting".to_string(), "RustFFI".to_string()]);
    expose_css_pixels_as_raw_i32(&mut painting_config);
    let libgfx_src_dir = manifest_dir.join("../../LibGfx/Rust/src");
    let painting_sources = [
        libgfx_src_dir.join("geometry.rs"),
        libgfx_src_dir.join("matrix.rs"),
        libgfx_src_dir.join("color.rs"),
        libgfx_src_dir.join("corner_radii.rs"),
        libgfx_src_dir.join("paint_enums.rs"),
        manifest_dir.join("src/painting/display_list/commands.rs"),
    ];
    painting_config.export.include = Vec::new();
    for libgfx_source in &painting_sources[..painting_sources.len() - 1] {
        painting_config.export.include.extend(public_type_names(libgfx_source)?);
    }
    painting_config.export.include.extend(
        [
            "OptionalFloatRect",
            "OptionalColor",
            "OptionalU32",
            "OptionalF32",
            "OptionalAffineTransform",
            "VisualContextIndex",
            "FontResourceId",
            "ImageFrameResourceId",
            "VideoSinkResourceId",
            "DisplayListResourceId",
            "CanvasId",
            "CompositorContextId",
            "UniqueNodeId",
        ]
        .map(String::from),
    );
    generate_ffi_header_strict(
        painting_config,
        &painting_sources,
        &out_dir,
        Path::new("Painting/PaintingRustFFI.h"),
    );

    let mut display_list_commands_config = base_config;
    display_list_commands_config.namespaces = Some(vec!["Web".to_string(), "Painting".to_string()]);
    let commands_source = manifest_dir.join("src/painting/display_list/commands.rs");
    let types_with_existing_cpp_definitions = [
        "VisualContextIndex",
        "FontResourceId",
        "ImageFrameResourceId",
        "VideoSinkResourceId",
        "DisplayListResourceId",
        "CanvasId",
        "CompositorContextId",
        "UniqueNodeId",
        "OptionalFloatRect",
        "OptionalColor",
        "OptionalU32",
        "OptionalF32",
        "OptionalAffineTransform",
        "VISUAL_VIEWPORT_NODE_INDEX",
        "DISPLAY_LIST_COMMAND_TYPE_COUNT",
    ];
    display_list_commands_config.export.include = public_type_names(&commands_source)?
        .into_iter()
        .filter(|name| !types_with_existing_cpp_definitions.contains(&name.as_str()))
        .collect();
    display_list_commands_config.export.exclude = types_with_existing_cpp_definitions
        .iter()
        .map(|name| name.to_string())
        .collect();
    let references_renamed_to_real_types = [
        ("IntPoint", "Gfx::IntPoint"),
        ("FloatPoint", "Gfx::FloatPoint"),
        ("IntSize", "Gfx::IntSize"),
        ("FloatSize", "Gfx::FloatSize"),
        ("IntRect", "Gfx::IntRect"),
        ("FloatRect", "Gfx::FloatRect"),
        ("Color", "Gfx::Color"),
        ("AffineTransform", "Gfx::AffineTransform"),
        ("CornerRadius", "Gfx::CornerRadius"),
        ("CornerRadii", "Gfx::CornerRadii"),
        ("GradientInterpolationMethod", "Gfx::GradientInterpolationMethod"),
        ("WindingRule", "Gfx::WindingRule"),
        ("LineStyle", "Gfx::LineStyle"),
        ("ScalingMode", "Gfx::ScalingMode"),
        ("CompositingAndBlendingOperator", "Gfx::CompositingAndBlendingOperator"),
        ("MaskKind", "Gfx::MaskKind"),
        ("Orientation", "Gfx::Orientation"),
        ("ShouldAntiAlias", "Gfx::ShouldAntiAlias"),
        ("CornerClip", "Gfx::CornerClip"),
        ("InterpolationColorSpace", "Gfx::InterpolationColorSpace"),
        ("CapStyle", "Gfx::Path::CapStyle"),
        ("JoinStyle", "Gfx::Path::JoinStyle"),
        ("OptionalFloatRect", "Optional<Gfx::FloatRect>"),
        ("OptionalColor", "Optional<Gfx::Color>"),
        ("OptionalU32", "Optional<u32>"),
        ("OptionalF32", "Optional<float>"),
        ("OptionalAffineTransform", "Optional<Gfx::AffineTransform>"),
        ("CompositorContextId", "Web::Compositor::CompositorContextId"),
        ("UniqueNodeId", "UniqueNodeID"),
    ];
    for (rust_name, cpp_name) in references_renamed_to_real_types {
        display_list_commands_config
            .export
            .rename
            .insert(rust_name.to_string(), cpp_name.to_string());
    }
    display_list_commands_config.includes = [
        "AK/Forward.h",
        "AK/Optional.h",
        "AK/StringView.h",
        "AK/Types.h",
        "LibGfx/AffineTransform.h",
        "LibGfx/AntiAliasing.h",
        "LibGfx/Color.h",
        "LibGfx/CompositingAndBlendingOperator.h",
        "LibGfx/CornerRadii.h",
        "LibGfx/Forward.h",
        "LibGfx/GradientInterpolation.h",
        "LibGfx/InterpolationColorSpace.h",
        "LibGfx/LineStyle.h",
        "LibGfx/Orientation.h",
        "LibGfx/Path.h",
        "LibGfx/Point.h",
        "LibGfx/Rect.h",
        "LibGfx/ScalingMode.h",
        "LibGfx/Size.h",
        "LibGfx/WindingRule.h",
        "LibWeb/Compositor/Types.h",
        "LibWeb/Forward.h",
        "LibWeb/Painting/DisplayListResourceIds.h",
        "LibWeb/Painting/VisualContextIndex.h",
    ]
    .into_iter()
    .map(String::from)
    .collect();
    for command in display_list_command_impl_facts(&commands_source)? {
        let name = &command.name;
        display_list_commands_config.export.pre_body.insert(
            name.clone(),
            format!(
                "    static constexpr StringView command_name = \"{name}\"sv;\n    static constexpr DisplayListCommandType command_type = DisplayListCommandType::{name};"
            ),
        );
        let mut member_declarations = String::new();
        if command.has_bounding_rect {
            member_declarations.push_str("    [[nodiscard]] Gfx::IntRect bounding_rect() const;\n");
        }
        if command.has_is_clip {
            member_declarations.push_str("    bool is_clip() const;\n");
        }
        member_declarations.push_str("    void dump(StringBuilder&) const;");
        display_list_commands_config
            .export
            .body
            .insert(name.clone(), member_declarations);
    }
    generate_ffi_header_strict(
        display_list_commands_config,
        &[commands_source],
        &out_dir,
        Path::new("Painting/DisplayListCommandsGenerated.h"),
    );

    Ok(())
}
