// https://dom.spec.whatwg.org/#document
// https://html.spec.whatwg.org/multipage/dom.html#the-document-object
[Exposed=Window, LegacyOverrideBuiltins]
interface Document : Node {
    constructor();

    [ImplementedAs=has_focus_for_bindings] boolean hasFocus();

    [PutForwards=href, LegacyUnforgeable] readonly attribute Location? location;
    attribute Utf16USVString domain;

    readonly attribute DOMImplementation implementation;

    [ImplementedAs=url_string_for_bindings] readonly attribute Utf16DOMString URL;
    readonly attribute Utf16DOMString documentURI;

    readonly attribute Utf16DOMString characterSet;
    readonly attribute Utf16DOMString charset;
    readonly attribute Utf16DOMString inputEncoding;
    readonly attribute Utf16DOMString contentType;

    readonly attribute WindowProxy? defaultView;

    [CEReactions] Document open(optional Utf16DOMString unused1, optional Utf16DOMString unused2);
    WindowProxy? open(Utf16USVString url, Utf16DOMString name, Utf16DOMString features);
    [CEReactions] undefined close();
    [CEReactions] undefined write((TrustedHTML or Utf16DOMString)... text);
    [CEReactions] undefined writeln((TrustedHTML or Utf16DOMString)... text);

    static Document parseHTMLUnsafe((TrustedHTML or Utf16DOMString) html);

    attribute Utf16DOMString cookie;

    // https://html.spec.whatwg.org/multipage/obsolete.html#Document-partial
    [CEReactions, LegacyNullToEmptyString] attribute Utf16DOMString fgColor;
    [CEReactions, LegacyNullToEmptyString] attribute Utf16DOMString linkColor;
    [CEReactions, LegacyNullToEmptyString] attribute Utf16DOMString vlinkColor;
    [CEReactions, LegacyNullToEmptyString] attribute Utf16DOMString alinkColor;
    [CEReactions, LegacyNullToEmptyString] attribute Utf16DOMString bgColor;

    readonly attribute Utf16DOMString referrer;


    Element? getElementById(Utf16DOMString id);
    NodeList getElementsByName(Utf16DOMString name);
    HTMLCollection getElementsByTagName([Utf16FlyString] Utf16DOMString tagName);
    HTMLCollection getElementsByTagNameNS([Utf16FlyString] Utf16DOMString? namespace, [Utf16FlyString] Utf16DOMString localName);
    HTMLCollection getElementsByClassName(Utf16DOMString className);

    [SameObject] readonly attribute HTMLCollection applets;
    [SameObject] readonly attribute HTMLCollection anchors;
    [SameObject] readonly attribute HTMLCollection images;
    [SameObject] readonly attribute HTMLCollection embeds;
    [SameObject] readonly attribute HTMLCollection plugins;
    [SameObject] readonly attribute HTMLCollection links;
    [SameObject] readonly attribute HTMLCollection forms;
    [SameObject] readonly attribute HTMLCollection scripts;

    readonly attribute HTMLAllCollection all;

    undefined clear();
    undefined captureEvents();
    undefined releaseEvents();

    [CEReactions, NewObject] Element createElement([Utf16FlyString] Utf16DOMString tagName, optional ([Utf16FlyString] Utf16DOMString or ElementCreationOptions) options = {});
    [CEReactions, NewObject] Element createElementNS([Utf16FlyString] Utf16DOMString? namespace, [Utf16FlyString] Utf16DOMString qualifiedName, optional ([Utf16FlyString] Utf16DOMString or ElementCreationOptions) options = {});
    DocumentFragment createDocumentFragment();
    Text createTextNode(Utf16DOMString data);
    [NewObject] CDATASection createCDATASection(Utf16DOMString data);
    Comment createComment(Utf16DOMString data);
    [NewObject] ProcessingInstruction createProcessingInstruction([Utf16FlyString] Utf16DOMString target, Utf16DOMString data);

    [NewObject] Attr createAttribute([Utf16FlyString] Utf16DOMString localName);
    [NewObject] Attr createAttributeNS([Utf16FlyString] Utf16DOMString? namespace, [Utf16FlyString] Utf16DOMString qualifiedName);

    Range createRange();
    Event createEvent([Utf16FlyString] Utf16DOMString interface);

    [CEReactions, NewObject] Node importNode(Node node, optional (boolean or ImportNodeOptions) options = false);
    [CEReactions, ImplementedAs=adopt_node_binding] Node adoptNode(Node node);

    readonly attribute [Utf16FlyString] Utf16DOMString compatMode;
    readonly attribute DocumentType? doctype;

    readonly attribute Element? documentElement;
    [CEReactions] attribute Utf16DOMString dir;
    [CEReactions] attribute HTMLElement? body;
    readonly attribute HTMLHeadElement? head;
    readonly attribute HTMLScriptElement? currentScript;

    readonly attribute Utf16DOMString lastModified;
    readonly attribute [Utf16FlyString] Utf16DOMString readyState;

    [CEReactions] attribute Utf16DOMString title;

    readonly attribute boolean hidden;
    readonly attribute [Utf16FlyString] Utf16DOMString visibilityState;

    [NewObject] NodeIterator createNodeIterator(Node root, optional unsigned long whatToShow = 0xFFFFFFFF, optional NodeFilter? filter = null);
    [NewObject] TreeWalker createTreeWalker(Node root, optional unsigned long whatToShow = 0xFFFFFFFF, optional NodeFilter? filter = null);

    Selection? getSelection();

    [CEReactions] attribute Utf16DOMString designMode;

    // https://drafts.csswg.org/web-animations-1/#extensions-to-the-document-interface
    readonly attribute DocumentTimeline timeline;

    // https://drafts.csswg.org/cssom-view/#extensions-to-the-document-interface
    Element? elementFromPoint(double x, double y);
    sequence<Element> elementsFromPoint(double x, double y);
    CaretPosition? caretPositionFromPoint(double x, double y, optional CaretPositionFromPointOptions options = {});
    readonly attribute Element? scrollingElement;

    // https://w3c.github.io/editing/docs/execCommand/
    // FIXME: [CEReactions] boolean execCommand([Utf16FlyString] Utf16DOMString commandId, optional boolean showUI = false, optional (TrustedHTML or Utf16DOMString) value = "");
    [CEReactions] boolean execCommand([Utf16FlyString] Utf16DOMString commandId, optional boolean showUI = false, optional Utf16DOMString value = "");
    boolean queryCommandEnabled([Utf16FlyString] Utf16DOMString commandId);
    boolean queryCommandIndeterm([Utf16FlyString] Utf16DOMString commandId);
    boolean queryCommandState([Utf16FlyString] Utf16DOMString commandId);
    boolean queryCommandSupported([Utf16FlyString] Utf16DOMString commandId);
    Utf16DOMString queryCommandValue([Utf16FlyString] Utf16DOMString commandId);

    // special event handler IDL attributes that only apply to Document objects
    [LegacyLenientThis] attribute EventHandler onreadystatechange;
    attribute EventHandler onvisibilitychange;

    // https://drafts.csswg.org/css-view-transitions-1/#additions-to-document-api
    [Experimental] ViewTransition startViewTransition(optional ViewTransitionUpdateCallback updateCallback);

    // https://w3c.github.io/svgwg/svg2-draft/struct.html#InterfaceDocumentExtensions
    readonly attribute SVGSVGElement? rootElement;
    
    // https://w3c.github.io/pointerlock/#extensions-to-the-document-interface
    undefined exitPointerLock();
};

dictionary CaretPositionFromPointOptions {
    sequence<ShadowRoot> shadowRoots = [];
};

// https://dom.spec.whatwg.org/#dictdef-elementcreationoptions
dictionary ElementCreationOptions {
    CustomElementRegistry? customElementRegistry;
    [Utf16FlyString] Utf16DOMString is;
};

// https://dom.spec.whatwg.org/#dictdef-importnodeoptions
dictionary ImportNodeOptions {
    CustomElementRegistry customElementRegistry;
    boolean selfOnly = false;
};

Document includes ParentNode;
Document includes GlobalEventHandlers;
Document includes DocumentOrShadowRoot;
Document includes FontFaceSource;
