// https://dom.spec.whatwg.org/#documenttype
[Exposed=Window]
interface DocumentType : Node {
    readonly attribute DOMString name;
    readonly attribute DOMString publicId;
    readonly attribute DOMString systemId;
};

DocumentType includes ChildNode;
