// https://dom.spec.whatwg.org/#documentorshadowroot
interface mixin DocumentOrShadowRoot {
    readonly attribute CustomElementRegistry? customElementRegistry;
};

// https://html.spec.whatwg.org/multipage/dom.html#the-documentorshadowroot-interface
partial interface mixin DocumentOrShadowRoot {
    readonly attribute Element? activeElement;
};
