// https://dom.spec.whatwg.org/#documenttype
[Exposed=Window]
interface DocumentType : Node {
    readonly attribute Utf16DOMString name;
    readonly attribute Utf16DOMString publicId;
    readonly attribute Utf16DOMString systemId;
};

DocumentType includes ChildNode;
