// https://dom.spec.whatwg.org/#domimplementation
[Exposed=Window]
interface DOMImplementation {
    [NewObject] DocumentType createDocumentType([Utf16FlyString] Utf16DOMString qualifiedName, Utf16DOMString publicId, Utf16DOMString systemId);
    [NewObject] XMLDocument createDocument([Utf16FlyString] Utf16DOMString? namespace, [LegacyNullToEmptyString, Utf16FlyString] Utf16DOMString qualifiedName, optional DocumentType? doctype = null);
    [NewObject] Document createHTMLDocument(optional Utf16DOMString title);

    boolean hasFeature(); // useless; always returns true
};
