// https://dom.spec.whatwg.org/#interface-domtokenlist
[Exposed=Window]
interface DOMTokenList {
    readonly attribute unsigned long length;
    getter Utf16DOMString? item(unsigned long index);
    boolean contains(Utf16DOMString token);
    [CEReactions] undefined add(Utf16DOMString... tokens);
    [CEReactions] undefined remove(Utf16DOMString... tokens);
    [CEReactions] boolean toggle(Utf16DOMString token, optional boolean force);
    [CEReactions] boolean replace(Utf16DOMString token, Utf16DOMString newToken);
    boolean supports(Utf16DOMString token);
    [CEReactions] stringifier attribute Utf16DOMString value;
    iterable<Utf16DOMString>;
};
