enum ScrollLogicalPosition { "start", "center", "end", "nearest" };
// https://drafts.csswg.org/cssom-view-1/#dictdef-scrollintoviewoptions
dictionary ScrollIntoViewOptions : ScrollOptions {
    ScrollLogicalPosition block = "start";
    ScrollLogicalPosition inline = "nearest";
    ScrollIntoViewContainer container = "all";
};

enum ScrollIntoViewContainer { "all", "nearest" };

// https://drafts.csswg.org/cssom-view-1/#dictdef-checkvisibilityoptions
dictionary CheckVisibilityOptions {
    boolean checkOpacity = false;
    boolean checkVisibilityCSS = false;
    boolean contentVisibilityAuto = false;
    boolean opacityProperty = false;
    boolean visibilityProperty = false;
};

// https://w3c.github.io/pointerlock/#pointerlockoptions-dictionary
dictionary PointerLockOptions {
    boolean unadjustedMovement = false;
};

// https://dom.spec.whatwg.org/#element
[Exposed=Window]
interface Element : Node {
    readonly attribute Utf16DOMString? namespaceURI;
    readonly attribute Utf16DOMString? prefix;
    readonly attribute Utf16DOMString localName;
    readonly attribute Utf16DOMString tagName;

    [Reflect, CEReactions] attribute Utf16DOMString id;
    [Reflect=class, CEReactions] attribute Utf16DOMString className;
    [SameObject, PutForwards=value] readonly attribute DOMTokenList classList;
    [Reflect, CEReactions, Unscopable] attribute Utf16DOMString slot;

    boolean hasAttributes();
    [SameObject] readonly attribute NamedNodeMap attributes;
    sequence<[Utf16FlyString] Utf16DOMString> getAttributeNames();
    Utf16DOMString? getAttribute([Utf16FlyString] Utf16DOMString qualifiedName);
    Utf16DOMString? getAttributeNS([Utf16FlyString] Utf16DOMString? namespace, [Utf16FlyString] Utf16DOMString localName);
    [CEReactions, ImplementedAs=set_attribute_for_bindings] undefined setAttribute([Utf16FlyString] Utf16DOMString qualifiedName, (TrustedType or Utf16DOMString) value);
    [CEReactions, ImplementedAs=set_attribute_ns_for_bindings] undefined setAttributeNS([Utf16FlyString] Utf16DOMString? namespace, [Utf16FlyString] Utf16DOMString qualifiedName, (TrustedType or Utf16DOMString) value);
    [CEReactions] undefined removeAttribute([Utf16FlyString] Utf16DOMString qualifiedName);
    [CEReactions] undefined removeAttributeNS([Utf16FlyString] Utf16DOMString? namespace, [Utf16FlyString] Utf16DOMString localName);
    [CEReactions] boolean toggleAttribute([Utf16FlyString] Utf16DOMString qualifiedName, optional boolean force);
    boolean hasAttribute([Utf16FlyString] Utf16DOMString qualifiedName);
    boolean hasAttributeNS([Utf16FlyString] Utf16DOMString? namespace, [Utf16FlyString] Utf16DOMString localName);

    Attr? getAttributeNode([Utf16FlyString] Utf16DOMString qualifiedName);
    Attr? getAttributeNodeNS([Utf16FlyString] Utf16DOMString? namespace, [Utf16FlyString] Utf16DOMString localName);
    [CEReactions, ImplementedAs=set_attribute_node_for_bindings] Attr? setAttributeNode(Attr attr);
    [CEReactions, ImplementedAs=set_attribute_node_ns_for_bindings] Attr? setAttributeNodeNS(Attr attr);
    [CEReactions] Attr removeAttributeNode(Attr attr);

    ShadowRoot attachShadow(ShadowRootInit init);
    [ImplementedAs=shadow_root_for_bindings] readonly attribute ShadowRoot? shadowRoot;

    readonly attribute CustomElementRegistry? customElementRegistry;

    boolean matches(Utf16DOMString selectors);
    Element? closest(Utf16DOMString selectors);
    [ImplementedAs=matches] boolean webkitMatchesSelector(Utf16DOMString selectors); // legacy alias of .matches

    HTMLCollection getElementsByTagName([Utf16FlyString] Utf16DOMString tagName);
    HTMLCollection getElementsByTagNameNS([Utf16FlyString] Utf16DOMString? namespace, [Utf16FlyString] Utf16DOMString localName);
    HTMLCollection getElementsByClassName(Utf16DOMString className);

    [CEReactions] Element? insertAdjacentElement(Utf16DOMString where, Element element); // legacy
    undefined insertAdjacentText(Utf16DOMString where, Utf16DOMString data); // legacy

    // https://dom.spec.whatwg.org/#interface-nondocumenttypechildnode
    readonly attribute Element? nextElementSibling;
    readonly attribute Element? previousElementSibling;

    // https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface
    [ImplementedAs=get_client_rects_for_bindings] DOMRectList getClientRects();
    [ImplementedAs=get_bounding_client_rect_for_bindings] DOMRect getBoundingClientRect();

    boolean checkVisibility(optional CheckVisibilityOptions options = {});

    Promise<undefined> scrollIntoView(optional (boolean or ScrollIntoViewOptions) arg = {});
    Promise<undefined> scroll(optional ScrollToOptions options = {});
    Promise<undefined> scroll(unrestricted double x, unrestricted double y);
    [ImplementedAs=scroll] Promise<undefined> scrollTo(optional ScrollToOptions options = {});
    [ImplementedAs=scroll] Promise<undefined> scrollTo(unrestricted double x, unrestricted double y);
    Promise<undefined> scrollBy(optional ScrollToOptions options = {});
    Promise<undefined> scrollBy(unrestricted double x, unrestricted double y);
    attribute unrestricted double scrollTop;
    attribute unrestricted double scrollLeft;
    readonly attribute long scrollWidth;
    readonly attribute long scrollHeight;
    readonly attribute long clientTop;
    readonly attribute long clientLeft;
    readonly attribute long clientWidth;
    readonly attribute long clientHeight;
    readonly attribute double currentCSSZoom;

    // https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-parsing-and-serialization
    [CEReactions] undefined setHTMLUnsafe((TrustedHTML or Utf16DOMString) html);
    Utf16DOMString getHTML(optional GetHTMLOptions options = {});

    [CEReactions, LegacyNullToEmptyString] attribute (TrustedHTML or Utf16DOMString) innerHTML;

    [CEReactions, LegacyNullToEmptyString] attribute (TrustedHTML or Utf16DOMString) outerHTML;

    [CEReactions] undefined insertAdjacentHTML(Utf16DOMString position, (TrustedHTML or Utf16DOMString) text);

    // https://w3c.github.io/pointerevents/#extensions-to-the-element-interface
    undefined setPointerCapture(long pointerId);
    undefined releasePointerCapture(long pointerId);
    boolean hasPointerCapture(long pointerId);
    
    // https://drafts.csswg.org/css-shadow-1/#idl
    [SameObject, PutForwards=value, ImplementedAs=part_list] readonly attribute DOMTokenList part;
    
    // https://w3c.github.io/pointerlock/#requestPointerLock
    Promise<undefined> requestPointerLock(optional PointerLockOptions options = {});
};

dictionary GetHTMLOptions {
    boolean serializableShadowRoots = false;
    sequence<ShadowRoot> shadowRoots = [];
};

dictionary ShadowRootInit {
    required ShadowRootMode mode;
    boolean delegatesFocus = false;
    SlotAssignmentMode slotAssignment = "named";
    boolean clonable = false;
    boolean serializable = false;
    CustomElementRegistry? customElementRegistry;
};

Element includes ParentNode;
Element includes ChildNode;
// https://w3c.github.io/aria/#ARIAMixin
Element includes ARIAMixin;
Element includes Slottable;
// https://drafts.csswg.org/web-animations-1/#extensions-to-the-element-interface
Element includes Animatable;
