// https://dom.spec.whatwg.org/#eventtarget
[Exposed=*]
interface EventTarget {
    constructor();

    [ImplementedInBindings] undefined addEventListener(DOMString type, EventListener? callback, optional (AddEventListenerOptions or boolean) options = {});
    [ImplementedInBindings] undefined removeEventListener(DOMString type, EventListener? callback, optional (EventListenerOptions or boolean) options = {});
    [ImplementedAs=dispatch_event_for_bindings] boolean dispatchEvent(Event event);
};

dictionary EventListenerOptions {
    boolean capture = false;
};

dictionary AddEventListenerOptions : EventListenerOptions {
    boolean passive;
    boolean once = false;
    AbortSignal signal;
};
