// https://dom.spec.whatwg.org/#interface-mutationrecord
[Exposed=Window]
interface MutationRecord {
    readonly attribute DOMString type;
    [DirectGetter, SameObject] readonly attribute Node target;
    [DirectGetter, SameObject] readonly attribute NodeList addedNodes;
    [DirectGetter, SameObject] readonly attribute NodeList removedNodes;
    [DirectGetter] readonly attribute Node? previousSibling;
    [DirectGetter] readonly attribute Node? nextSibling;
    readonly attribute DOMString? attributeName;
    readonly attribute DOMString? attributeNamespace;
    readonly attribute DOMString? oldValue;
};
