// https://dom.spec.whatwg.org/#nondocumenttypechildnode
interface mixin NonDocumentTypeChildNode {
    readonly attribute Element? previousElementSibling;
    readonly attribute Element? nextElementSibling;
};
