// https://dom.spec.whatwg.org/#text
[Exposed=Window]
interface Text : CharacterData {
    constructor(optional DOMString data = "");

    [NewObject] Text splitText(unsigned long offset);
    readonly attribute DOMString wholeText;
};

Text includes Slottable;
