// https://dom.spec.whatwg.org/#interface-treewalker
[Exposed=Window]
interface TreeWalker {
    [SameObject] readonly attribute Node root;
    readonly attribute unsigned long whatToShow;

    readonly attribute NodeFilter? filter;

    attribute Node currentNode;

    [NeedsCallerRealm] Node? parentNode();
    [NeedsCallerRealm] Node? firstChild();
    [NeedsCallerRealm] Node? lastChild();
    [NeedsCallerRealm] Node? previousSibling();
    [NeedsCallerRealm] Node? nextSibling();
    [NeedsCallerRealm] Node? previousNode();
    [NeedsCallerRealm] Node? nextNode();
};
