// https://registry.khronos.org/webgl/specs/latest/1.0/#5.15
[Exposed=(Window,Worker)]
interface WebGLContextEvent : Event {
    constructor([Utf16FlyString] Utf16DOMString type, optional WebGLContextEventInit eventInit = {});
    readonly attribute Utf16DOMString statusMessage;
};

dictionary WebGLContextEventInit : EventInit {
    Utf16DOMString statusMessage = "";
};
