name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Do not cancel in-progress runs if a labeling action took place (other than 'windows'). Otherwise, adding irrelevant
  # labels causes existing runs to be canceled and a new (identical) run to be started.
  cancel-in-progress: ${{ (github.event.action != 'labeled' && github.event.action != 'unlabeled') || github.event.label.name == 'windows' }}

jobs:
  CI:
    # Only run this job if the PR has the 'windows' label.
    if: |
      github.repository == 'LadybirdBrowser/ladybird'
      && contains(github.event.pull_request.labels.*.name, 'windows')
    name: 'Windows, x86_64, Windows_SanitizerCI, ClangCL'
    uses: ./.github/workflows/lagom-template.yml
    with:
      toolchain: 'ClangCL'
      os_name: 'Windows'
      runner_labels: '["windows-2025"]'
      arch: 'x86_64'
      build_preset: 'Windows_Sanitizer_CI'
      clang_plugins: false
