name: ClusterFuzzLite

on:
  workflow_dispatch:

permissions: read-all

concurrency:
  group: clusterfuzzlite-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fuzz:
    name: Build and run fuzzers
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps:
      - name: Build fuzzers (AddressSanitizer)
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: c++
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: address
      - name: Run fuzzers (AddressSanitizer)
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: batch
          sanitizer: address
