name: "Build on ${{ inputs.distribution_name }}"

on:
    workflow_call:
        inputs:
            distribution_name:
                required: true
                type: string
            distribution_version:
                required: false
                type: string
                default: latest
    workflow_dispatch:
        inputs:
            distribution_name:
                description: Linux distribution name
                required: true
                type: string
            distribution_version:
                description: Linux distribution CI image tag (best kept as 'latest' in most cases)
                required: false
                type: string
                default: latest

jobs:
    set-image:
        name: "Set CI image"
        runs-on: "ubuntu-latest"
        outputs:
            ci-image-name: ${{ steps.ci-image-name.outputs.ci-image-name }}
        steps:
            # github.repository is case-sensitive, but job.container mandates lowercase
            - name: "Ensure lowercase image prefix"
              id: ci-image-name
              env:
                  IMAGE_NAME: ${{ inputs.distribution_name }}:${{ inputs.distribution_version }}
              run: |
                  IMAGE_PREFIX="ghcr.io/$GITHUB_REPOSITORY/ci-images"
                  IMAGE_FQN_LOWER=$(echo "$IMAGE_PREFIX/$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
                  echo "ci-image-name=$IMAGE_FQN_LOWER" | tee -a "$GITHUB_OUTPUT"

    distribution-ci:
        name: "${{ inputs.distribution_name }}"
        runs-on: "ubuntu-latest"
        needs: set-image
        permissions:
            packages: read
        container: ${{ needs.set-image.outputs.ci-image }}
        steps:
            - uses: actions/checkout@v4
              if: ${{ github.event_name != 'pull_request' }}
            - uses: actions/checkout@v4
              if: ${{ github.event_name == 'pull_request' }}
              with:
                  ref: refs/pull/${{ github.event.pull_request.number }}/merge
            - name: Create Build Environment
              run: |
                  ./Meta/ladybird.sh vcpkg
            - name: Build Ladybird
              run: |
                  ./Meta/ladybird.sh build
