#import <Compression/CompressionStream.idl>
#import <Streams/GenericTransformStream.idl>

// https://compression.spec.whatwg.org/#decompressionstream
[Exposed=*]
interface DecompressionStream {
    constructor(CompressionFormat format);
};

DecompressionStream includes GenericTransformStream;
