// https://webassembly.github.io/spec/js-api/#instances
[LegacyNamespace=WebAssembly, Exposed=*]
interface Instance {
    [ImplementedInBindings] constructor(Module module, optional object importObject);

    [ImplementedInBindings, NeedsCallerRealmForGetter] readonly attribute object exports;
};
