enum AddressType {
    "i32",
    "i64"
};

typedef any AddressValue;

enum TableKind {
    "externref",
    "anyfunc"
};

dictionary TableDescriptor {
    required TableKind element;
    required AddressValue initial;
    AddressValue maximum;
    AddressType address;
};

// https://webassembly.github.io/spec/js-api/#tables
[LegacyNamespace=WebAssembly, Exposed=*]
interface Table {
    [ImplementedInBindings] constructor(TableDescriptor descriptor, optional any value);

    [ImplementedInBindings, NeedsCallerRealm] AddressValue grow(AddressValue delta, optional any value);

    [ImplementedInBindings, NeedsCallerRealm] any get(AddressValue index);
    [ImplementedInBindings, NeedsCallerRealm] undefined set(AddressValue index, optional any value);

    [ImplementedInBindings, NeedsCallerRealmForGetter] readonly attribute AddressValue length;
};
