[package]
name = "libcompositing_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = []
allocator = ["dep:ladybird_allocator"]

[dependencies]
foldhash = "0.1"
ladybird_allocator = { path = "../../RustAllocator", optional = true }
libgfx_rust = { path = "../../LibGfx/Rust", default-features = false }

[build-dependencies]
cbindgen = "0.29"

[lints]
workspace = true
